export enum IntegrationErrorCode {
  INTEGRATION_PROVIDER_UNAVAILABLE = 'INTEGRATION_PROVIDER_UNAVAILABLE',

  INTEGRATION_AUTH_FAILED = 'INTEGRATION_AUTH_FAILED',

  INTEGRATION_TIMEOUT = 'INTEGRATION_TIMEOUT',

  INTEGRATION_RATE_LIMITED = 'INTEGRATION_RATE_LIMITED',

  INTEGRATION_PAYLOAD_INVALID = 'INTEGRATION_PAYLOAD_INVALID',

  INTEGRATION_CONTRACT_UNSUPPORTED = 'INTEGRATION_CONTRACT_UNSUPPORTED',

  WEBHOOK_SIGNATURE_FAILED = 'WEBHOOK_SIGNATURE_FAILED',

  SYNCHRONIZATION_CONFLICT = 'SYNCHRONIZATION_CONFLICT',

  INTERNAL_INTEGRATION_ERROR = 'INTERNAL_INTEGRATION_ERROR',

  INTEGRATION_INVALID_STATE = 'INTEGRATION_INVALID_STATE',
}
