export enum PlatformErrorCode {
  APPLICATION_NOT_FOUND = 'PLATFORM_APPLICATION_NOT_FOUND',
  APPLICATION_CODE_EXISTS = 'PLATFORM_APPLICATION_CODE_EXISTS',
  APPLICATION_ARCHIVED = 'PLATFORM_APPLICATION_ARCHIVED',

  VERSION_NOT_FOUND = 'PLATFORM_VERSION_NOT_FOUND',
  VERSION_INVALID = 'PLATFORM_VERSION_INVALID',
  VERSION_EXISTS = 'PLATFORM_VERSION_EXISTS',
  VERSION_IMMUTABLE = 'PLATFORM_VERSION_IMMUTABLE',
  VERSION_LIFECYCLE_INVALID = 'PLATFORM_VERSION_LIFECYCLE_INVALID',

  PERMISSION_DENIED = 'PLATFORM_PERMISSION_DENIED',
  TENANT_VIOLATION = 'PLATFORM_TENANT_VIOLATION',
}
