export enum PlatformErrorCode {
  APPLICATION_NOT_FOUND = 'PLATFORM_APPLICATION_NOT_FOUND',
  APPLICATION_CODE_EXISTS = 'PLATFORM_APPLICATION_CODE_EXISTS',
  APPLICATION_ARCHIVED = 'PLATFORM_APPLICATION_ARCHIVED',

  VERSION_NOT_FOUND = 'PLATFORM_VERSION_NOT_FOUND',
  VERSION_INVALID = 'PLATFORM_VERSION_INVALID',
  VERSION_EXISTS = 'PLATFORM_VERSION_EXISTS',
  VERSION_IMMUTABLE = 'PLATFORM_VERSION_IMMUTABLE',
  VERSION_LIFECYCLE_INVALID = 'PLATFORM_VERSION_LIFECYCLE_INVALID',

  PERMISSION_DENIED = 'PLATFORM_PERMISSION_DENIED',
  TENANT_VIOLATION = 'PLATFORM_TENANT_VIOLATION',

  ENVIRONMENT_NOT_FOUND = 'PLATFORM_ENVIRONMENT_NOT_FOUND',
  ENVIRONMENT_CODE_EXISTS = 'PLATFORM_ENVIRONMENT_CODE_EXISTS',
  ENVIRONMENT_ARCHIVED = 'PLATFORM_ENVIRONMENT_ARCHIVED',
  ENVIRONMENT_PRODUCTION_PROTECTED = 'PLATFORM_ENVIRONMENT_PRODUCTION_PROTECTED',

  // CONTRACTS
  CONTRACT_NOT_FOUND = 'PLATFORM_CONTRACT_NOT_FOUND',
  CONTRACT_EXISTS = 'PLATFORM_CONTRACT_EXISTS',
  CONTRACT_INVALID_STATUS = 'PLATFORM_CONTRACT_INVALID_STATUS',
  CONTRACT_LOCKED = 'PLATFORM_CONTRACT_LOCKED',
  CONTRACT_VERSION_IMMUTABLE = 'PLATFORM_CONTRACT_VERSION_IMMUTABLE',
  CONTRACT_COMPATIBILITY_ERROR = 'PLATFORM_CONTRACT_COMPATIBILITY_ERROR',

  CONFIGURATION_NOT_FOUND = 'PLATFORM_CONFIGURATION_NOT_FOUND',
  CONFIGURATION_EXISTS = 'PLATFORM_CONFIGURATION_EXISTS',
  CONFIGURATION_INVALID_SCOPE = 'PLATFORM_CONFIGURATION_INVALID_SCOPE',
  CONFIGURATION_INVALID_TYPE = 'PLATFORM_CONFIGURATION_INVALID_TYPE',
  CONFIGURATION_INVALID_VALUE = 'PLATFORM_CONFIGURATION_INVALID_VALUE',
  CONFIGURATION_IMMUTABLE = 'PLATFORM_CONFIGURATION_IMMUTABLE',
  CONFIGURATION_OVERRIDE_FORBIDDEN = 'PLATFORM_CONFIGURATION_OVERRIDE_FORBIDDEN',
}
