import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { PackCapability, PackFeature, PackFeatureCapability, PackModule, PackOutboxEvent, PackVersion } from '../../entities';
import { PackCapabilityStatus, PackFeatureStatus, PackManifestStatus, PackValidationStatus, PackVersionStatus } from '../../../../common/enums';
import { AuditService } from '../../audit/audit.service';
import { AttachCapabilityDto, CapabilityQueryDto, CreateCapabilityDto, CreateFeatureDto, FeatureQueryDto, UpdateFeatureDto } from './dto/feature-capability.dto';

@Injectable()
export class FeaturesService {
  private readonly features: Repository<PackFeature>;
  private readonly capabilities: Repository<PackCapability>;
  private readonly links: Repository<PackFeatureCapability>;
  private readonly versions: Repository<PackVersion>;
  private readonly modules: Repository<PackModule>;
  constructor(@InjectDataSource() private readonly dataSource: DataSource, private readonly audit: AuditService) { this.features = dataSource.getRepository(PackFeature); this.capabilities = dataSource.getRepository(PackCapability); this.links = dataSource.getRepository(PackFeatureCapability); this.versions = dataSource.getRepository(PackVersion); this.modules = dataSource.getRepository(PackModule); }

  async listFeatures(tenantId: string, versionId: string, query: FeatureQueryDto = new FeatureQueryDto()) { await this.version(tenantId, versionId); const qb = this.features.createQueryBuilder('feature').where('feature.tenantId = :tenantId AND feature.packVersionId = :versionId', { tenantId, versionId }); if (query.moduleId) qb.andWhere('feature.moduleId = :moduleId', { moduleId: query.moduleId }); if (query.featureType) qb.andWhere('feature.featureType = :featureType', { featureType: query.featureType }); if (query.status) qb.andWhere('feature.status = :status', { status: query.status }); if (query.enabled !== undefined) qb.andWhere('feature.enabled = :enabled', { enabled: query.enabled }); if (query.search) qb.andWhere('(feature.code ILIKE :search OR feature.name ILIKE :search OR feature.description ILIKE :search)', { search: `%${query.search}%` }); return qb.orderBy('feature.createdAt', 'ASC').getMany(); }
  async getFeature(tenantId: string, id: string) { const feature = await this.features.findOne({ where: { id, tenantId }, relations: ['module'] }); if (!feature) throw new NotFoundException('PACK_FEATURE_NOT_FOUND'); return feature; }
  async createFeature(tenantId: string, versionId: string, actorId: string, dto: CreateFeatureDto) { const version = await this.mutableVersion(tenantId, versionId); await this.validateModule(tenantId, versionId, dto.moduleId); const exists = await this.features.findOne({ where: { tenantId, packVersionId: versionId, code: dto.code } }); if (exists) throw new ConflictException('PACK_FEATURE_CODE_ALREADY_EXISTS'); this.assertSafeConfig(dto.configuration); const feature = await this.features.save(this.features.create({ ...dto, tenantId, packVersionId: versionId, createdBy: actorId, status: PackFeatureStatus.DRAFT, visibility: dto.visibility, configuration: dto.configuration ?? {}, metadata: dto.metadata ?? {} })); await this.invalidate(version, tenantId, actorId, 'pack.feature.created', feature.id); return feature; }
  async updateFeature(tenantId: string, id: string, actorId: string, dto: UpdateFeatureDto) { const feature = await this.getFeature(tenantId, id); const version = await this.mutableVersion(tenantId, feature.packVersionId); if (dto.expectedVersion !== undefined && Number(dto.expectedVersion) !== feature.version) throw new ConflictException('PACK_FEATURE_CONFLICT'); await this.validateModule(tenantId, feature.packVersionId, dto.moduleId); this.assertSafeConfig(dto.configuration); const { expectedVersion: _expectedVersion, ...content } = dto; Object.assign(feature, content, { updatedBy: actorId, version: feature.version + 1 }); const saved = await this.features.save(feature); await this.invalidate(version, tenantId, actorId, 'pack.feature.updated', id); return saved; }
  async setEnabled(tenantId: string, id: string, actorId: string, enabled: boolean) { const feature = await this.getFeature(tenantId, id); const version = await this.mutableVersion(tenantId, feature.packVersionId); feature.enabled = enabled; feature.status = enabled ? PackFeatureStatus.ACTIVE : PackFeatureStatus.DISABLED; feature.updatedBy = actorId; feature.version += 1; const saved = await this.features.save(feature); await this.invalidate(version, tenantId, actorId, enabled ? 'pack.feature.enabled' : 'pack.feature.disabled', id); return saved; }
  async archiveFeature(tenantId: string, id: string, actorId: string) { const feature = await this.getFeature(tenantId, id); const version = await this.mutableVersion(tenantId, feature.packVersionId); feature.status = PackFeatureStatus.ARCHIVED; feature.enabled = false; feature.archivedAt = new Date(); feature.updatedBy = actorId; feature.version += 1; const saved = await this.features.save(feature); await this.invalidate(version, tenantId, actorId, 'pack.feature.archived', id); return saved; }
  async impact(tenantId: string, id: string) { const feature = await this.getFeature(tenantId, id); const links = await this.links.find({ where: { featureId: id }, relations: ['capability'] }); return { featureId: feature.id, blocking: [], warnings: links.filter((link) => link.required).map((link) => `Capability ${link.capabilityId} is required`), infos: [], capabilities: links.map((link) => link.capability.code), summary: { capabilities: links.length } }; }

  async listCapabilities(tenantId: string, query: CapabilityQueryDto = new CapabilityQueryDto()) { const qb = this.capabilities.createQueryBuilder('capability').where('capability.tenantId = :tenantId', { tenantId }); if (query.type) qb.andWhere('capability.capabilityType = :type', { type: query.type }); if (query.scope) qb.andWhere('capability.scope = :scope', { scope: query.scope }); if (query.status) qb.andWhere('capability.status = :status', { status: query.status }); if (query.namespace) qb.andWhere('capability.code LIKE :namespace', { namespace: `${query.namespace}.%` }); if (query.search) qb.andWhere('(capability.code ILIKE :search OR capability.name ILIKE :search)', { search: `%${query.search}%` }); return qb.orderBy('capability.code', 'ASC').getMany(); }
  async getCapability(tenantId: string, id: string) { const capability = await this.capabilities.findOne({ where: { id, tenantId } }); if (!capability) throw new NotFoundException('PACK_CAPABILITY_NOT_FOUND'); return capability; }
  async createCapability(tenantId: string, actorId: string, dto: CreateCapabilityDto) { const exists = await this.capabilities.findOne({ where: { tenantId, code: dto.code } }); if (exists) throw new ConflictException('PACK_CAPABILITY_CODE_ALREADY_EXISTS'); const capability = await this.capabilities.save(this.capabilities.create({ ...dto, tenantId, createdBy: actorId, status: dto.status ?? PackCapabilityStatus.DRAFT, metadata: dto.metadata ?? {} })); await this.event(tenantId, actorId, 'pack.capability.created', capability.id, { code: capability.code }); return capability; }
  async attach(tenantId: string, featureId: string, actorId: string, dto: AttachCapabilityDto) { const feature = await this.getFeature(tenantId, featureId); const version = await this.mutableVersion(tenantId, feature.packVersionId); await this.getCapability(tenantId, dto.capabilityId); const exists = await this.links.findOne({ where: { featureId, capabilityId: dto.capabilityId } }); if (exists) throw new ConflictException('PACK_CAPABILITY_ALREADY_ATTACHED'); const link = await this.links.save(this.links.create({ featureId, capabilityId: dto.capabilityId, relationType: dto.relationType, required: dto.required, configuration: dto.configuration ?? {} })); await this.invalidate(version, tenantId, actorId, 'pack.capability.attached', featureId); return link; }
  async detach(tenantId: string, featureId: string, capabilityId: string, actorId: string) { const feature = await this.getFeature(tenantId, featureId); const version = await this.mutableVersion(tenantId, feature.packVersionId); const link = await this.links.findOne({ where: { featureId, capabilityId } }); if (!link) throw new NotFoundException('PACK_CAPABILITY_NOT_FOUND'); await this.links.remove(link); await this.invalidate(version, tenantId, actorId, 'pack.capability.detached', featureId); }

  private async version(tenantId: string, id: string) { const version = await this.versions.findOne({ where: { id, tenantId } }); if (!version) throw new NotFoundException('PACK_VERSION_NOT_FOUND'); return version; }
  private async mutableVersion(tenantId: string, id: string) { const version = await this.version(tenantId, id); if ([PackVersionStatus.PUBLISHED, PackVersionStatus.SUPERSEDED, PackVersionStatus.DEPRECATED, PackVersionStatus.ARCHIVED].includes(version.status)) throw new ConflictException('PACK_VERSION_IMMUTABLE'); return version; }
  private async validateModule(tenantId: string, versionId: string, moduleId?: string) { if (!moduleId) return; const module = await this.modules.findOne({ where: { id: moduleId, tenantId, packVersionId: versionId } }); if (!module) throw new NotFoundException('PACK_MODULE_NOT_FOUND'); }
  private assertSafeConfig(configuration?: Record<string, unknown>) { if (configuration && /password|secret|token|credential|apiKey/i.test(JSON.stringify(configuration))) throw new ConflictException('PACK_FEATURE_CONFIG_INVALID'); }
  private async invalidate(version: PackVersion, tenantId: string, actorId: string, eventType: string, aggregateId: string) { const features = await this.features.find({ where: { tenantId, packVersionId: version.id }, order: { createdAt: 'ASC' } }); const links = features.length ? await this.links.find({ where: features.map((feature) => ({ featureId: feature.id })) }) : []; await this.versions.update({ id: version.id, tenantId, version: version.version }, { features: features.filter((feature) => feature.enabled).map((feature) => feature.code), capabilities: [...new Set(links.map((link) => link.capabilityId))], validationStatus: PackValidationStatus.OUTDATED, manifestStatus: PackManifestStatus.OUTDATED, snapshot: undefined, snapshotHash: undefined, manifest: undefined, manifestHash: undefined, version: version.version + 1 }); await this.event(tenantId, actorId, eventType, aggregateId, { packVersionId: version.id }); }
  private async event(tenantId: string, actorId: string, eventType: string, aggregateId: string, after: unknown) { await this.audit.log({ actorId, eventType, action: eventType.split('.').pop()?.toUpperCase() ?? 'UPDATE', targetType: 'PackFeature', targetId: aggregateId, after, metadata: { tenantId } }); await this.dataSource.getRepository(PackOutboxEvent).save({ tenantId, eventType, aggregateType: 'PackFeature', aggregateId, payload: { aggregateId } }); }
}
