import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { createHash } from 'crypto';
import { DataSource, ObjectLiteral } from 'typeorm';
import { ApplicationVersion } from '../entities/application-version.entity';
import { ContractArtifact } from '../entities/contract-artifact.entity';
import { DataModelDefinition } from '../entities/data-model.entity';
import { IntegrationBinding } from '../entities/integration-binding.entity';
import { IntegrationDefinition } from '../entities/integration-definition.entity';
import { RuntimeSnapshot } from '../entities/runtime-snapshot.entity';
import { VersionCapability } from '../entities/version-capability.entity';
import { VersionFeature } from '../entities/version-feature.entity';
import { VersionMenu } from '../entities/version-menu.entity';
import { ApplicationVersionStatus, VersionFeatureState } from '../../../common/enums';

@Injectable()
export class RuntimeBridgeService {
  constructor(@InjectDataSource() private readonly db: DataSource) {}
  private repo = <T extends ObjectLiteral>(t: any) => this.db.getRepository<T>(t);
  async manifest(versionId: string, environment?: string, channel?: string) { const version = await this.version(versionId); const [models, features, capabilities, menus, bindings] = await Promise.all([this.repo<DataModelDefinition>(DataModelDefinition).find({ where: { versionId } }), this.repo<VersionFeature>(VersionFeature).find({ where: { applicationVersionId: versionId }, relations: ['feature'] }), this.repo<VersionCapability>(VersionCapability).find({ where: { applicationVersionId: versionId }, relations: ['capability'] }), this.repo<VersionMenu>(VersionMenu).find({ where: { applicationVersionId: versionId, enabled: true } }), this.repo<IntegrationBinding>(IntegrationBinding).find({ where: { applicationVersionId: versionId, ...(environment ? { environment } : {}) } })]); const payload = { manifestVersion: '1.0.0', applicationId: version.applicationId, applicationVersionId: versionId, version: version.versionNumber, environment, channel, dataModels: models.map(x => ({ id: x.id, name: x.name, schemaVersion: x.schemaVersion })), features: features.filter(x => x.state !== VersionFeatureState.DISABLED).map(x => ({ code: x.feature?.code, state: x.state })).sort((a,b) => String(a.code).localeCompare(String(b.code))), capabilities: capabilities.filter(x => x.enabled).map(x => x.capability?.code).sort(), menus: menus.map(x => x.menuId).sort(), integrations: bindings.filter(x => x.status === 'ENABLED').map(x => ({ id: x.id, targetId: x.targetId, required: x.required })) }; return { ...payload, manifestHash: this.hash(payload) }; }
  async readiness(versionId: string, environment?: string) { const [manifest, bindings] = await Promise.all([this.manifest(versionId, environment), this.repo<IntegrationBinding>(IntegrationBinding).find({ where: { applicationVersionId: versionId, ...(environment ? { environment } : {}) } })]); const issues: Array<{ severity: string; code: string; bindingId?: string }> = bindings.filter(x => x.required && x.status !== 'ENABLED').map(x => ({ severity: 'ERROR', code: 'INTEGRATION_BINDING_INVALID', bindingId: x.id })); if (!manifest.capabilities.length) issues.push({ severity: 'WARNING', code: 'RUNTIME_NO_CAPABILITIES' }); return { ready: !issues.some(x => x.severity === 'ERROR'), manifestHash: manifest.manifestHash, issues }; }
  async generateContracts(versionId: string) { const manifest = await this.manifest(versionId); const types = { application: { applicationId: manifest.applicationId, version: manifest.version }, dataModel: manifest.dataModels, features: manifest.features, capabilities: manifest.capabilities, navigation: manifest.menus, integrations: manifest.integrations }; const r = this.repo<ContractArtifact>(ContractArtifact); return Promise.all(Object.entries(types).map(async ([contractType, content]) => { const contentHash = this.hash(content); const old = await r.findOne({ where: { applicationVersionId: versionId, contractType, contentHash } }); return old ?? r.save(r.create({ applicationId: manifest.applicationId, applicationVersionId: versionId, contractType, contentHash, content })); })); }
  async contracts(versionId: string, type?: string) { return this.repo<ContractArtifact>(ContractArtifact).find({ where: { applicationVersionId: versionId, ...(type ? { contractType: type } : {}) }, order: { generatedAt: 'DESC' } }); }
  async snapshot(versionId: string, environment?: string) { const version = await this.version(versionId); const manifest = await this.manifest(versionId, environment); const r = this.repo<RuntimeSnapshot>(RuntimeSnapshot); const old = await r.findOne({ where: { applicationVersionId: versionId, environment: environment ?? null as any, snapshotHash: manifest.manifestHash } }); return old ?? r.save(r.create({ applicationId: version.applicationId, applicationVersionId: versionId, environment, snapshotHash: manifest.manifestHash, manifest })); }
  async getSnapshot(versionId: string, environment?: string) { const x = await this.repo<RuntimeSnapshot>(RuntimeSnapshot).findOne({ where: { applicationVersionId: versionId, ...(environment ? { environment } : {}) }, order: { generatedAt: 'DESC' } }); if (!x) throw new NotFoundException('RUNTIME_SNAPSHOT_NOT_FOUND'); return x; }
  async createIntegration(data: Partial<IntegrationDefinition>) { const code = String(data.code ?? '').trim().toLowerCase(); if (!code || !data.name || !data.type || !data.adapterKey) throw new ConflictException('INTEGRATION_DEFINITION_INVALID'); const r = this.repo<IntegrationDefinition>(IntegrationDefinition); if (await r.findOne({ where: { code } })) throw new ConflictException('INTEGRATION_CODE_EXISTS'); return r.save(r.create({ ...data, code })); }
  async listIntegrations() { return this.repo<IntegrationDefinition>(IntegrationDefinition).find({ order: { code: 'ASC' } }); }
  async listBindings(applicationVersionId: string) { return this.repo<IntegrationBinding>(IntegrationBinding).find({ where: { applicationVersionId }, order: { createdAt: 'DESC' } }); }
  async bind(versionId: string, data: Partial<IntegrationBinding>) { const version = await this.editable(versionId); if (!data.integrationDefinitionId || !await this.repo<IntegrationDefinition>(IntegrationDefinition).findOne({ where: { id: data.integrationDefinitionId } })) throw new NotFoundException('INTEGRATION_NOT_FOUND'); const r = this.repo<IntegrationBinding>(IntegrationBinding); const old = await r.findOne({ where: { applicationVersionId: versionId, integrationDefinitionId: data.integrationDefinitionId, environment: data.environment ?? null as any } }); if (old) throw new ConflictException('INTEGRATION_BINDING_EXISTS'); return r.save(r.create({ ...data, applicationId: version.applicationId, applicationVersionId: versionId })); }
  async updateBinding(id: string, data: Partial<IntegrationBinding> & { expectedVersion?: number }) { const item = await this.binding(id); await this.editable(item.applicationVersionId); if (data.expectedVersion !== undefined && data.expectedVersion !== item.version) throw new ConflictException('VERSION_CONFLICT'); const { id: _id, applicationId: _a, applicationVersionId: _v, expectedVersion: _e, ...changes } = data; return this.repo<IntegrationBinding>(IntegrationBinding).save({ ...item, ...changes, version: item.version + 1 }); }
  async validateBinding(id: string) { const item = await this.binding(id); const valid = !!item.targetId && !!item.integrationDefinitionId; return { valid, issues: valid ? [] : [{ severity: 'ERROR', code: 'INTEGRATION_BINDING_INVALID' }] }; }
  async testBinding(id: string) { const check = await this.validateBinding(id); return { ...check, testedAt: new Date().toISOString(), adapterCalled: false }; }
  private hash(value: unknown) { return createHash('sha256').update(JSON.stringify(value)).digest('hex'); } private async version(id: string) { const x = await this.repo<ApplicationVersion>(ApplicationVersion).findOne({ where: { id } }); if (!x) throw new NotFoundException('VERSION_NOT_FOUND'); return x; } private async editable(id: string) { const x = await this.version(id); if ([ApplicationVersionStatus.PUBLISHED, ApplicationVersionStatus.ARCHIVED, ApplicationVersionStatus.SUPERSEDED].includes(x.status)) throw new ConflictException('VERSION_NOT_EDITABLE'); return x; } private async binding(id: string) { const x = await this.repo<IntegrationBinding>(IntegrationBinding).findOne({ where: { id } }); if (!x) throw new NotFoundException('INTEGRATION_BINDING_NOT_FOUND'); return x; }
}
