export const ROUTES = {
  login: '/login',
  cockpit: '/cockpit',
  overview: '/overview',
  applications: '/applications',
  workspace: '/workspace',
  versions: '/versions',
  validation: '/validation',
  publication: '/publication',
  history: '/history',
  specifications: '/specifications',
  environments: '/environments',
  contracts: '/contracts',
  config: '/config',
  snapshots: '/snapshots',
  platformContract: '/platform-contract',
  integrations: '/integrations',
  integrationCockpit: '/integrations/cockpit',
  connectors: '/integrations/connectors',
  apis: '/integrations/apis',
  webhooks: '/integrations/webhooks',
  credentials: '/integrations/credentials',
  sync: '/integrations/sync',
  diagnostics: '/integrations/diagnostics',
  integrationSpecs: '/integrations/specifications',
  deployment: '/deployment',
  deploymentCockpit: '/deployment/cockpit',
  releases: '/deployment/releases',
  pipelines: '/deployment/pipelines',
  promotions: '/deployment/promotion',
  rollback: '/deployment/rollback',
  deploymentDiagnostics: '/deployment/diagnostics',
  deploymentSpecs: '/deployment/specifications',
  iam: '/iam',
  iamUsers: '/iam/users',
  iamIdentities: '/iam/identities',
  iamTenants: '/iam/tenants',
  iamRoles: '/iam/roles',
  iamPolicies: '/iam/policies',
  iamSessions: '/iam/sessions',
  iamObservability: '/iam/observability',
  iamObservabilityLogs: '/iam/observability/logs',
  iamObservabilityAudit: '/iam/observability/audit',
  iamObservabilitySecurityEvents: '/iam/observability/security-events',
  iamObservabilityMonitoring: '/iam/observability/monitoring',
  iamObservabilityAlerts: '/iam/observability/alerts',
  iamAdmin: '/iam/admin',
  erp: '/erp',
  erpRegistry: '/erps',
  erpRegistryCreate: '/erps/create',
  erpDataRuntime: '/data-runtime',
  erpAutomation: '/automation',
  dataRuntime: '/data-runtime',
  automation: '/automation',
  notFound: '/not-found',
};

export const LEGACY_NAVIGATION_BRIDGE = {
  description:
    'RouteToTabSync synchronizes URL routes -> Redux activeTab/activeModuleId. ' +
    'Existing components read Redux state; React Router remains the navigation authority.',
  syncHook: 'RouteToTabSync.jsx',
};
