import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { createHash } from 'crypto';
import { DataSource, ObjectLiteral } from 'typeorm';
import { ApplicationVersion } from '../entities/application-version.entity';
import { Capability } from '../entities/capability.entity';
import { Feature } from '../entities/feature.entity';
import { Menu } from '../entities/menu.entity';
import { MenuItem } from '../entities/menu-item.entity';
import { MenuItemCapabilityRequirement } from '../entities/menu-item-capability-requirement.entity';
import { MenuItemFeatureRequirement } from '../entities/menu-item-feature-requirement.entity';
import { VersionCapability } from '../entities/version-capability.entity';
import { VersionFeature } from '../entities/version-feature.entity';
import { VersionMenu } from '../entities/version-menu.entity';
import { VersionMenuItem } from '../entities/version-menu-item.entity';
import { ApplicationVersionStatus, MenuItemState, MenuStatus, NavigationTargetType, RequirementMode, VersionFeatureState } from '../../../common/enums';

@Injectable()
export class MenuService {
  constructor(@InjectDataSource() private readonly db: DataSource) {}
  private repo = <T extends ObjectLiteral>(target: any) => this.db.getRepository<T>(target);
  async createMenu(data: Partial<Menu>) { const code = String(data.code ?? '').trim().toUpperCase(); if (!code || !data.name || !data.location) throw new BadRequestException('MENU_CODE_NAME_LOCATION_REQUIRED'); const repo = this.repo<Menu>(Menu); if (await repo.findOne({ where: { code } })) throw new ConflictException('MENU_CODE_EXISTS'); return repo.save(repo.create({ ...data, code, status: data.status ?? MenuStatus.DRAFT })); }
  async listMenus(q: any = {}) { const repo = this.repo<Menu>(Menu), qb = repo.createQueryBuilder('menu'); if (q.search) qb.where('(LOWER(menu.code) LIKE LOWER(:q) OR LOWER(menu.name) LIKE LOWER(:q))', { q: `%${q.search}%` }); if (q.location) qb.andWhere('menu.location=:location', { location: q.location }); if (q.status) qb.andWhere('menu.status=:status', { status: q.status }); const limit = Math.min(Number(q.limit) || 25, 100), page = Number(q.page) || 1; const [items, total] = await qb.orderBy('menu.code').skip((page - 1) * limit).take(limit).getManyAndCount(); return { items, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }; }
  async getMenu(id: string) { return this.menu(id); }
  async updateMenu(id: string, data: Partial<Menu> & { expectedVersion?: number }) { const item = await this.menu(id); this.lock(item.version, data.expectedVersion); const { id: _id, code: _code, expectedVersion: _e, createdBy: _c, ...changes } = data; return this.repo<Menu>(Menu).save({ ...item, ...changes, version: item.version + 1 }); }
  archiveMenu(id: string, expectedVersion?: number) { return this.updateMenu(id, { status: MenuStatus.ARCHIVED, archivedAt: new Date(), expectedVersion }); }
  async createItem(menuId: string, data: Partial<MenuItem>) { await this.menu(menuId); if (!data.code || !data.label) throw new BadRequestException('MENU_ITEM_CODE_AND_LABEL_REQUIRED'); const repo = this.repo<MenuItem>(MenuItem); if (await repo.findOne({ where: { menuId, code: data.code } })) throw new ConflictException('MENU_ITEM_CODE_EXISTS'); await this.validItem(menuId, undefined, data.parentId, data.targetType, data.route, data.externalUrl, data.actionKey); return repo.save(repo.create({ ...data, menuId })); }
  async listItems(menuId: string) { await this.menu(menuId); return this.repo<MenuItem>(MenuItem).find({ where: { menuId }, order: { sortOrder: 'ASC' } }); }
  async updateItem(id: string, data: Partial<MenuItem> & { expectedVersion?: number }) { const item = await this.item(id); this.lock(item.version, data.expectedVersion); await this.validItem(item.menuId, id, data.parentId === undefined ? item.parentId : data.parentId, data.targetType ?? item.targetType, data.route ?? item.route, data.externalUrl ?? item.externalUrl, data.actionKey ?? item.actionKey); const { id: _id, menuId: _m, expectedVersion: _e, createdBy: _c, ...changes } = data; return this.repo<MenuItem>(MenuItem).save({ ...item, ...changes, version: item.version + 1 }); }
  moveItem(id: string, parentId: string | null, sortOrder?: number, expectedVersion?: number) { return this.updateItem(id, { parentId, sortOrder, expectedVersion }); }
  async reorder(menuId: string, changes: Array<{ id: string; parentId?: string | null; sortOrder: number }>) { await this.db.transaction(async em => { for (const change of changes) { const item = await em.getRepository(MenuItem).findOne({ where: { id: change.id, menuId } }); if (!item) throw new NotFoundException('MENU_ITEM_NOT_FOUND'); await this.validItem(menuId, item.id, change.parentId === undefined ? item.parentId : change.parentId, item.targetType, item.route, item.externalUrl, item.actionKey); await em.getRepository(MenuItem).save({ ...item, parentId: change.parentId === undefined ? item.parentId : change.parentId, sortOrder: change.sortOrder, version: item.version + 1 }); } }); return this.listItems(menuId); }
  async addFeatureRequirement(menuItemId: string, featureId: string) { await this.item(menuItemId); if (!await this.repo<Feature>(Feature).findOne({ where: { id: featureId } })) throw new NotFoundException('FEATURE_NOT_FOUND'); const r = this.repo<MenuItemFeatureRequirement>(MenuItemFeatureRequirement); if (await r.findOne({ where: { menuItemId, featureId } })) throw new ConflictException('FEATURE_REQUIREMENT_EXISTS'); return r.save(r.create({ menuItemId, featureId })); }
  async addCapabilityRequirement(menuItemId: string, capabilityId: string) { await this.item(menuItemId); if (!await this.repo<Capability>(Capability).findOne({ where: { id: capabilityId } })) throw new NotFoundException('CAPABILITY_NOT_FOUND'); const r = this.repo<MenuItemCapabilityRequirement>(MenuItemCapabilityRequirement); if (await r.findOne({ where: { menuItemId, capabilityId } })) throw new ConflictException('CAPABILITY_REQUIREMENT_EXISTS'); return r.save(r.create({ menuItemId, capabilityId })); }
  async requirements(menuItemId: string) { return { features: await this.repo<MenuItemFeatureRequirement>(MenuItemFeatureRequirement).find({ where: { menuItemId } }), capabilities: await this.repo<MenuItemCapabilityRequirement>(MenuItemCapabilityRequirement).find({ where: { menuItemId } }) }; }
  async enableMenu(applicationVersionId: string, menuId: string, enabled: boolean) { await this.editable(applicationVersionId); await this.menu(menuId); const r = this.repo<VersionMenu>(VersionMenu), old = await r.findOne({ where: { applicationVersionId, menuId } }); return r.save(old ? { ...old, enabled, version: old.version + 1 } : r.create({ applicationVersionId, menuId, enabled })); }
  async resolve(versionId: string, location?: string) { const vm = await this.repo<VersionMenu>(VersionMenu).find({ where: { applicationVersionId: versionId, enabled: true } }); const menus = (await Promise.all(vm.map(x => this.menu(x.menuId)))).filter(x => !location || x.location === location); return { versionId, menus: await Promise.all(menus.map(menu => this.resolveMenu(versionId, menu))) }; }
  async validate(versionId: string) { const nav: any = await this.resolve(versionId); const issues = nav.menus.flatMap((m: any) => m.issues); return { valid: !issues.some((x: any) => x.severity === 'ERROR'), errors: issues.filter((x: any) => x.severity === 'ERROR').length, warnings: issues.filter((x: any) => x.severity === 'WARNING').length, issues }; }
  async snapshot(versionId: string) { const navigation = await this.resolve(versionId); return { ...navigation, snapshotHash: createHash('sha256').update(JSON.stringify(navigation)).digest('hex') }; }
  private async resolveMenu(versionId: string, menu: Menu) { const [items, overrides, features, capabilities] = await Promise.all([this.listItems(menu.id), this.repo<VersionMenuItem>(VersionMenuItem).find({ where: { applicationVersionId: versionId } }), this.repo<VersionFeature>(VersionFeature).find({ where: { applicationVersionId: versionId } }), this.repo<VersionCapability>(VersionCapability).find({ where: { applicationVersionId: versionId } })]); const over = new Map(overrides.map(x => [x.menuItemId, x])), activeF = new Set(features.filter(x => x.state !== VersionFeatureState.DISABLED).map(x => x.featureId)), activeC = new Set(capabilities.filter(x => x.enabled).map(x => x.capabilityId)), visible = new Set<string>(), issues: any[] = []; for (const item of items) { const req = await this.requirements(item.id), f = req.features.every(x => activeF.has(x.featureId)), checks = req.capabilities.map(x => activeC.has(x.capabilityId)), c = item.requirementMode === RequirementMode.ANY ? (!checks.length || checks.some(Boolean)) : checks.every(Boolean); if (!f || !c) issues.push({ severity: 'ERROR', code: f ? 'MENU_CAPABILITY_NOT_AVAILABLE' : 'MENU_FEATURE_NOT_AVAILABLE', menuItem: item.code }); if ((over.get(item.id)?.state ?? item.state) !== MenuItemState.HIDDEN && f && c) visible.add(item.id); } const tree = (parentId: string | null = null): any[] => items.filter(x => (x.parentId ?? null) === parentId).sort((a,b) => (over.get(a.id)?.sortOrder ?? a.sortOrder) - (over.get(b.id)?.sortOrder ?? b.sortOrder)).flatMap(x => { const children = tree(x.id); if (!visible.has(x.id) || (x.hideWhenEmpty && !children.length && x.targetType === NavigationTargetType.NONE)) return []; return [{ ...x, state: over.get(x.id)?.state ?? x.state, children }]; }); return { code: menu.code, location: menu.location, items: tree(), issues }; }
  private async validItem(menuId: string, id: string | undefined, parentId: string | null | undefined, target?: NavigationTargetType, route?: string, externalUrl?: string, actionKey?: string) { if (parentId) { if (parentId === id) throw new BadRequestException('MENU_ITEM_SELF_PARENT'); let parent = await this.repo<MenuItem>(MenuItem).findOne({ where: { id: parentId, menuId } }); if (!parent) throw new BadRequestException('ORPHAN_MENU_ITEM'); let depth = 1; while (parent.parentId) { if (parent.parentId === id) throw new BadRequestException('MENU_HIERARCHY_CYCLE'); parent = await this.repo<MenuItem>(MenuItem).findOne({ where: { id: parent.parentId, menuId } }); if (!parent) throw new BadRequestException('ORPHAN_MENU_ITEM'); if (++depth >= 3) throw new BadRequestException('MAX_DEPTH_EXCEEDED'); } } if (target === NavigationTargetType.ROUTE && (!route || !route.startsWith('/'))) throw new BadRequestException('ROUTE_REQUIRED'); if (target === NavigationTargetType.EXTERNAL_URL) try { const url = new URL(externalUrl ?? ''); if (!['http:', 'https:'].includes(url.protocol)) throw Error(); } catch { throw new BadRequestException('EXTERNAL_URL_INVALID'); } if (target === NavigationTargetType.ACTION && !actionKey) throw new BadRequestException('ACTION_REQUIRED'); }
  private async menu(id: string) { const x = await this.repo<Menu>(Menu).findOne({ where: { id } }); if (!x) throw new NotFoundException('MENU_NOT_FOUND'); return x; } private async item(id: string) { const x = await this.repo<MenuItem>(MenuItem).findOne({ where: { id } }); if (!x) throw new NotFoundException('MENU_ITEM_NOT_FOUND'); return x; } private async editable(id: string) { const x = await this.repo<ApplicationVersion>(ApplicationVersion).findOne({ where: { id } }); if (!x) throw new NotFoundException('VERSION_NOT_FOUND'); if ([ApplicationVersionStatus.PUBLISHED, ApplicationVersionStatus.ARCHIVED, ApplicationVersionStatus.SUPERSEDED].includes(x.status)) throw new ConflictException('VERSION_NOT_EDITABLE'); return x; } private lock(current: number, expected?: number) { if (expected !== undefined && expected !== current) throw new ConflictException('VERSION_CONFLICT'); }
}
