const express = require('express');
const authRoutes = require('./auth.routes');
const sessionRoutes = require('./session.routes');
const identityRoutes = require('./identity.routes');
const contextRoutes = require('./context.routes');
const mfaRoutes = require('./mfa.routes');
const securityRoutes = require('./security.routes');
const planRoutes = require('./plan.routes');
const subscriptionRoutes = require('./subscription.routes');
const invoiceRoutes = require('./invoice.routes');
const paymentRoutes = require('./payment.routes');
const webhookRoutes = require('./webhook.routes');
const entitlementRoutes = require('./entitlement.routes');
const accessDecisionRoutes = require('./accessDecision.routes');
const featureRoutes = require('./feature.routes');
const router = express.Router();

router.use('/auth', authRoutes);
router.use('/context', contextRoutes);
router.use('/', sessionRoutes);
router.use('/', identityRoutes);
router.use('/mfa', mfaRoutes);
router.use('/security', securityRoutes);
router.use('/billing/plans', planRoutes);
router.use('/billing/subscriptions', subscriptionRoutes);
router.use('/billing/invoices', invoiceRoutes);
router.use('/billing/payments', paymentRoutes);
router.use('/billing/webhooks', webhookRoutes);
router.use('/billing/entitlements', entitlementRoutes);
router.use('/billing/access', accessDecisionRoutes);
router.use('/billing/features', featureRoutes);
module.exports = router;
