const express = require('express');
const authRoutes = require('./auth.routes');
const sessionRoutes = require('./session.routes');
const identityRoutes = require('./identity.routes');
const contextRoutes = require('./context.routes');
const mfaRoutes = require('./mfa.routes');
const securityRoutes = require('./security.routes');
const planRoutes = require('./plan.routes');
const subscriptionRoutes = require('./subscription.routes');
const invoiceRoutes = require('./invoice.routes');
const paymentRoutes = require('./payment.routes');
const webhookRoutes = require('./webhook.routes');
const entitlementRoutes = require('./entitlement.routes');
const accessDecisionRoutes = require('./accessDecision.routes');
const featureRoutes = require('./feature.routes');
const adminUserRoutes = require('./adminUser.routes');
const observabilityRoutes = require('./observability.routes');
const logsManagerRoutes = require('./logsManager.routes');
const auditManagerRoutes = require('./auditManager.routes');
const alertManagerRoutes = require('./alertManager.routes');
const adminTenantRoutes = require('./adminTenant.routes');
const adminGovernanceRoutes = require('./adminGovernance.routes');
const adminDelegationRoutes = require('./adminDelegation.routes');
const adminSecurityRoutes = require('./adminSecurity.routes');
const adminAuditRoutes = require('./adminAudit.routes');
const adminMonitoringDiagnosticsRoutes = require('./adminMonitoringDiagnostics.routes');
const adminActionsRoutes = require('./adminActions.routes');
const router = express.Router();

router.use('/auth', authRoutes);
router.use('/context', contextRoutes);
router.use('/observability', observabilityRoutes);
router.use('/logs', logsManagerRoutes);
router.use('/audit', auditManagerRoutes);
router.use('/alerts', alertManagerRoutes);
router.use('/', sessionRoutes);
router.use('/', identityRoutes);
router.use('/mfa', mfaRoutes);
router.use('/security', securityRoutes);
router.use('/billing/plans', planRoutes);
router.use('/billing/subscriptions', subscriptionRoutes);
router.use('/billing/invoices', invoiceRoutes);
router.use('/billing/payments', paymentRoutes);
router.use('/billing/webhooks', webhookRoutes);
router.use('/billing/entitlements', entitlementRoutes);
router.use('/billing/access', accessDecisionRoutes);
router.use('/billing/features', featureRoutes);
router.use('/admin/users', adminUserRoutes);
router.use('/admin/tenants', adminTenantRoutes);
router.use('/admin/governance', adminGovernanceRoutes);
router.use('/admin/delegations', adminDelegationRoutes);
router.use('/admin/security', adminSecurityRoutes);
router.use('/admin/audit', adminAuditRoutes);
router.use('/admin/monitoring', adminMonitoringDiagnosticsRoutes);
router.use('/admin/actions', adminActionsRoutes);
module.exports = router;
