const express = require('express');
const authRoutes = require('./auth.routes');
const sessionRoutes = require('./session.routes');
const identityRoutes = require('./identity.routes');
const contextRoutes = require('./context.routes');
const mfaRoutes = require('./mfa.routes');
const securityRoutes = require('./security.routes');
const planRoutes = require('./plan.routes');
const subscriptionRoutes = require('./subscription.routes');
const invoiceRoutes = require('./invoice.routes');
const paymentRoutes = require('./payment.routes');
const router = express.Router();

router.use('/auth', authRoutes);
router.use('/context', contextRoutes);
router.use('/', sessionRoutes);
router.use('/', identityRoutes);
router.use('/mfa', mfaRoutes);
router.use('/security', securityRoutes);
router.use('/billing/plans', planRoutes);
router.use('/billing/subscriptions', subscriptionRoutes);
router.use('/billing/invoices', invoiceRoutes);
router.use('/billing/payments', paymentRoutes);
module.exports = router;
