import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import { createHash } from 'crypto';
import { DataSource, ObjectLiteral } from 'typeorm';
import { ApplicationVersion } from '../entities/application-version.entity';
import { ConfigurationDefinition } from '../entities/configuration-definition.entity';
import { ConfigurationValue } from '../entities/configuration-value.entity';
import { MetadataDefinition } from '../entities/metadata-definition.entity';
import { MetadataValue } from '../entities/metadata-value.entity';
import { ApplicationVersionStatus, ConfigurationDataType, ConfigurationScope } from '../../../common/enums';

@Injectable()
export class ConfigurationService {
  constructor(@InjectDataSource() private readonly db: DataSource) {}
  private repo = <T extends ObjectLiteral>(t: any) => this.db.getRepository<T>(t);
  async createDefinition(data: Partial<ConfigurationDefinition>) { const code = String(data.code ?? '').trim().toLowerCase(); if (!/^[a-z][a-z0-9-]*(\.[a-z][a-z0-9-]*)+$/.test(code)) throw new BadRequestException('CONFIGURATION_CODE_INVALID'); if (!data.name || !data.dataType || !data.scope) throw new BadRequestException('CONFIGURATION_DEFINITION_REQUIRED_FIELDS'); const r = this.repo<ConfigurationDefinition>(ConfigurationDefinition); if (await r.findOne({ where: { code } })) throw new ConflictException('CONFIGURATION_CODE_EXISTS'); this.validateValue({ ...data, code } as ConfigurationDefinition, data.defaultValue, true); return r.save(r.create({ ...data, code })); }
  async listDefinitions(query: any = {}) { const qb = this.repo<ConfigurationDefinition>(ConfigurationDefinition).createQueryBuilder('definition'); if (query.search) qb.where('(LOWER(definition.code) LIKE LOWER(:q) OR LOWER(definition.name) LIKE LOWER(:q))', { q: `%${query.search}%` }); if (query.scope) qb.andWhere('definition.scope=:scope', { scope: query.scope }); return qb.orderBy('definition.sortOrder').addOrderBy('definition.code').getMany(); }
  async updateDefinition(id: string, data: Partial<ConfigurationDefinition> & { expectedVersion?: number }) { const d = await this.definition(id); if (data.expectedVersion !== undefined && d.version !== data.expectedVersion) throw new ConflictException('VERSION_CONFLICT'); const { id: _id, code: _code, expectedVersion: _e, ...changes } = data; return this.repo<ConfigurationDefinition>(ConfigurationDefinition).save({ ...d, ...changes, version: d.version + 1 }); }
  async setValue(definitionCode: string, scope: { applicationId?: string; applicationVersionId?: string; environment?: string; tenantId?: string }, value: unknown, createdBy?: string) { const d = await this.definitionByCode(definitionCode); this.assertScope(d.scope, scope); if (scope.applicationVersionId) await this.editable(scope.applicationVersionId); this.validateValue(d, value); const r = this.repo<ConfigurationValue>(ConfigurationValue); const old = await r.findOne({ where: { definitionId: d.id, applicationId: scope.applicationId ?? null as any, applicationVersionId: scope.applicationVersionId ?? null as any, environment: scope.environment ?? null as any } }); const data = { ...scope, definitionId: d.id, value: d.secret ? undefined : value, encryptedValue: d.secret ? this.protect(value) : undefined, source: d.scope, createdBy }; return r.save(old ? { ...old, ...data, version: old.version + 1 } : r.create(data)); }
  async removeOverride(versionId: string, code: string) { await this.editable(versionId); const d = await this.definitionByCode(code); const r = this.repo<ConfigurationValue>(ConfigurationValue); const item = await r.findOne({ where: { definitionId: d.id, applicationVersionId: versionId } }); if (!item) throw new NotFoundException('CONFIGURATION_OVERRIDE_NOT_FOUND'); await r.remove(item); }
  async resolve(versionId: string, environment?: string, codes?: string[]) { const version = await this.version(versionId); const definitions = await this.repo<ConfigurationDefinition>(ConfigurationDefinition).find(); const filtered = codes?.length ? definitions.filter(x => codes.includes(x.code)) : definitions; const values = await this.repo<ConfigurationValue>(ConfigurationValue).find(); return Promise.all(filtered.map(d => this.resolveOne(d, version.applicationId, versionId, environment, values))); }
  async explain(versionId: string, code: string, environment?: string) { const version = await this.version(versionId), d = await this.definitionByCode(code), values = await this.repo<ConfigurationValue>(ConfigurationValue).find(); return this.resolveOne(d, version.applicationId, versionId, environment, values, true); }
  async validate(versionId: string) { const resolved = await this.resolve(versionId), issues: any[] = []; for (const x of resolved) if (x.value === undefined && x.required) issues.push({ severity: 'ERROR', code: 'CONFIGURATION_REQUIRED_MISSING', target: x.code }); return { valid: !issues.length, errors: issues.length, warnings: 0, issues }; }
  async diff(source: string, target: string) { const [a, b] = await Promise.all([this.resolve(source), this.resolve(target)]); const left = new Map(a.map(x => [x.code, x.value])); return b.filter(x => JSON.stringify(left.get(x.code)) !== JSON.stringify(x.value)).map(x => ({ code: x.code, source: left.get(x.code), target: x.value })); }
  async snapshot(versionId: string) { const config = await this.resolve(versionId); const publicConfig = config.map(x => ({ code: x.code, value: x.secret ? '***' : x.value, source: x.source })).sort((a,b) => a.code.localeCompare(b.code)); return { applicationVersionId: versionId, configuration: publicConfig, snapshotHash: createHash('sha256').update(JSON.stringify(publicConfig)).digest('hex') }; }
  async createMetadataDefinition(data: Partial<MetadataDefinition>) { if (!data.code || !data.targetType || !data.name || !data.dataType) throw new BadRequestException('METADATA_DEFINITION_REQUIRED_FIELDS'); const r = this.repo<MetadataDefinition>(MetadataDefinition); if (await r.findOne({ where: { targetType: data.targetType, code: data.code } })) throw new ConflictException('METADATA_CODE_EXISTS'); return r.save(r.create(data)); }
  async listMetadataDefinitions() { return this.repo<MetadataDefinition>(MetadataDefinition).find({ order: { targetType: 'ASC', code: 'ASC' } }); }
  async setMetadata(resourceType: string, resourceId: string, code: string, value: unknown) { const d = await this.repo<MetadataDefinition>(MetadataDefinition).findOne({ where: { targetType: resourceType, code } }); if (!d) throw new NotFoundException('METADATA_DEFINITION_NOT_FOUND'); this.validateMetadata(d, value); const r = this.repo<MetadataValue>(MetadataValue), old = await r.findOne({ where: { definitionId: d.id, resourceType, resourceId } }); return r.save(old ? { ...old, value } : r.create({ definitionId: d.id, resourceType, resourceId, value })); }
  async resourceMetadata(resourceType: string, resourceId: string) { return this.repo<MetadataValue>(MetadataValue).find({ where: { resourceType, resourceId } }); }
  private async resolveOne(d: ConfigurationDefinition, applicationId: string, versionId: string, environment: string | undefined, values: ConfigurationValue[], explain = false): Promise<any> { const candidates = values.filter(v => v.definitionId === d.id); const selected = candidates.find(v => v.applicationVersionId === versionId && (!environment || v.environment === environment)) ?? candidates.find(v => v.applicationVersionId === versionId) ?? candidates.find(v => v.applicationId === applicationId && (!environment || v.environment === environment)) ?? candidates.find(v => v.applicationId === applicationId) ?? candidates.find(v => !v.applicationId && !v.applicationVersionId); const value = selected ? (d.secret ? undefined : selected.value) : d.defaultValue; return { code: d.code, value, required: d.required, secret: d.secret, source: selected?.source ?? 'DEFAULT', ...(explain ? { defaultValue: d.secret ? undefined : d.defaultValue, overridden: !!selected } : {}) }; }
  private validateValue(d: ConfigurationDefinition, value: unknown, allowUndefined = false) { if (value === undefined && allowUndefined) return; if ((value === null || value === undefined) && !d.nullable && d.required) throw new BadRequestException('CONFIGURATION_VALUE_REQUIRED'); if (value === null || value === undefined) return; const t = d.dataType; if (t === ConfigurationDataType.BOOLEAN && typeof value !== 'boolean') throw new BadRequestException('CONFIGURATION_TYPE_INVALID'); if (t === ConfigurationDataType.INTEGER && (!Number.isInteger(value))) throw new BadRequestException('CONFIGURATION_TYPE_INVALID'); if (t === ConfigurationDataType.DECIMAL && (typeof value !== 'number')) throw new BadRequestException('CONFIGURATION_TYPE_INVALID'); if ([ConfigurationDataType.STRING, ConfigurationDataType.TEXT, ConfigurationDataType.URL, ConfigurationDataType.EMAIL, ConfigurationDataType.SECRET].includes(t) && typeof value !== 'string') throw new BadRequestException('CONFIGURATION_TYPE_INVALID'); if (t === ConfigurationDataType.URL) try { new URL(value as string); } catch { throw new BadRequestException('CONFIGURATION_URL_INVALID'); } if (d.allowedValues?.length && !d.allowedValues.includes(value)) throw new BadRequestException('CONFIGURATION_VALUE_NOT_ALLOWED'); }
  private validateMetadata(d: MetadataDefinition, value: unknown) { this.validateValue({ ...d, nullable: !d.required, required: d.required, scope: ConfigurationScope.APPLICATION } as unknown as ConfigurationDefinition, value); }
  private assertScope(scope: ConfigurationScope, value: any) { if (scope === ConfigurationScope.APPLICATION && !value.applicationId) throw new BadRequestException('APPLICATION_SCOPE_REQUIRED'); if (scope === ConfigurationScope.APPLICATION_VERSION && !value.applicationVersionId) throw new BadRequestException('APPLICATION_VERSION_SCOPE_REQUIRED'); }
  private protect(value: unknown) { return Buffer.from(JSON.stringify(value)).toString('base64'); }
  private async definition(id: string) { const x = await this.repo<ConfigurationDefinition>(ConfigurationDefinition).findOne({ where: { id } }); if (!x) throw new NotFoundException('CONFIGURATION_DEFINITION_NOT_FOUND'); return x; } private async definitionByCode(code: string) { const x = await this.repo<ConfigurationDefinition>(ConfigurationDefinition).findOne({ where: { code } }); if (!x) throw new NotFoundException('CONFIGURATION_DEFINITION_NOT_FOUND'); return x; } private async version(id: string) { const x = await this.repo<ApplicationVersion>(ApplicationVersion).findOne({ where: { id } }); if (!x) throw new NotFoundException('VERSION_NOT_FOUND'); return x; } private async editable(id: string) { const x = await this.version(id); if ([ApplicationVersionStatus.PUBLISHED, ApplicationVersionStatus.ARCHIVED, ApplicationVersionStatus.SUPERSEDED].includes(x.status)) throw new ConflictException('VERSION_NOT_EDITABLE'); return x; }
}
