// BM-CDC-00, BM-CDC-01 & BM-CDC-02 Domain Constants & Types

export const APPLICATION_STATUS = {
  DRAFT: 'DRAFT',
  CONFIGURING: 'CONFIGURING',
  READY: 'READY',
  TESTING: 'TESTING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  ARCHIVED: 'ARCHIVED',
  ERROR: 'ERROR',
};

export const VERSION_STATUS = {
  DRAFT: 'DRAFT',
  CONFIGURING: 'CONFIGURING',
  VALIDATING: 'VALIDATING',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED',
  SUPERSEDED: 'SUPERSEDED',
  DEPRECATED: 'DEPRECATED',
  ARCHIVED: 'ARCHIVED',
  ERROR: 'ERROR',
};

export const ENVIRONMENTS = {
  DEVELOPMENT: 'DEVELOPMENT',
  TEST: 'TEST',
  STAGING: 'STAGING',
  PRODUCTION: 'PRODUCTION',
};

export const SOURCE_TYPES = {
  SYSTEM: 'SYSTEM',
  TEMPLATE: 'TEMPLATE',
  CUSTOM: 'CUSTOM',
  CLONED: 'CLONED',
  IMPORTED: 'IMPORTED',
  GENERATED: 'GENERATED',
};

export const VALIDATION_SEVERITY = {
  ERROR: 'ERROR',     // Blocks publication & ready transitions
  WARNING: 'WARNING', // Permitted with alert badge
  INFO: 'INFO',       // Informational notice
};

export const ERROR_CODES = {
  // BM-CDC-00 Common Error Codes
  BUSINESS_VALIDATION_FAILED: 'BUSINESS_VALIDATION_FAILED',
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  BUSINESS_PERMISSION_DENIED: 'BUSINESS_PERMISSION_DENIED',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_CODE_EXISTS: 'APPLICATION_CODE_EXISTS',
  APPLICATION_NAME_REQUIRED: 'APPLICATION_NAME_REQUIRED',
  APPLICATION_CODE_REQUIRED: 'APPLICATION_CODE_REQUIRED',
  APPLICATION_CODE_INVALID: 'APPLICATION_CODE_INVALID',
  APPLICATION_ARCHIVED: 'APPLICATION_ARCHIVED',
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',
  VERSION_NOT_EDITABLE: 'VERSION_NOT_EDITABLE',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  VERSION_INVALID_NUMBER: 'VERSION_INVALID_NUMBER',
  VERSION_ALREADY_EXISTS: 'VERSION_ALREADY_EXISTS',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  INVALID_STATE: 'INVALID_STATE',
  DEPENDENCY_MISSING: 'DEPENDENCY_MISSING',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  SNAPSHOT_FAILED: 'SNAPSHOT_FAILED',
  CONTEXT_INVALID: 'CONTEXT_INVALID',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ROLLBACK_NOT_ALLOWED: 'ROLLBACK_NOT_ALLOWED',
  PUBLICATION_VALIDATION_FAILED: 'PUBLICATION_VALIDATION_FAILED',
};

export const ALLOWED_APPLICATION_TRANSITIONS = {
  DRAFT: ['CONFIGURING', 'ARCHIVED'],
  CONFIGURING: ['READY', 'DRAFT', 'ARCHIVED'],
  READY: ['TESTING', 'CONFIGURING', 'ARCHIVED'],
  TESTING: ['ACTIVE', 'READY', 'CONFIGURING', 'ARCHIVED'],
  ACTIVE: ['SUSPENDED', 'ARCHIVED'],
  SUSPENDED: ['ACTIVE', 'ARCHIVED'],
  ARCHIVED: [], // Terminal
  ERROR: ['DRAFT', 'CONFIGURING'],
};

export const ALLOWED_VERSION_TRANSITIONS = {
  DRAFT: ['CONFIGURING', 'VALIDATING', 'ARCHIVED'],
  CONFIGURING: ['VALIDATING', 'DRAFT', 'ARCHIVED'],
  VALIDATING: ['READY', 'CONFIGURING'],
  READY: ['PUBLISHED', 'CONFIGURING', 'ARCHIVED'],
  PUBLISHED: ['SUPERSEDED', 'DEPRECATED', 'ARCHIVED'],
  SUPERSEDED: ['DEPRECATED', 'ARCHIVED'],
  DEPRECATED: ['ARCHIVED'],
  ARCHIVED: [],
  ERROR: ['DRAFT', 'CONFIGURING'],
};

export const IMMUTABLE_VERSION_STATUSES = [
  'PUBLISHED',
  'SUPERSEDED',
  'DEPRECATED',
  'ARCHIVED',
];

export const ROLES = {
  ADMIN: 'ADMIN',
  BUILDER: 'BUILDER',
  VIEWER: 'VIEWER',
};

export const ROLE_PERMISSIONS = {
  ADMIN: [
    'business.application.read',
    'business.application.create',
    'business.application.update',
    'business.application.clone',
    'business.application.archive',
    'business.application.restore',
    'business.application.activity.read',
    'business.version.read',
    'business.version.create',
    'business.version.update',
    'business.version.clone',
    'business.version.archive',
    'business.version.transition',
    'business.version.validate',
    'business.version.compare',
    'business.version.snapshot',
    'business.version.publish',
    'business.version.rollback',
    'business.audit.read',
  ],
  BUILDER: [
    'business.application.read',
    'business.application.create',
    'business.application.update',
    'business.application.clone',
    'business.version.read',
    'business.version.create',
    'business.version.update',
    'business.version.clone',
    'business.version.validate',
    'business.version.compare',
    'business.version.snapshot',
    'business.version.publish',
    'business.audit.read',
  ],
  VIEWER: [
    'business.application.read',
    'business.version.read',
    'business.version.compare',
    'business.audit.read',
  ],
};

// ============================================================================
// PACK MANAGER DOMAIN (PM-CDC-00, PM-CDC-01, PM-CDC-02, PM-CDC-03..07)
// ============================================================================

export const PACK_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEPRECATED: 'DEPRECATED',
  ARCHIVED: 'ARCHIVED',
};

export const PACK_VERSION_STATUS = {
  DRAFT: 'DRAFT',
  CONFIGURING: 'CONFIGURING',
  VALIDATING: 'VALIDATING',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED',
  SUPERSEDED: 'SUPERSEDED',
  DEPRECATED: 'DEPRECATED',
  ARCHIVED: 'ARCHIVED',
  INVALID: 'INVALID',
  ERROR: 'ERROR',
};

export const PACK_VALIDATION_STATUS = {
  NOT_RUN: 'NOT_RUN',
  RUNNING: 'RUNNING',
  VALID: 'VALID',
  INVALID: 'INVALID',
  OUTDATED: 'OUTDATED',
  ERROR: 'ERROR',
};

export const PACK_MANIFEST_STATUS = {
  NOT_GENERATED: 'NOT_GENERATED',
  GENERATING: 'GENERATING',
  VALID: 'VALID',
  INVALID: 'INVALID',
  OUTDATED: 'OUTDATED',
  ERROR: 'ERROR',
};

export const PACK_SOURCE_TYPE = {
  SYSTEM: 'SYSTEM',
  TEMPLATE: 'TEMPLATE',
  CUSTOM: 'CUSTOM',
  CLONED: 'CLONED',
  IMPORTED: 'IMPORTED',
  GENERATED: 'GENERATED',
};

export const MODULE_TYPE = {
  BUSINESS: 'BUSINESS',
  SUPPORT: 'SUPPORT',
  CONFIGURATION: 'CONFIGURATION',
  REPORTING: 'REPORTING',
  INTEGRATION: 'INTEGRATION',
  SYSTEM: 'SYSTEM',
};

export const FEATURE_TYPE = {
  CORE: 'CORE',
  OPTIONAL: 'OPTIONAL',
  PREMIUM: 'PREMIUM',
  EXPERIMENTAL: 'EXPERIMENTAL',
  INTERNAL: 'INTERNAL',
  INTEGRATION: 'INTEGRATION',
};

export const CAPABILITY_TYPE = {
  DATA: 'DATA',
  ACTION: 'ACTION',
  UI: 'UI',
  WORKFLOW: 'WORKFLOW',
  INTEGRATION: 'INTEGRATION',
  SYSTEM: 'SYSTEM',
};

export const CAPABILITY_RELATION_TYPE = {
  PROVIDES: 'PROVIDES',
  REQUIRES: 'REQUIRES',
  USES: 'USES',
};

export const DEPENDENCY_TYPE = {
  REQUIRED: 'REQUIRED',
  OPTIONAL: 'OPTIONAL',
  CONFLICTS_WITH: 'CONFLICTS_WITH',
  RECOMMENDS: 'RECOMMENDS',
  IMPLIES: 'IMPLIES',
};

export const DEPENDENCY_RESOLUTION_STATUS = {
  NOT_RESOLVED: 'NOT_RESOLVED',
  RESOLVING: 'RESOLVING',
  RESOLVED: 'RESOLVED',
  MISSING: 'MISSING',
  INCOMPATIBLE: 'INCOMPATIBLE',
  CONFLICT: 'CONFLICT',
  CYCLE: 'CYCLE',
  ERROR: 'ERROR',
  OUTDATED: 'OUTDATED',
};

export const RULE_TYPE = {
  ACTIVATION: 'ACTIVATION',
  ELIGIBILITY: 'ELIGIBILITY',
  VISIBILITY: 'VISIBILITY',
  AVAILABILITY: 'AVAILABILITY',
  CONFIGURATION: 'CONFIGURATION',
  COMPATIBILITY: 'COMPATIBILITY',
};

export const RULE_EFFECT = {
  ALLOW: 'ALLOW',
  DENY: 'DENY',
  ENABLE: 'ENABLE',
  DISABLE: 'DISABLE',
  SHOW: 'SHOW',
  HIDE: 'HIDE',
  REQUIRE: 'REQUIRE',
  SET_VALUE: 'SET_VALUE',
};

export const PACK_ERROR_CODES = {
  PACK_NOT_FOUND: 'PACK_NOT_FOUND',
  PACK_CODE_ALREADY_EXISTS: 'PACK_CODE_ALREADY_EXISTS',
  PACK_CODE_INVALID: 'PACK_CODE_INVALID',
  PACK_ARCHIVED: 'PACK_ARCHIVED',
  PACK_VERSION_NOT_FOUND: 'PACK_VERSION_NOT_FOUND',
  PACK_VERSION_IMMUTABLE: 'PACK_VERSION_IMMUTABLE',
  PACK_VERSION_CONFLICT: 'PACK_VERSION_CONFLICT',
  PACK_VALIDATION_FAILED: 'PACK_VALIDATION_FAILED',
  PACK_VALIDATION_OUTDATED: 'PACK_VALIDATION_OUTDATED',
  PACK_DEPENDENCY_MISSING: 'PACK_DEPENDENCY_MISSING',
  PACK_DEPENDENCY_CONFLICT: 'PACK_DEPENDENCY_CONFLICT',
  PACK_DEPENDENCY_CYCLE: 'PACK_DEPENDENCY_CYCLE',
  PACK_MANIFEST_INVALID: 'PACK_MANIFEST_INVALID',
  PACK_CONTRACT_INCOMPATIBLE: 'PACK_CONTRACT_INCOMPATIBLE',
  PACK_PUBLICATION_DENIED: 'PACK_PUBLICATION_DENIED',
  PACK_CATEGORY_NOT_FOUND: 'PACK_CATEGORY_NOT_FOUND',
  PACK_OPERATION_FORBIDDEN: 'PACK_OPERATION_FORBIDDEN',
  PACK_ARCHIVE_BLOCKED: 'PACK_ARCHIVE_BLOCKED',
  PACK_RESTORE_BLOCKED: 'PACK_RESTORE_BLOCKED',
};

