/**
 * Pack Runtime — constantes et erreurs PR-CDC-00.
 */

export const PR = {
  API_PREFIX: 'api/runtime',
  EFFECTIVE_CONTRACT: 'techzone.effective-runtime-manifest',
  EFFECTIVE_CONTRACT_VERSION: '1.0',
  CACHE_TTL_SECONDS: 300,
} as const;

export const PrErrorCode = {
  RUNTIME_MANIFEST_NOT_FOUND: 'RUNTIME_MANIFEST_NOT_FOUND',
  RUNTIME_MANIFEST_INVALID: 'RUNTIME_MANIFEST_INVALID',
  RUNTIME_MANIFEST_HASH_INVALID: 'RUNTIME_MANIFEST_HASH_INVALID',
  RUNTIME_CONTRACT_UNSUPPORTED: 'RUNTIME_CONTRACT_UNSUPPORTED',
  RUNTIME_CONTEXT_INVALID: 'RUNTIME_CONTEXT_INVALID',
  RUNTIME_TENANT_MISMATCH: 'RUNTIME_TENANT_MISMATCH',
  RUNTIME_CAPABILITY_MISSING: 'RUNTIME_CAPABILITY_MISSING',
  RUNTIME_DEPENDENCY_MISSING: 'RUNTIME_DEPENDENCY_MISSING',
  RUNTIME_RESOLUTION_BLOCKED: 'RUNTIME_RESOLUTION_BLOCKED',
  RUNTIME_INTERNAL_ERROR: 'RUNTIME_INTERNAL_ERROR',
} as const;

export type PrErrorCodeValue = (typeof PrErrorCode)[keyof typeof PrErrorCode];
