const fs=require('fs'),path=require('path');const {chromium}=require('../logs/browser-tools/node_modules/playwright');
(async()=>{const result={mode:'LIVE_NO_MOCKS',timestamp:new Date().toISOString(),routes:[],responsive:[],console:[],network:[],errors:[]};const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))result.console.push({type:m.type(),message:m.text().slice(0,350)});});page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))result.network.push({path:new URL(r.url()).pathname,status:r.status()});});
try{await page.goto('http://localhost:3000/login');await page.locator('#identifier').waitFor();const a=JSON.parse(fs.readFileSync(path.join(process.env.LOCALAPPDATA,'TechzoneRecipe/test-login.json')));await page.locator('#identifier').fill(a.username);await page.locator('#password').fill(a.password);await page.locator('button[type=submit]').click();await page.waitForURL('**/dashboard',{timeout:20000});await page.locator('#main-sidebar').waitFor();result.authenticated=true;await page.waitForTimeout(700);
result.sidebarGroups=await page.locator('[data-navigation-group]').evaluateAll(es=>es.map(e=>e.dataset.navigationGroup));
for(const id of result.sidebarGroups){const link=page.locator(`[data-navigation-group="${id}"] > div > a`);if(!await link.count()){result.routes.push({group:id,status:'NOT_IMPLEMENTED',click:false});continue;}const before=result.errors.length;await link.click();await page.waitForTimeout(250);result.routes.push({group:id,url:new URL(page.url()).pathname,click:true,rendered:await page.locator('main').innerText().then(x=>x.trim().length>0),active:await page.locator(`[data-navigation-group="${id}"] > div`).getAttribute('class').then(x=>x.includes('bg-blue-600')),tenantBlocked:await page.getByTestId('tenant-required').count()>0,comingSoon:await page.getByTestId('coming-soon').count()>0,reactErrors:result.errors.length-before});}
for(const route of ['/business-manager','/business-manager/applications','/business-manager/versions','/business-manager/models','/business-manager/features','/business-manager/navigation','/business-manager/configuration','/business-manager/runtime','/business-manager/validation','/business/configuration','/ui/forms','/erp/mappings','/not-a-route']){await page.goto('http://localhost:3000'+route);if(route==='/business/configuration')await page.waitForURL('**/business-manager/configuration');await page.locator('#main-sidebar').waitFor();const initial=new URL(page.url()).pathname;await page.reload();await page.locator('#main-sidebar').waitFor();result.routes.push({route,url:initial,refreshUrl:new URL(page.url()).pathname,text:(await page.locator('main').innerText().catch(()=>'' )).slice(0,160)});}
await page.goto('http://localhost:3000/business-manager/configuration');await page.getByTestId('tenant-required').waitFor();await page.screenshot({path:'docs/business-manager/runtime/configuration-desktop.png',fullPage:true});
for(const [name,width,height]of [['desktop',1440,1000],['wide',1920,1080],['tablet',768,1024],['mobile',390,844]]){await page.setViewportSize({width,height});if(width<1024){await page.locator('#mobile-menu-toggle-btn').click();await page.waitForTimeout(150);result.responsive.push({name,open:await page.locator('#main-sidebar').boundingBox().then(b=>b.x===0),overlay:await page.getByTestId('sidebar-overlay').isVisible()});await page.screenshot({path:`docs/business-manager/runtime/sidebar-${name}.png`});await page.getByRole('button',{name:'Fermer le menu'}).click();}else{result.responsive.push({name,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});}await page.screenshot({path:`docs/business-manager/runtime/page-${name}.png`});}
await page.setViewportSize({width:1440,height:1000});await page.goto('http://localhost:3000/ui/forms');await page.getByTestId('coming-soon').waitFor();await page.screenshot({path:'docs/business-manager/runtime/coming-soon.png',fullPage:true});
for(const button of await page.locator('#main-sidebar button[aria-expanded="false"]').all())await button.click();
const allLinks = await page.locator('#main-sidebar a').evaluateAll(links => [...new Set(links.map(link => link.getAttribute('href')))]);
result.submenuLinks=[];
for (const href of allLinks) { await page.goto('http://localhost:3000'+href); await page.locator('#main-sidebar').waitFor(); result.submenuLinks.push({href,url:new URL(page.url()).pathname,rendered:await page.locator('main').innerText().then(t=>t.trim().length>0)}); }
await page.goto('http://localhost:3000/business-manager/models');await page.locator('#main-sidebar').waitFor();
await page.getByRole('navigation',{name:'Business Manager',exact:true}).getByRole('link',{name:'Configuration',exact:true}).click();await page.waitForURL('**/business-manager/configuration');await page.goBack();await page.waitForURL('**/business-manager/models');await page.goForward();await page.waitForURL('**/business-manager/configuration');result.backForward=true;
for(const route of ['/iam/users','/observability']) { await page.goto('http://localhost:3000'+route);await page.getByRole('heading',{name:'Accès interdit'}).waitFor();result.routes.push({route,status:'EXPECTED_PERMISSION_DENIAL',rendered:true}); }
const favicon=await page.request.get('http://localhost:3000/favicon.ico');result.favicon={status:favicon.status(),contentType:favicon.headers()['content-type']};
await page.setViewportSize({width:1440,height:1000});await page.goto('http://localhost:3000/dashboard');await page.locator('#sidebar-collapse-toggle').click();await page.waitForTimeout(350);result.collapsedWidth=await page.locator('#main-sidebar').boundingBox().then(b=>b.width);await page.locator('#sidebar-collapse-toggle').click();
// Remove access cookie only: browser must recover through the genuine refresh endpoint.
await context.clearCookies({name:'iam_access_token'});const start=result.network.length;await page.reload();await page.waitForTimeout(1300);result.sessionRecovery={url:new URL(page.url()).pathname,refreshCalls:result.network.slice(start).filter(r=>r.path.endsWith('/auth/refresh')).length};
// Remove both cookies: finite failure must settle at login.
await context.clearCookies();const invalidStart=result.network.length;await page.reload();await page.waitForURL('**/login',{timeout:15000});await page.waitForTimeout(1000);result.invalidRefresh={url:new URL(page.url()).pathname,requests:result.network.slice(invalidStart)};
}catch(e){result.failure={name:e.name,message:e.message.slice(0,600)};}finally{await browser.close();fs.writeFileSync('docs/business-manager/runtime/browser.json',JSON.stringify(result,null,2));console.log(JSON.stringify({auth:result.authenticated,groups:result.sidebarGroups,routes:result.routes.length,errors:result.errors,console:result.console.length,sessionRecovery:result.sessionRecovery,invalidRefresh:result.invalidRefresh,favicon:result.favicon,failure:result.failure},null,2));}})();
