import { createElement, useEffect, useState } from 'react';
import { Link, useLocation, useSearchParams } from 'react-router-dom';
import { Activity, CheckCircle2, AlertTriangle } from 'lucide-react';
import { api } from '../../services/apiClient.js';
import { useTenant } from '../../contexts/TenantProvider.jsx';
import { useAuth } from '../../auth/AuthProvider.jsx';
import { BmPage, BmPageHeader, BmBreadcrumb, BmContextBar, BmCard, BmKpiCard, BmButton, BmTable, BmStatusBadge, BmEmptyState, BmErrorState, BmLoading, BmSelect } from '../business-manager/bm/ui.jsx';
const get = path => api.get(path).then(r => r.data);
const titles = { overview:'Vue d’ensemble Runtime',context:'Contextes',manifest:'Manifest publié',resolver:'Résolution',effective:'Configuration effective',cache:'Cache',diagnostics:'Diagnostics' };
export default function RuntimePage() { const { activeTenant } = useTenant(); return <Workspace key={activeTenant?.id} tenant={activeTenant}/>; }
function Workspace({ tenant }) {
  const { pathname } = useLocation(), [query,setQuery] = useSearchParams(), { user } = useAuth();
  const section = pathname === '/runtime' ? 'overview' : pathname.split('/').pop();
  const [data,setData] = useState(null), [detail,setDetail] = useState(null), [error,setError] = useState(''), [busy,setBusy] = useState(false), [revision,setRevision] = useState(0);
  const key = `runtime-context:${tenant?.id}`;
  const [context,setContext] = useState(() => { let saved = {}, bm = {}; try { saved = JSON.parse(sessionStorage.getItem(key) || '{}'); bm = JSON.parse(sessionStorage.getItem('bm-context:'+tenant?.id) || '{}'); } catch {} return { ...saved,applicationId:query.get('applicationId') || saved.applicationId || bm.applicationId,businessVersionId:query.get('businessVersionId') || saved.businessVersionId || bm.versionId,packCode:query.get('pack') || saved.packCode || '',packVersion:query.get('packVersion') || saved.packVersion || '' }; });
  const [versions,setVersions] = useState([]);
  const [sourceManifest,setSourceManifest] = useState(null);
  const selected = query.get('resolution') ?? '';
  const allowed = p => user?.isAdmin || user?.permissions?.includes('*') || user?.permissions?.includes(p);
  const refresh = () => setRevision(r => r+1);
  useEffect(() => { let live = true; setError(''); setData(null); Promise.all([get('/runtime/dashboard'),get('/pack-manager/registry'),get('/business-manager/applications'),get('/business-manager/environments'),get('/runtime/cache/status'),get('/runtime/cache/entries'),get('/runtime/providers/health')]).then(([dashboard,packs,applications,environments,cache,entries,health]) => { if (live) setData({ dashboard,packs,applications,environments,cache,entries,health }); }).catch(e => { if (live) setError(e.normalized?.message || 'Runtime indisponible'); }); return () => { live = false; }; },[revision]);
  useEffect(() => { let live = true; setVersions([]); if (context.applicationId) get(`/business-manager/applications/${context.applicationId}/versions`).then(v => { if (live) setVersions(v); }).catch(e => { if (live) setError(e.normalized?.message || 'Versions indisponibles'); }); return () => { live = false; }; },[context.applicationId]);
  useEffect(() => { let live = true; setDetail(null); if (selected) Promise.all([get(`/runtime/resolutions/${selected}`),get(`/runtime/resolutions/${selected}/diagnostics`)]).then(([resolution,diagnostics]) => { if (live) setDetail({ resolution,diagnostics }); }).catch(e => { if (live) setError(e.normalized?.message || 'Résolution indisponible'); }); return () => { live = false; }; },[selected,revision]);
  useEffect(() => {
    let live = true; setSourceManifest(null);
    const source = detail?.resolution.effectiveManifest?.content?.source;
    if (section === 'manifest' && source) get('/runtime/manifests/'+encodeURIComponent(source.packCode)+'/'+encodeURIComponent(source.packVersion)).then(value => { if(live) setSourceManifest(value); }).catch(e => { if(live) setError(e.normalized?.message || 'Manifest indisponible'); });
    return () => { live = false; };
  },[section,detail]);
  const change = values => setContext(c => { const next = { ...c,...values }; sessionStorage.setItem(key,JSON.stringify(next)); return next; });
  async function run(path,body) { if (busy) return; setBusy(true); setError(''); try { const result = (await api.post('/runtime'+path,body)).data; if (result.resolutionId) setQuery({ resolution:result.resolutionId }); refresh(); } catch(e) { setError(e.normalized?.message || 'Opération refusée'); } finally { setBusy(false); } }
  const effective = detail?.resolution.effectiveManifest?.content;
  const app = data?.applications.find(a => a.id === context.applicationId);
  return <BmPage><BmBreadcrumb items={[{ label:'Runtime',to:'/runtime' },{ label:titles[section] }]}/><BmPageHeader title={titles[section] ?? 'Runtime'} subtitle="Résolution de packs publiés dans un contexte métier vérifié."/>
    {error && <BmErrorState message={error} onRetry={refresh}/>}
    {!data ? !error && <BmLoading/> : <>
      <BmContextBar items={[{ label:'Application',value:effective?.businessConfiguration?.application?.name ?? app?.name },{ label:'Pack',value:effective?.source?.packCode ?? context.packCode },{ label:'Version',value:effective?.source?.packVersion ?? context.packVersion },{ label:'Tenant',value:tenant?.name ?? tenant?.id },{ label:'Environnement',value:effective?.scope?.environment ?? context.environment }]}/>
      {['overview','context','resolver'].includes(section) && <BmCard title="Contexte de résolution" subtitle="L’identité, les permissions et la configuration sont déterminées par le serveur."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
        <BmSelect label="Application" value={context.applicationId ?? ''} onChange={v => change({ applicationId:v,businessVersionId:'' })} options={[{ value:'',label:'Application' },...data.applications.map(a => ({ value:a.id,label:a.name }))]}/>
        <BmSelect label="Version métier" value={context.businessVersionId ?? ''} onChange={v => change({ businessVersionId:v })} options={[{ value:'',label:'Version métier' },...versions.map(v => ({ value:v.id,label:v.version+' · '+v.status }))]}/>
        <BmSelect label="Pack publié" value={context.packCode+'@'+context.packVersion} onChange={v => { const p = data.packs.find(p => p.code+'@'+p.versionNumber === v); change({ packCode:p?.code ?? '',packVersion:p?.versionNumber ?? '' }); }} options={[{ value:'@',label:'Pack publié' },...data.packs.map(p => ({ value:p.code+'@'+p.versionNumber,label:p.name+' · '+p.versionNumber }))]}/>
        <BmSelect label="Environnement" value={context.environment ?? ''} onChange={v => change({ environment:v })} options={[{ value:'',label:'Environnement' },...data.environments.filter(e => e.status === 'ACTIVE').map(e => ({ value:e.code,label:e.name }))]}/>
      </div><div className="mt-4 flex flex-wrap gap-3">{allowed('runtime.resolve') && <BmButton disabled={busy || !context.applicationId || !context.businessVersionId || !context.environment || !context.packVersion} onClick={() => run('/resolve',context)}>{busy ? 'Résolution…' : 'Résoudre le pack'}</BmButton>}<Link className="text-sm text-blue-700 py-2" to="/packs/registry">Consulter les packs publiés</Link></div></BmCard>}
      {section === 'overview' && <><div className="grid gap-4 md:grid-cols-3">{[['total','Résolutions',Activity],['resolved','Résolues',CheckCircle2],['blocked','Bloquées',AlertTriangle]].map(([k,label,icon]) => <BmKpiCard key={k} label={label} value={data.dashboard.counters[k]} icon={createElement(icon,{ size:22 })}/>)}</div><BmCard title="Disponibilité des providers">{data.health.providers.map(p => <div key={p.code} className="flex justify-between text-sm"><span>{p.code}</span><BmStatusBadge value={p.state}/></div>)}</BmCard></>}
      {!['cache'].includes(section) && <><BmSelect label="Résolution enregistrée" value={selected} onChange={v => setQuery({ resolution:v })} options={[{ value:'',label:'Choisir une résolution' },...data.dashboard.recent.map(r => ({ value:r.id,label:new Date(r.startedAt).toLocaleString()+' · '+r.status }))]}/>
        {selected && !detail ? !error && <BmLoading/> : detail ? <><BmCard title="Parcours de résolution"><div className="flex flex-wrap gap-3" aria-live="polite">{detail.resolution.steps.map((s,i) => <div key={s.id} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm transition-colors duration-150 motion-reduce:transition-none"><span className="text-blue-600 font-semibold">{i+1}. </span>{s.code}<div className="mt-1"><BmStatusBadge value={s.status}/></div></div>)}</div><p className="mt-4"><BmStatusBadge value={detail.resolution.status}/></p>{allowed('runtime.resolution.reresolve') && <BmButton className="mt-3" variant="secondary" disabled={busy} onClick={() => run(`/resolutions/${selected}/reresolve`,{})}>Relancer la résolution</BmButton>}</BmCard>
        {['manifest','effective','resolver','overview'].includes(section) && effective && <BmCard title={section === 'manifest' ? 'Manifest source' : 'Configuration effective'}><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Pack</dt><dd>{effective.source.packCode} · {effective.source.packVersion}</dd></div><div><dt className="text-slate-500">Exécutable</dt><dd>{effective.executable ? 'Oui' : 'Non — diagnostic à corriger'}</dd></div></dl><p className="my-3 text-xs break-all">{effective.source.manifestHash}</p><BmTable rows={[...(effective.modules ?? []),...(effective.features ?? [])]} columns={[{ key:'code',label:'Module / fonctionnalité' },{ key:'state',label:'État',render:r => <BmStatusBadge value={r.state}/> },{ key:'reasonCode',label:'Explication' }]} emptyState={<BmEmptyState title="Aucun module résolu"/>}/><details className="mt-4"><summary className="text-blue-700 cursor-pointer">Inspecter le contrat JSON</summary><pre className="max-h-96 overflow-auto bg-slate-50 rounded-lg p-4 text-xs">{JSON.stringify(section === 'manifest' ? sourceManifest : effective,null,2)}</pre></details></BmCard>}
        {detail.diagnostics.length > 0 || section === 'diagnostics' ? <BmCard title="Diagnostics">{detail.diagnostics.length ? <ul className="space-y-3">{detail.diagnostics.map(d => <li key={d.id} className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><strong>{d.code}</strong><p>{d.message}</p><span className="text-xs text-slate-500">Trace : {d.traceId}</span></li>)}</ul> : <BmEmptyState title="Aucun diagnostic pour cette résolution"/>}</BmCard> : null}</> : <BmEmptyState title="Aucune résolution sélectionnée" description="Résolvez un pack publié ou choisissez une résolution enregistrée."/>}
      </>}
      {section === 'cache' && <BmCard title="Cache Runtime" subtitle={`Mémoire locale · TTL ${data.cache.ttlMs / 1000} s · ${data.cache.entries} entrée(s)`}>{allowed('runtime.cache.invalidate') && <BmButton disabled={busy} variant="secondary" onClick={() => { if (window.confirm('Invalider le cache Runtime de ce tenant ?')) run('/cache/invalidate',{ scope:'TENANT' }); }}>Invalider le cache du tenant</BmButton>}<BmTable rows={data.entries} keyOf={r => r.key} columns={[{ key:'packCode',label:'Pack' },{ key:'state',label:'État' },{ key:'expiresAt',label:'Expiration',render:r => new Date(r.expiresAt).toLocaleString() }]} emptyState={<BmEmptyState title="Cache vide"/>}/></BmCard>}
    </>}
  </BmPage>;
}
