export const ERROR_CODES = {
  APPLICATION_NOT_FOUND: "APPLICATION_NOT_FOUND",
  APPLICATION_CODE_ALREADY_EXISTS: "APPLICATION_CODE_ALREADY_EXISTS",
  APPLICATION_INVALID_CODE: "APPLICATION_INVALID_CODE",
  APPLICATION_INVALID_STATUS: "APPLICATION_INVALID_STATUS",
  APPLICATION_ARCHIVED: "APPLICATION_ARCHIVED",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  VERSION_ALREADY_EXISTS: "VERSION_ALREADY_EXISTS",
  VERSION_INVALID_NUMBER: "VERSION_INVALID_NUMBER",
  VERSION_NOT_PUBLISHABLE: "VERSION_NOT_PUBLISHABLE",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  PUBLICATION_FAILED: "PUBLICATION_FAILED",
  PUBLICATION_CONFLICT: "PUBLICATION_CONFLICT",
  ROLLBACK_FAILED: "ROLLBACK_FAILED",
  CLONE_FAILED: "CLONE_FAILED",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  INVALID_REQUEST: "INVALID_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR"
};
// Allowed lifecycle transitions
export const ALLOWED_TRANSITIONS = {
  DRAFT: ["CONFIGURING", "ARCHIVED"],
  CONFIGURING: ["READY", "DRAFT", "ARCHIVED"],
  READY: ["TESTING", "CONFIGURING", "ARCHIVED"],
  TESTING: ["ACTIVE", "READY", "CONFIGURING", "ARCHIVED"],
  ACTIVE: ["SUSPENDED", "ARCHIVED"],
  SUSPENDED: ["ACTIVE", "ARCHIVED"],
  ARCHIVED: [],
  // Terminal
  ERROR: ["DRAFT", "CONFIGURING"]
};

// Permissions map
export const PERMISSIONS = {
  READ_APP: "business.application.read",
  CREATE_APP: "business.application.create",
  UPDATE_APP: "business.application.update",
  CLONE_APP: "business.application.clone",
  ARCHIVE_APP: "business.application.archive",
  READ_VERSION: "business.application.version.read",
  CREATE_VERSION: "business.application.version.create",
  VALIDATE_VERSION: "business.application.validate",
  PUBLISH_VERSION: "business.application.publish",
  ROLLBACK_VERSION: "business.application.rollback",
  READ_AUDIT: "business.application.audit.read"
};
export const ROLE_PERMISSIONS = {
  ADMIN: [PERMISSIONS.READ_APP, PERMISSIONS.CREATE_APP, PERMISSIONS.UPDATE_APP, PERMISSIONS.CLONE_APP, PERMISSIONS.ARCHIVE_APP, PERMISSIONS.READ_VERSION, PERMISSIONS.CREATE_VERSION, PERMISSIONS.VALIDATE_VERSION, PERMISSIONS.PUBLISH_VERSION, PERMISSIONS.ROLLBACK_VERSION, PERMISSIONS.READ_AUDIT],
  BUILDER: [PERMISSIONS.READ_APP, PERMISSIONS.CREATE_APP, PERMISSIONS.UPDATE_APP, PERMISSIONS.CLONE_APP, PERMISSIONS.READ_VERSION, PERMISSIONS.CREATE_VERSION, PERMISSIONS.VALIDATE_VERSION, PERMISSIONS.READ_AUDIT],
  VIEWER: [PERMISSIONS.READ_APP, PERMISSIONS.READ_VERSION, PERMISSIONS.READ_AUDIT]
};