import {
  UsersIcon,
  CubeIcon,
  ShoppingCartIcon,
  CurrencyEuroIcon,
  TruckIcon,
  DocumentTextIcon,
  ArchiveBoxIcon,
  ArrowTopRightOnSquareIcon,
  FolderOpenIcon,
  ScaleIcon,
  TagIcon,
  WrenchScrewdriverIcon,
  ArrowsRightLeftIcon,
  ClipboardDocumentListIcon,
  BellAlertIcon,
  ArrowPathIcon,
  PercentBadgeIcon,
  BanknotesIcon,
  CreditCardIcon,
  CalendarDaysIcon,
} from '@heroicons/react/24/outline';
import {
  clientService,
  productService,
  orderService,
  quoteService,
  invoiceService,
  paymentService,
  supplierService,
  warehouseService,
  shipmentService,
  documentService,
  purchaseService,
  stockMovementService,
  projectService,
  agendaService,
  productVariantService,
  serviceService,
  stockTransferService,
  inventoryService,
  stockAlertService,
  returnService,
  promotionService,
  cashRegisterService,
  expenseService,
  reservationService,
} from '../services/apiClient.js';

export const MODULES = [
  {
    key: 'clients',
    title: 'Clients',
    subtitle: 'Tiers clients Dolibarr (thirdparties)',
    icon: UsersIcon,
    gradient: 'from-[#3B4BA8] to-[#5469D4]',
    service: clientService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'nom', label: 'Nom' },
      { key: 'email', label: 'Email' },
      { key: 'telephone', label: 'Telephone' },
    ],
    create: true,
    fields: [
      { name: 'nom', label: 'Nom', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'telephone', label: 'Telephone', type: 'text' },
    ],
  },
  {
    key: 'products',
    title: 'Produits',
    subtitle: 'Produits et articles Dolibarr',
    icon: CubeIcon,
    gradient: 'from-emerald-500 to-teal-600',
    service: productService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'label', label: 'Libelle' },
      { key: 'price', label: 'Prix HT', money: true },
      { key: 'stock', label: 'Stock' },
    ],
    create: true,
    fields: [
      { name: 'ref', label: 'Reference', type: 'text', required: true },
      { name: 'label', label: 'Libelle', type: 'text', required: true },
      { name: 'price', label: 'Prix HT', type: 'number', step: '0.01' },
      { name: 'stock', label: 'Stock', type: 'number' },
    ],
  },
  {
    key: 'product-variants',
    title: 'Variantes',
    subtitle: 'Variantes de produits (attributs Dolibarr)',
    icon: TagIcon,
    gradient: 'from-amber-500 to-orange-600',
    service: productVariantService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'productId', label: 'Produit' },
      { key: 'attribute', label: 'Attribut' },
      { key: 'value', label: 'Valeur' },
      { key: 'price', label: 'Prix HT', money: true },
      { key: 'stock', label: 'Stock' },
    ],
    create: true,
    fields: [
      { name: 'productId', label: 'Produit', type: 'select', source: productService, labelKey: 'ref', valueKey: 'id', required: true },
      { name: 'ref', label: 'Reference', type: 'text', required: true },
      { name: 'attribute', label: 'Attribut', type: 'text', required: true },
      { name: 'value', label: 'Valeur', type: 'text', required: true },
      { name: 'price', label: 'Prix HT', type: 'number', step: '0.01' },
      { name: 'stock', label: 'Stock', type: 'number' },
    ],
  },
  {
    key: 'services',
    title: 'Services',
    subtitle: 'Services et prestations Dolibarr',
    icon: WrenchScrewdriverIcon,
    gradient: 'from-lime-500 to-green-600',
    service: serviceService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'label', label: 'Libelle' },
      { key: 'price', label: 'Prix HT', money: true },
      { key: 'duration', label: 'Duree (min)' },
    ],
    create: true,
    fields: [
      { name: 'ref', label: 'Reference', type: 'text' },
      { name: 'label', label: 'Libelle', type: 'text', required: true },
      { name: 'price', label: 'Prix HT', type: 'number', step: '0.01', required: true },
      { name: 'duration', label: 'Duree (minutes)', type: 'number' },
      { name: 'description', label: 'Description', type: 'text' },
    ],
  },
  {
    key: 'orders',
    title: 'Commandes',
    subtitle: 'Commandes clients Dolibarr (sales orders)',
    icon: ShoppingCartIcon,
    gradient: 'from-orange-500 to-amber-600',
    service: orderService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'clientId', label: 'Client' },
      { key: 'total', label: 'Total HT', money: true },
      { key: 'status', label: 'Statut' },
      { key: 'createdAt', label: 'Date' },
    ],
    create: true,
    lines: true,
    fields: [
      { name: 'clientId', label: 'Client', type: 'select', source: clientService, labelKey: 'nom', valueKey: 'id', required: true },
    ],
  },
  {
    key: 'quotes',
    title: 'Devis',
    subtitle: 'Propositions commerciales Dolibarr',
    icon: DocumentTextIcon,
    gradient: 'from-sky-500 to-blue-600',
    service: quoteService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'clientId', label: 'Client' },
      { key: 'total', label: 'Total HT', money: true },
      { key: 'status', label: 'Statut' },
      { key: 'validUntil', label: 'Valable jusqu au' },
    ],
    create: true,
    lines: true,
    fields: [
      { name: 'clientId', label: 'Client', type: 'select', source: clientService, labelKey: 'nom', valueKey: 'id', required: true },
      { name: 'validUntil', label: 'Valable jusqu au', type: 'date' },
      { name: 'status', label: 'Statut', type: 'select', options: [
        { value: 'BROUILLON', label: 'Brouillon' },
        { value: 'VALIDE', label: 'Valide' },
      ] },
    ],
  },
  {
    key: 'invoices',
    title: 'Factures',
    subtitle: 'Factures clients Dolibarr',
    icon: CurrencyEuroIcon,
    gradient: 'from-rose-500 to-pink-600',
    service: invoiceService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'clientId', label: 'Client' },
      { key: 'total', label: 'Total HT', money: true },
      { key: 'paid', label: 'Payee' },
      { key: 'status', label: 'Statut' },
      { key: 'dueDate', label: 'Echeance' },
    ],
    create: true,
    lines: true,
    fields: [
      { name: 'clientId', label: 'Client', type: 'select', source: clientService, labelKey: 'nom', valueKey: 'id', required: true },
      { name: 'dueDate', label: 'Echeance', type: 'date' },
      { name: 'status', label: 'Statut', type: 'select', options: [
        { value: 'BROUILLON', label: 'Brouillon' },
        { value: 'VALIDE', label: 'Valide' },
      ] },
    ],
  },
  {
    key: 'payments',
    title: 'Paiements',
    subtitle: 'Paiements clients reels Dolibarr (lecture API)',
    icon: CurrencyEuroIcon,
    gradient: 'from-violet-500 to-purple-600',
    service: paymentService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'amount', label: 'Montant', money: true },
      { key: 'method', label: 'Mode' },
      { key: 'status', label: 'Statut' },
      { key: 'paidAt', label: 'Date' },
    ],
    create: false,
    notice: "L'API REST Dolibarr 23.0.3 ne permet pas de creer des paiements (lecture seule). Creer le paiement directement dans Dolibarr.",
  },
  {
    key: 'suppliers',
    title: 'Fournisseurs',
    subtitle: 'Tiers fournisseurs Dolibarr',
    icon: TruckIcon,
    gradient: 'from-cyan-500 to-teal-600',
    service: supplierService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'nom', label: 'Nom' },
      { key: 'email', label: 'Email' },
      { key: 'telephone', label: 'Telephone' },
      { key: 'ville', label: 'Ville' },
    ],
    create: true,
    fields: [
      { name: 'nom', label: 'Nom', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'telephone', label: 'Telephone', type: 'text' },
      { name: 'adresse', label: 'Adresse', type: 'text' },
      { name: 'ville', label: 'Ville', type: 'text' },
    ],
  },
  {
    key: 'warehouses',
    title: 'Entrepots',
    subtitle: 'Entrepots reels Dolibarr (warehouses)',
    icon: ArchiveBoxIcon,
    gradient: 'from-slate-600 to-slate-800',
    service: warehouseService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'nom', label: 'Nom' },
      { key: 'ville', label: 'Ville' },
      { key: 'adresse', label: 'Adresse' },
    ],
    create: true,
    fields: [
      { name: 'nom', label: 'Nom', type: 'text', required: true },
      { name: 'ville', label: 'Ville', type: 'text' },
      { name: 'adresse', label: 'Adresse', type: 'text' },
    ],
  },
  {
    key: 'shipments',
    title: 'Expeditions',
    subtitle: 'Expeditions / livraisons Dolibarr',
    icon: TruckIcon,
    gradient: 'from-yellow-500 to-orange-600',
    service: shipmentService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'orderId', label: 'Commande' },
      { key: 'carrier', label: 'Transporteur' },
      { key: 'status', label: 'Statut' },
      { key: 'trackingNumber', label: 'Tracking' },
    ],
    create: true,
    fields: [
      { name: 'orderId', label: 'Commande (ref)', type: 'text' },
      { name: 'carrier', label: 'Transporteur', type: 'text' },
      { name: 'trackingNumber', label: 'Tracking', type: 'text' },
    ],
  },
  {
    key: 'documents',
    title: 'Documents',
    subtitle: 'Fichiers reels lies aux objets Dolibarr',
    icon: DocumentTextIcon,
    gradient: 'from-indigo-500 to-blue-600',
    service: documentService,
    columns: [
      { key: 'type', label: 'Module' },
      { key: 'ref', label: 'Fichier' },
      { key: 'size', label: 'Taille (octets)' },
      { key: 'createdAt', label: 'Date' },
    ],
    create: true,
    fields: [
      { name: 'type', label: 'Module', type: 'select', options: [
        { value: 'invoice', label: 'Facture' },
        { value: 'proposal', label: 'Devis' },
        { value: 'commande', label: 'Commande' },
        { value: 'thirdparty', label: 'Client' },
        { value: 'product', label: 'Produit' },
      ], required: true },
      { name: 'title', label: 'Titre du fichier', type: 'text', required: true },
      { name: 'relatedTo', label: 'Reference cible (ex: FA1007-0002)', type: 'text', required: true },
    ],
  },
  {
    key: 'purchases',
    title: 'Achats',
    subtitle: 'Bons de commande fournisseurs Dolibarr',
    icon: DocumentTextIcon,
    gradient: 'from-teal-500 to-emerald-700',
    service: purchaseService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'supplierId', label: 'Fournisseur' },
      { key: 'total', label: 'Total HT', money: true },
      { key: 'status', label: 'Statut' },
      { key: 'createdAt', label: 'Date' },
    ],
    create: true,
    lines: true,
    fields: [
      { name: 'supplierId', label: 'Fournisseur', type: 'select', source: supplierService, labelKey: 'nom', valueKey: 'id', required: true },
    ],
  },
  {
    key: 'stock-movements',
    title: 'Mouvements de stock',
    subtitle: 'Mouvements reels Dolibarr (stockmovements)',
    icon: ArrowTopRightOnSquareIcon,
    gradient: 'from-red-500 to-rose-700',
    service: stockMovementService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'productId', label: 'Produit' },
      { key: 'type', label: 'Type' },
      { key: 'quantity', label: 'Quantite' },
      { key: 'reason', label: 'Motif' },
      { key: 'date', label: 'Date' },
    ],
    create: true,
    fields: [
      { name: 'productId', label: 'Produit', type: 'select', source: productService, labelKey: 'ref', valueKey: 'id', required: true },
      { name: 'type', label: 'Type', type: 'select', options: [
        { value: 'ENTREE', label: 'ENTREE' },
        { value: 'SORTIE', label: 'SORTIE' },
      ], required: true },
      { name: 'quantity', label: 'Quantite', type: 'number', step: '1', required: true },
      { name: 'reason', label: 'Motif', type: 'text', required: true },
    ],
  },
  {
    key: 'stock-transfers',
    title: 'Transferts',
    subtitle: 'Transferts de stock entre entrepots',
    icon: ArrowsRightLeftIcon,
    gradient: 'from-yellow-500 to-amber-700',
    service: stockTransferService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'productId', label: 'Produit' },
      { key: 'quantity', label: 'Quantite' },
      { key: 'fromWarehouseId', label: 'De' },
      { key: 'toWarehouseId', label: 'Vers' },
      { key: 'status', label: 'Statut' },
    ],
    create: true,
    fields: [
      { name: 'productId', label: 'Produit', type: 'select', source: productService, labelKey: 'ref', valueKey: 'id', required: true },
      { name: 'quantity', label: 'Quantite', type: 'number', step: '1', required: true },
      { name: 'fromWarehouseId', label: 'Entrepot source', type: 'select', source: warehouseService, labelKey: 'nom', valueKey: 'id', required: true },
      { name: 'toWarehouseId', label: 'Entrepot destination', type: 'select', source: warehouseService, labelKey: 'nom', valueKey: 'id', required: true },
    ],
  },
  {
    key: 'inventories',
    title: 'Inventaires',
    subtitle: 'Inventaires de stock Dolibarr',
    icon: ClipboardDocumentListIcon,
    gradient: 'from-cyan-500 to-blue-700',
    service: inventoryService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'label', label: 'Libelle' },
      { key: 'type', label: 'Type' },
      { key: 'status', label: 'Statut' },
      { key: 'createdAt', label: 'Date' },
    ],
    create: true,
    fields: [
      { name: 'label', label: 'Libelle', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: [
        { value: 'PARTIEL', label: 'Partiel' },
        { value: 'GLOBAL', label: 'Global' },
      ], required: true },
    ],
  },
  {
    key: 'stock-alerts',
    title: 'Alertes stock',
    subtitle: 'Alertes de niveau de stock',
    icon: BellAlertIcon,
    gradient: 'from-rose-500 to-red-700',
    service: stockAlertService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'productId', label: 'Produit' },
      { key: 'level', label: 'Niveau' },
      { key: 'current', label: 'Actuel' },
      { key: 'threshold', label: 'Seuil' },
    ],
    create: true,
    fields: [
      { name: 'productId', label: 'Produit', type: 'select', source: productService, labelKey: 'ref', valueKey: 'id', required: true },
      { name: 'level', label: 'Niveau', type: 'select', options: [
        { value: 'LOW', label: 'Bas' },
        { value: 'OUT', label: 'Rupture' },
        { value: 'CRITICAL', label: 'Critique' },
      ], required: true },
      { name: 'current', label: 'Stock actuel', type: 'number', required: true },
      { name: 'threshold', label: 'Seuil', type: 'number', required: true },
    ],
  },
  {
    key: 'returns',
    title: 'Retours',
    subtitle: 'Retours clients Dolibarr',
    icon: ArrowPathIcon,
    gradient: 'from-purple-500 to-violet-700',
    service: returnService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'orderId', label: 'Commande' },
      { key: 'clientId', label: 'Client' },
      { key: 'reason', label: 'Motif' },
      { key: 'type', label: 'Type' },
      { key: 'status', label: 'Statut' },
    ],
    create: true,
    fields: [
      { name: 'orderId', label: 'Commande', type: 'select', source: orderService, labelKey: 'ref', valueKey: 'id', required: true },
      { name: 'clientId', label: 'Client', type: 'select', source: clientService, labelKey: 'nom', valueKey: 'id', required: true },
      { name: 'reason', label: 'Motif', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: [
        { value: 'REMBOURSEMENT', label: 'Remboursement' },
        { value: 'ECHANGE', label: 'Echange' },
        { value: 'AVOIR', label: 'Avoir' },
      ], required: true },
    ],
  },
  {
    key: 'promotions',
    title: 'Promotions',
    subtitle: 'Promotions et offres commerciales',
    icon: PercentBadgeIcon,
    gradient: 'from-fuchsia-500 to-pink-700',
    service: promotionService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'label', label: 'Libelle' },
      { key: 'type', label: 'Type' },
      { key: 'value', label: 'Valeur' },
      { key: 'appliesTo', label: 'Applique a' },
      { key: 'startDate', label: 'Debut' },
      { key: 'endDate', label: 'Fin' },
    ],
    create: true,
    fields: [
      { name: 'label', label: 'Libelle', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: [
        { value: 'PERCENTAGE', label: 'Pourcentage' },
        { value: 'FIXE', label: 'Montant fixe' },
        { value: 'BUY_X_GET_Y', label: 'Achetez X, obtenez Y' },
      ], required: true },
      { name: 'value', label: 'Valeur', type: 'number', step: '0.01', required: true },
      { name: 'appliesTo', label: 'Applique a', type: 'text', required: true },
      { name: 'startDate', label: 'Date de debut', type: 'date', required: true },
      { name: 'endDate', label: 'Date de fin', type: 'date', required: true },
    ],
  },
  {
    key: 'cash-registers',
    title: 'Caisses',
    subtitle: 'Caisses et fonds (POS)',
    icon: BanknotesIcon,
    gradient: 'from-teal-500 to-emerald-700',
    service: cashRegisterService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'label', label: 'Libelle' },
      { key: 'openingCash', label: 'Fond de caisse', money: true },
      { key: 'status', label: 'Statut' },
    ],
    create: true,
    fields: [
      { name: 'label', label: 'Libelle', type: 'text', required: true },
      { name: 'openingCash', label: 'Fond de caisse', type: 'number', step: '0.01', required: true },
    ],
  },
  {
    key: 'expenses',
    title: 'Depenses',
    subtitle: 'Depenses et charges',
    icon: CreditCardIcon,
    gradient: 'from-slate-500 to-slate-800',
    service: expenseService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'label', label: 'Libelle' },
      { key: 'amount', label: 'Montant', money: true },
      { key: 'category', label: 'Categorie' },
      { key: 'supplierId', label: 'Fournisseur' },
      { key: 'createdAt', label: 'Date' },
    ],
    create: true,
    fields: [
      { name: 'label', label: 'Libelle', type: 'text', required: true },
      { name: 'amount', label: 'Montant', type: 'number', step: '0.01', required: true },
      { name: 'category', label: 'Categorie', type: 'text', required: true },
      { name: 'supplierId', label: 'Fournisseur', type: 'select', source: supplierService, labelKey: 'nom', valueKey: 'id' },
    ],
  },
  {
    key: 'reservations',
    title: 'Reservations',
    subtitle: 'Reservations clients',
    icon: CalendarDaysIcon,
    gradient: 'from-indigo-500 to-blue-700',
    service: reservationService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'clientId', label: 'Client' },
      { key: 'quantity', label: 'Quantite' },
      { key: 'startAt', label: 'Debut', date: true },
      { key: 'endAt', label: 'Fin', date: true },
      { key: 'status', label: 'Statut' },
    ],
    create: true,
    fields: [
      { name: 'clientId', label: 'Client', type: 'select', source: clientService, labelKey: 'nom', valueKey: 'id', required: true },
      { name: 'startAt', label: 'Debut', type: 'datetime-local', required: true },
      { name: 'endAt', label: 'Fin', type: 'datetime-local', required: true },
    ],
  },
  {
    key: 'projects',
    title: 'Projets',
    subtitle: 'Projets reels Dolibarr',
    icon: FolderOpenIcon,
    gradient: 'from-[#3B4BA8] to-[#6C7BDD]',
    service: projectService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'ref', label: 'Ref' },
      { key: 'label', label: 'Libelle' },
      { key: 'clientId', label: 'Client' },
      { key: 'status', label: 'Statut' },
      { key: 'startDate', label: 'Debut' },
    ],
    create: true,
    fields: [
      { name: 'label', label: 'Libelle', type: 'text', required: true },
      { name: 'clientId', label: 'Client', type: 'select', source: clientService, labelKey: 'nom', valueKey: 'id' },
      { name: 'status', label: 'Statut', type: 'select', options: [
        { value: 'EN_COURS', label: 'En cours' },
        { value: 'TERMINE', label: 'Termine' },
      ] },
      { name: 'startDate', label: 'Date de debut', type: 'date' },
    ],
  },
  {
    key: 'agenda',
    title: 'Agenda',
    subtitle: 'Evenements d agenda Dolibarr',
    icon: ScaleIcon,
    gradient: 'from-lime-500 to-green-600',
    service: agendaService,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'title', label: 'Titre' },
      { key: 'type', label: 'Type' },
      { key: 'startAt', label: 'Debut', date: true },
      { key: 'endAt', label: 'Fin', date: true },
    ],
    create: true,
    fields: [
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'text', required: true },
      { name: 'startAt', label: 'Debut', type: 'datetime-local', required: true },
      { name: 'endAt', label: 'Fin', type: 'datetime-local', required: true },
    ],
  },
];

export const MODULES_BY_KEY = Object.fromEntries(MODULES.map((m) => [m.key, m]));
