/**
 * Codes d'erreur Billing (CDC 100).
 *
 * Le contrat global Techzone Cloud est reutilise : la classe porte `code`,
 * `traceId` et `statusCode`, et le filtre global
 * (`common/filters/all-exceptions.filter.ts`) les expose tels quels.
 * Aucun code n'est invente hors de la nomenclature du CDC 100.
 */
export enum BillingErrorCode {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_CODE_TAKEN = 'PRODUCT_CODE_TAKEN',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PLAN_CODE_TAKEN = 'PLAN_CODE_TAKEN',
  PLAN_INVALID_STATE = 'PLAN_INVALID_STATE',
  PRICE_NOT_FOUND = 'PRICE_NOT_FOUND',
  PRICE_INVALID_STATE = 'PRICE_INVALID_STATE',
  BILLING_ACCOUNT_NOT_FOUND = 'BILLING_ACCOUNT_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_NOT_ACTIVE = 'SUBSCRIPTION_NOT_ACTIVE',
  SUBSCRIPTION_ALREADY_CANCELLED = 'SUBSCRIPTION_ALREADY_CANCELLED',
  SUBSCRIPTION_INVALID_TRANSITION = 'SUBSCRIPTION_INVALID_TRANSITION',
  SUBSCRIPTION_CONFLICT = 'SUBSCRIPTION_CONFLICT',
  PLAN_CHANGE_NOT_ALLOWED = 'PLAN_CHANGE_NOT_ALLOWED',
  ENTITLEMENT_NOT_AVAILABLE = 'ENTITLEMENT_NOT_AVAILABLE',
  ENTITLEMENT_LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  FEATURE_NOT_FOUND = 'FEATURE_NOT_FOUND',
  FEATURE_CODE_TAKEN = 'FEATURE_CODE_TAKEN',
  METER_NOT_FOUND = 'METER_NOT_FOUND',
  METER_KEY_TAKEN = 'METER_KEY_TAKEN',
  USAGE_EVENT_DUPLICATE = 'USAGE_EVENT_DUPLICATE',
  USAGE_EVENT_INVALID = 'USAGE_EVENT_INVALID',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID',
  INVOICE_INVALID_STATE = 'INVOICE_INVALID_STATE',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_DUPLICATE = 'PAYMENT_DUPLICATE',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_WEBHOOK_INVALID = 'PAYMENT_WEBHOOK_INVALID',
  REFUND_NOT_ALLOWED = 'REFUND_NOT_ALLOWED',
  BILLING_CONFIGURATION_INVALID = 'BILLING_CONFIGURATION_INVALID',
  CURRENCY_NOT_SUPPORTED = 'CURRENCY_NOT_SUPPORTED',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  AMOUNT_INVALID = 'AMOUNT_INVALID',
  TENANT_SCOPE_VIOLATION = 'TENANT_SCOPE_VIOLATION',
  CROSS_TENANT_ACCESS_DENIED = 'CROSS_TENANT_ACCESS_DENIED',
}