/**
 * Pack Manager — constantes PM-CDC-00 (contrats communs).
 */

export const PM = {
  API_PREFIX: 'api/pack-manager',
  MANIFEST_CONTRACT: 'techzone.pack-manifest',
  MANIFEST_CONTRACT_VERSION: '1.0',
} as const;

/** Statuts de version à partir desquels la modification est interdite (immutabilité post-publication). */
export const PM_IMMUTABLE_VERSION_STATUSES = new Set<string>([
  'PUBLISHED',
  'SUPERSEDED',
  'ARCHIVED',
]);

/** Erreurs métier stables (PM-CDC-00 §26). */
export const PmErrorCode = {
  PACK_NOT_FOUND: 'PACK_NOT_FOUND',
  PACK_CODE_ALREADY_EXISTS: 'PACK_CODE_ALREADY_EXISTS',
  PACK_VERSION_NOT_FOUND: 'PACK_VERSION_NOT_FOUND',
  PACK_VERSION_IMMUTABLE: 'PACK_VERSION_IMMUTABLE',
  PACK_VERSION_CONFLICT: 'PACK_VERSION_CONFLICT',
  PACK_VALIDATION_FAILED: 'PACK_VALIDATION_FAILED',
  PACK_VALIDATION_OUTDATED: 'PACK_VALIDATION_OUTDATED',
  PACK_DEPENDENCY_MISSING: 'PACK_DEPENDENCY_MISSING',
  PACK_DEPENDENCY_CONFLICT: 'PACK_DEPENDENCY_CONFLICT',
  PACK_DEPENDENCY_CYCLE: 'PACK_DEPENDENCY_CYCLE',
  PACK_MANIFEST_INVALID: 'PACK_MANIFEST_INVALID',
  PACK_MANIFEST_NOT_GENERATED: 'PACK_MANIFEST_NOT_GENERATED',
  PACK_CONTRACT_INCOMPATIBLE: 'PACK_CONTRACT_INCOMPATIBLE',
  PACK_PUBLICATION_DENIED: 'PACK_PUBLICATION_DENIED',
} as const;

export type PmErrorCodeValue = (typeof PmErrorCode)[keyof typeof PmErrorCode];
