// Techzone Cloud Business Manager — Seed & Mock Data (BM-CDC-00, BM-CDC-01, BM-CDC-02)
import { computeSnapshotHash } from './snapshotService';

export const INITIAL_APPLICATIONS = [
  {
    id: 'app-9720-prem',
    tenantId: 'tenant-techzone-01',
    code: 'boutique-premium-e2e-9720',
    name: 'Boutique Premium E2E 9720',
    shortName: 'Boutique Premium',
    description: 'Application e-commerce premium avec gestion avancée des produits, commandes, paiements et clients.',
    category: 'Commerce',
    icon: 'ShoppingBag',
    status: 'ACTIVE',
    environment: 'PRODUCTION',
    sourceType: 'CUSTOM',
    color: '#3B82F6',
    defaultLocale: 'fr',
    timezone: 'Europe/Paris',
    currentVersionId: 'ver-9720-130',
    publishedVersionId: 'ver-9720-120',
    publishedVersionNumber: '1.2.0',
    currentVersionNumber: '1.3.0-dev',
    createdBy: 'Administrateur Business',
    createdAt: '2024-05-12T11:30:00.000Z',
    updatedAt: '2024-05-28T09:45:00.000Z',
    archivedAt: null,
    version: 8,
    metrics: {
      modulesCount: 24,
      featuresCount: 156,
      dataEntitiesCount: 38,
      menuItemsCount: 94,
    },
    tags: ['ecommerce', 'premium', 'boutique', 'paiement', 'produit', 'client'],
    notes: 'Application prioritaire pour le lancement de la nouvelle plateforme e-commerce. Attention particulière sur les performances et la sécurité des paiements.',
    notesUpdatedAt: '2024-05-27T09:24:00.000Z',
    environments: [
      { name: 'PRODUCTION', version: 'v1.2.0', status: 'ACTIF', publishedAt: '25/05/2024 09:00', health: 5 },
      { name: 'STAGING', version: 'v1.1.0', status: 'ACTIF', publishedAt: '27/05/2024 16:10', health: 5 },
      { name: 'TEST', version: 'v1.2.0-rc1', status: 'ACTIF', publishedAt: '28/05/2024 08:30', health: 5 },
      { name: 'DEVELOPMENT', version: 'v1.3.0-dev', status: 'DRAFT', publishedAt: '28/05/2024 09:40', health: 5 },
    ],
  },
  {
    id: 'app-9720-std',
    tenantId: 'tenant-techzone-01',
    code: 'boutique-e2e-9720',
    name: 'Boutique E2E 9720',
    shortName: 'Boutique Standard',
    description: 'E-commerce standard avec gestion du panier et catalogue de base.',
    category: 'Commerce',
    icon: 'Store',
    status: 'ACTIVE',
    environment: 'STAGING',
    sourceType: 'TEMPLATE',
    color: '#10B981',
    defaultLocale: 'fr',
    timezone: 'Europe/Paris',
    currentVersionId: 'ver-std-110',
    publishedVersionId: 'ver-std-110',
    publishedVersionNumber: '1.1.0',
    currentVersionNumber: '1.1.0',
    createdBy: 'Administrateur Business',
    createdAt: '2024-04-10T10:00:00.000Z',
    updatedAt: '2024-05-27T16:10:00.000Z',
    archivedAt: null,
    version: 4,
    metrics: {
      modulesCount: 16,
      featuresCount: 88,
      dataEntitiesCount: 19,
      menuItemsCount: 42,
    },
    tags: ['ecommerce', 'standard', 'boutique'],
    notes: 'Version stable pour test des passerelles bancaires.',
    notesUpdatedAt: '2024-05-20T10:00:00.000Z',
    environments: [
      { name: 'STAGING', version: 'v1.1.0', status: 'ACTIF', publishedAt: '27/05/2024 16:10', health: 5 },
      { name: 'TEST', version: 'v1.1.0', status: 'ACTIF', publishedAt: '27/05/2024 10:00', health: 5 },
    ],
  },
  {
    id: 'app-garage-2026',
    tenantId: 'tenant-techzone-01',
    code: 'garage-automobile-2026',
    name: 'Garage Automobile 2026',
    shortName: 'Garage 2026',
    description: 'Gestion d atelier mécanique, ordres de réparation, pièces détachées et parc véhicules.',
    category: 'Automobile',
    icon: 'Wrench',
    status: 'CONFIGURING',
    environment: 'DEVELOPMENT',
    sourceType: 'CUSTOM',
    color: '#8B5CF6',
    defaultLocale: 'fr',
    timezone: 'Europe/Paris',
    currentVersionId: 'ver-gar-050',
    publishedVersionId: null,
    publishedVersionNumber: null,
    currentVersionNumber: '0.5.0',
    createdBy: 'Administrateur Business',
    createdAt: '2024-05-18T16:45:00.000Z',
    updatedAt: '2024-05-28T09:40:00.000Z',
    archivedAt: null,
    version: 3,
    metrics: {
      modulesCount: 12,
      featuresCount: 45,
      dataEntitiesCount: 14,
      menuItemsCount: 28,
    },
    tags: ['automobile', 'garage', 'atelier', 'reparation'],
    notes: 'Validation des formulaires d entrée atelier en cours.',
    notesUpdatedAt: '2024-05-25T11:00:00.000Z',
    environments: [
      { name: 'DEVELOPMENT', version: 'v0.5.0', status: 'DRAFT', publishedAt: '-', health: 5 },
      { name: 'TEST', version: 'v0.5.0-rc', status: 'DRAFT', publishedAt: '-', health: 4 },
    ],
  },
  {
    id: 'app-finance-2024',
    tenantId: 'tenant-techzone-01',
    code: 'gestion-financiere',
    name: 'Gestion Financière',
    shortName: 'Finance',
    description: 'Finance & Comptabilité d entreprise, balances, factures et exports fiscaux.',
    category: 'Finance',
    icon: 'Building2',
    status: 'ACTIVE',
    environment: 'PRODUCTION',
    sourceType: 'SYSTEM',
    color: '#059669',
    defaultLocale: 'fr',
    timezone: 'Europe/Paris',
    currentVersionId: 'ver-fin-110',
    publishedVersionId: 'ver-fin-110',
    publishedVersionNumber: '1.1.0',
    currentVersionNumber: '1.1.0',
    createdBy: 'Administrateur Business',
    createdAt: '2024-04-01T09:00:00.000Z',
    updatedAt: '2024-05-25T09:00:00.000Z',
    archivedAt: null,
    version: 5,
    metrics: {
      modulesCount: 20,
      featuresCount: 110,
      dataEntitiesCount: 26,
      menuItemsCount: 65,
    },
    tags: ['finance', 'comptabilite', 'facturation'],
    notes: 'Clôture mensuelle automatisée configurée.',
    notesUpdatedAt: '2024-05-24T18:00:00.000Z',
    environments: [
      { name: 'PRODUCTION', version: 'v1.1.0', status: 'ACTIF', publishedAt: '25/05/2024 09:00', health: 5 },
    ],
  },
  {
    id: 'app-crm-2024',
    tenantId: 'tenant-techzone-01',
    code: 'crm-entreprise',
    name: 'CRM Entreprise',
    shortName: 'CRM',
    description: 'Gestion de la relation client, opportunités commerciales et suivi des prospects.',
    category: 'Services',
    icon: 'Briefcase',
    status: 'SUSPENDED',
    environment: 'STAGING',
    sourceType: 'CLONED',
    color: '#EF4444',
    defaultLocale: 'fr',
    timezone: 'Europe/Paris',
    currentVersionId: 'ver-crm-080',
    publishedVersionId: null,
    publishedVersionNumber: null,
    currentVersionNumber: '0.8.0',
    createdBy: 'Administrateur Business',
    createdAt: '2024-03-10T11:10:00.000Z',
    updatedAt: '2024-05-20T14:30:00.000Z',
    archivedAt: null,
    version: 2,
    metrics: {
      modulesCount: 14,
      featuresCount: 62,
      dataEntitiesCount: 16,
      menuItemsCount: 36,
    },
    tags: ['crm', 'commercial', 'prospects'],
    notes: 'Application mise en pause pour refonte de l API connecteur.',
    notesUpdatedAt: '2024-05-20T14:30:00.000Z',
    environments: [
      { name: 'STAGING', version: 'v0.8.0', status: 'SUSPENDU', publishedAt: '-', health: 3 },
    ],
  },
  {
    id: 'app-portail-client',
    tenantId: 'tenant-techzone-01',
    code: 'portail-client',
    name: 'Portail Client',
    shortName: 'Portail',
    description: 'Espace client sécurisé pour consultation de dossiers, factures et tickets de support.',
    category: 'Services',
    icon: 'Package',
    status: 'ACTIVE',
    environment: 'TEST',
    sourceType: 'CUSTOM',
    color: '#0284C7',
    defaultLocale: 'fr',
    timezone: 'Europe/Paris',
    currentVersionId: 'ver-port-100rc1',
    publishedVersionId: 'ver-port-100rc1',
    publishedVersionNumber: '1.0.0-rc1',
    currentVersionNumber: '1.0.0-rc1',
    createdBy: 'Administrateur Business',
    createdAt: '2024-05-02T10:00:00.000Z',
    updatedAt: '2024-05-26T11:20:00.000Z',
    archivedAt: null,
    version: 3,
    metrics: {
      modulesCount: 10,
      featuresCount: 52,
      dataEntitiesCount: 12,
      menuItemsCount: 22,
    },
    tags: ['portail', 'client', 'support', 'tickets'],
    notes: 'Phase de beta test avec 50 utilisateurs pilotes.',
    notesUpdatedAt: '2024-05-26T11:20:00.000Z',
    environments: [
      { name: 'TEST', version: 'v1.0.0-rc1', status: 'ACTIF', publishedAt: '26/05/2024 11:20', health: 5 },
      { name: 'DEVELOPMENT', version: 'v1.1.0-dev', status: 'DRAFT', publishedAt: '-', health: 5 },
    ],
  },
];

export const INITIAL_VERSIONS = [
  // Versions for Boutique Premium E2E 9720
  {
    id: 'ver-9720-120',
    applicationId: 'app-9720-prem',
    versionNumber: '1.2.0',
    status: 'PUBLISHED',
    environment: 'PRODUCTION',
    type: 'MAJOR',
    comment: 'Version stable en production avec gestion complète des paiements.',
    createdBy: 'Administrateur Business',
    createdAt: '2024-05-25T09:00:00.000Z',
    validatedAt: '2024-05-25T08:30:00.000Z',
    publishedAt: '2024-05-25T09:00:00.000Z',
    validationStatus: 'PASS',
    completeness: 100,
    snapshotHash: 'h_a1b2c3d4e5f6',
    snapshot: {
      appName: 'Boutique Premium E2E 9720',
      dataModels: [
        { code: 'product', name: 'Product', fields: ['code', 'name', 'price', 'stock', 'sku', 'vat'] },
        { code: 'order', name: 'Order', fields: ['orderNumber', 'customer', 'total', 'status', 'paymentMethod'] },
        { code: 'customer', name: 'Customer', fields: ['fullName', 'email', 'phone', 'tier', 'address'] },
        { code: 'category', name: 'Category', fields: ['title', 'slug', 'description'] },
      ],
      features: ['Catalog', 'Cart', 'Checkout', 'StripePayment', 'LoyaltyPoints', 'Invoicing', 'Analytics'],
      menus: [
        { id: 'm1', label: 'Accueil', path: '/' },
        { id: 'm2', label: 'Produits', path: '/products' },
        { id: 'm3', label: 'Commandes', path: '/orders' },
        { id: 'm4', label: 'Clients', path: '/customers' },
      ],
    },
    version: 4,
  },
  {
    id: 'ver-9720-110',
    applicationId: 'app-9720-prem',
    versionNumber: '1.1.0',
    status: 'SUPERSEDED',
    environment: 'STAGING',
    type: 'MINOR',
    comment: 'Ajout du programme de fidélité et codes promos.',
    createdBy: 'Administrateur Business',
    createdAt: '2024-04-27T10:30:00.000Z',
    validatedAt: '2024-04-27T10:00:00.000Z',
    publishedAt: '2024-04-27T10:30:00.000Z',
    validationStatus: 'PASS',
    completeness: 95,
    snapshotHash: 'h_f4e5d6c7b8a9',
    snapshot: {
      appName: 'Boutique Premium E2E 9720',
      dataModels: [
        { code: 'product', name: 'Product', fields: ['name', 'price', 'stock'] },
        { code: 'order', name: 'Order', fields: ['orderNumber', 'total'] },
      ],
      features: ['Catalog', 'Cart', 'Checkout', 'LoyaltyPoints'],
      menus: [{ id: 'm1', label: 'Accueil', path: '/' }],
    },
    version: 3,
  },
  {
    id: 'ver-9720-130',
    applicationId: 'app-9720-prem',
    versionNumber: '1.3.0-beta.1',
    status: 'DRAFT',
    environment: 'DEVELOPMENT',
    type: 'MAJOR',
    comment: 'Refonte multi-devises et moteur IA de recommandations produits.',
    createdBy: 'Jean Dupont (Développeur)',
    createdAt: '2024-05-20T14:20:00.000Z',
    validatedAt: null,
    publishedAt: null,
    validationStatus: 'OUTDATED',
    completeness: 75,
    snapshotHash: 'h_9a8b7c1d2e3f',
    snapshot: {
      appName: 'Boutique Premium E2E 9720',
      dataModels: [
        { code: 'product', name: 'Product', fields: ['code', 'name', 'price', 'currency', 'aiScore'] },
        { code: 'currency', name: 'Currency', fields: ['code', 'symbol', 'exchangeRate'] },
      ],
      features: ['Catalog', 'Cart', 'Checkout', 'MultiCurrency', 'AIRecommendations'],
      menus: [{ id: 'm1', label: 'Accueil', path: '/' }],
    },
    version: 1,
  },
  // Versions for Garage Automobile
  {
    id: 'ver-gar-050',
    applicationId: 'app-garage-2026',
    versionNumber: '0.5.0',
    status: 'READY',
    environment: 'DEVELOPMENT',
    type: 'MINOR',
    comment: 'Configuration des modèles de véhicules et ordres de travaux.',
    createdBy: 'Administrateur Business',
    createdAt: '2024-05-18T16:45:00.000Z',
    validatedAt: '2024-05-28T09:30:00.000Z',
    publishedAt: null,
    validationStatus: 'PASS',
    completeness: 90,
    snapshotHash: 'h_c9d8e7f6a5b4',
    snapshot: {
      appName: 'Garage Automobile 2026',
      dataModels: [
        { code: 'vehicle', name: 'Vehicle', fields: ['licensePlate', 'make', 'model', 'owner'] },
        { code: 'work_order', name: 'WorkOrder', fields: ['reference', 'status', 'laborHours'] },
      ],
      features: ['VehicleRegistry', 'DiagnosticSheet'],
      menus: [{ id: 'm1', label: 'Accueil', path: '/' }],
    },
    version: 2,
  },
  // Versions for Gestion Financière
  {
    id: 'ver-fin-110',
    applicationId: 'app-finance-2024',
    versionNumber: '1.1.0',
    status: 'PUBLISHED',
    environment: 'PRODUCTION',
    type: 'MINOR',
    comment: 'Clôture comptable trimestrielle et reporting fiscal.',
    createdBy: 'Administrateur Business',
    createdAt: '2024-05-25T09:00:00.000Z',
    validatedAt: '2024-05-25T08:50:00.000Z',
    publishedAt: '2024-05-25T09:00:00.000Z',
    validationStatus: 'PASS',
    completeness: 100,
    snapshotHash: 'h_a7b8c9d0e1f2',
    snapshot: {
      appName: 'Gestion Financière',
      dataModels: [{ code: 'invoice', name: 'Invoice', fields: ['num', 'amount', 'tax'] }],
      features: ['Ledger', 'Invoicing', 'TaxExport'],
      menus: [{ id: 'm1', label: 'Grand Livre', path: '/ledger' }],
    },
    version: 3,
  },
  // Versions for CRM
  {
    id: 'ver-crm-080',
    applicationId: 'app-crm-2024',
    versionNumber: '0.8.0',
    status: 'DEPRECATED',
    environment: 'STAGING',
    type: 'MINOR',
    comment: 'Remplacée par la nouvelle architecture v1.0.',
    createdBy: 'Administrateur Business',
    createdAt: '2024-03-10T11:10:00.000Z',
    validatedAt: null,
    publishedAt: null,
    validationStatus: 'FAIL',
    completeness: 60,
    snapshotHash: 'h_e1f2a3b4c5d6',
    snapshot: {
      appName: 'CRM Entreprise',
      dataModels: [{ code: 'contact', name: 'Contact', fields: ['name', 'email'] }],
      features: ['Leads'],
      menus: [{ id: 'm1', label: 'Leads', path: '/leads' }],
    },
    version: 1,
  },
  // Versions for Portail Client
  {
    id: 'ver-port-100rc1',
    applicationId: 'app-portail-client',
    versionNumber: '1.0.0-rc1',
    status: 'PUBLISHED',
    environment: 'TEST',
    type: 'PATCH',
    comment: 'Release Candidate 1 pour tests utilisateurs.',
    createdBy: 'Administrateur Business',
    createdAt: '2024-05-26T11:20:00.000Z',
    validatedAt: '2024-05-26T11:00:00.000Z',
    publishedAt: '2024-05-26T11:20:00.000Z',
    validationStatus: 'PASS',
    completeness: 98,
    snapshotHash: 'h_3d4e5f6a7b8c',
    snapshot: {
      appName: 'Portail Client',
      dataModels: [{ code: 'ticket', name: 'Ticket', fields: ['subject', 'priority', 'status'] }],
      features: ['HelpDesk', 'SelfService'],
      menus: [{ id: 'm1', label: 'Support', path: '/support' }],
    },
    version: 2,
  },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'evt-001',
    applicationId: 'app-9720-prem',
    applicationName: 'Boutique Premium E2E 9720',
    actorId: 'usr_admin_01',
    actorName: 'Administrateur Business',
    actorEmail: 'admin@techzone.io',
    actorRole: 'ADMIN',
    eventType: 'business.application.version.published',
    action: 'BUSINESS.VERSION.PUBLISHED',
    targetType: 'APPLICATION_VERSION',
    targetId: 'ver-9720-120',
    versionNumber: '1.2.0',
    result: 'SUCCESS',
    details: 'Publication transactionnelle de la version v1.2.0 sur PRODUCTION avec vérification d intégrité SHA-256',
    traceId: 'tr_9720pub01',
    createdAt: '2024-05-25T10:24:00.000Z',
    before: { status: 'READY', environment: 'STAGING', publishedVersion: '1.1.0' },
    after: { status: 'PUBLISHED', environment: 'PRODUCTION', publishedVersion: '1.2.0' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      snapshotHash: 'h_f4e3d2c1b0a9',
      validationScore: 100,
      ipAddress: '192.168.1.42',
    },
  },
  {
    id: 'evt-002',
    applicationId: 'app-9720-prem',
    applicationName: 'Boutique Premium E2E 9720',
    actorId: 'usr_admin_01',
    actorName: 'Administrateur Business',
    actorEmail: 'admin@techzone.io',
    actorRole: 'ADMIN',
    eventType: 'business.application.version.validated',
    action: 'BUSINESS.VERSION.VALIDATED',
    targetType: 'APPLICATION_VERSION',
    targetId: 'ver-9720-120',
    versionNumber: '1.2.0',
    result: 'SUCCESS',
    details: 'Validation d homologation réussie pour la version v1.2.0 (7/7 contrats techniques conformes, 100% complétude)',
    traceId: 'tr_9720val02',
    createdAt: '2024-05-25T10:22:00.000Z',
    before: { validationStatus: 'NOT_RUN', completeness: 70 },
    after: { validationStatus: 'PASS', completeness: 100, status: 'READY' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      passedChecks: 7,
      totalChecks: 7,
    },
  },
  {
    id: 'evt-003',
    applicationId: 'app-9720-prem',
    applicationName: 'Boutique Premium E2E 9720',
    actorId: 'usr_builder_02',
    actorName: 'Builder Studio',
    actorEmail: 'builder@techzone.io',
    actorRole: 'BUILDER',
    eventType: 'business.application.version.created',
    action: 'BUSINESS.VERSION.CREATED',
    targetType: 'APPLICATION_VERSION',
    targetId: 'ver-9720-120',
    versionNumber: '1.2.0',
    result: 'SUCCESS',
    details: 'Incrémentation SemVer MINOR: Création de la version v1.2.0 (DRAFT)',
    traceId: 'tr_9720cre03',
    createdAt: '2024-05-25T08:15:00.000Z',
    before: null,
    after: { versionNumber: '1.2.0', status: 'DRAFT', environment: 'DEVELOPMENT', type: 'MINOR' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      sourceVersion: '1.1.0',
      reason: 'Ajout du module de paiements échelonnés et fidélité',
    },
  },
  {
    id: 'evt-004',
    applicationId: 'app-finance-2024',
    applicationName: 'Gestion Financière',
    actorId: 'usr_admin_01',
    actorName: 'Administrateur Business',
    actorEmail: 'admin@techzone.io',
    actorRole: 'ADMIN',
    eventType: 'business.application.version.published',
    action: 'BUSINESS.VERSION.PUBLISHED',
    targetType: 'APPLICATION_VERSION',
    targetId: 'ver-fin-110',
    versionNumber: '1.1.0',
    result: 'SUCCESS',
    details: 'Déploiement de la version v1.1.0 sur PRODUCTION avec clôture comptable automatisée',
    traceId: 'tr_fin110pub04',
    createdAt: '2024-05-25T09:00:00.000Z',
    before: { status: 'READY', publishedVersion: '1.0.0' },
    after: { status: 'PUBLISHED', publishedVersion: '1.1.0' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      snapshotHash: 'h_a7b8c9d0e1f2',
    },
  },
  {
    id: 'evt-005',
    applicationId: 'app-finance-2024',
    applicationName: 'Gestion Financière',
    actorId: 'usr_builder_02',
    actorName: 'Builder Studio',
    actorEmail: 'builder@techzone.io',
    actorRole: 'BUILDER',
    eventType: 'data.schema.changed',
    action: 'DATA.SCHEMA.CHANGED',
    targetType: 'DATA_MODEL',
    targetId: 'ent_invoice_01',
    versionNumber: '1.1.0',
    result: 'SUCCESS',
    details: 'Ajout du champ "tax_rate_eu" et de la relation "CustomerInvoice" dans l entité Invoice',
    traceId: 'tr_fin110sch05',
    createdAt: '2024-05-24T17:45:00.000Z',
    before: { fieldsCount: 5 },
    after: { fieldsCount: 6, relation: 'CustomerInvoice' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      tableName: 'bm_invoice',
    },
  },
  {
    id: 'evt-006',
    applicationId: 'app-crm-2024',
    applicationName: 'CRM Entreprise',
    actorId: 'usr_admin_01',
    actorName: 'Administrateur Business',
    actorEmail: 'admin@techzone.io',
    actorRole: 'ADMIN',
    eventType: 'business.application.status.changed',
    action: 'BUSINESS.STATUS.TRANSITION',
    targetType: 'APPLICATION',
    targetId: 'app-crm-2024',
    versionNumber: '0.8.0',
    result: 'WARNING',
    details: 'Transition de statut vers SUSPENDED suite à la refonte de l API connecteur tiers',
    traceId: 'tr_crm080sus06',
    createdAt: '2024-05-20T14:30:00.000Z',
    before: { status: 'ACTIVE' },
    after: { status: 'SUSPENDED' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      comment: 'Mise en maintenance préventive',
    },
  },
  {
    id: 'evt-007',
    applicationId: 'app-portail-client',
    applicationName: 'Portail Client',
    actorId: 'usr_admin_01',
    actorName: 'Administrateur Business',
    actorEmail: 'admin@techzone.io',
    actorRole: 'ADMIN',
    eventType: 'business.application.version.published',
    action: 'BUSINESS.VERSION.PUBLISHED',
    targetType: 'APPLICATION_VERSION',
    targetId: 'ver-port-100rc1',
    versionNumber: '1.0.0-rc1',
    result: 'SUCCESS',
    details: 'Publication de la Release Candidate v1.0.0-rc1 sur l environnement TEST (pilote 50 utilisateurs)',
    traceId: 'tr_port100pub07',
    createdAt: '2024-05-26T11:20:00.000Z',
    before: { status: 'READY', publishedVersion: null },
    after: { status: 'PUBLISHED', publishedVersion: '1.0.0-rc1' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      snapshotHash: 'h_3d4e5f6a7b8c',
    },
  },
  {
    id: 'evt-008',
    applicationId: 'app-9720-prem',
    applicationName: 'Boutique Premium E2E 9720',
    actorId: 'usr_admin_01',
    actorName: 'Administrateur Business',
    actorEmail: 'admin@techzone.io',
    actorRole: 'ADMIN',
    eventType: 'business.application.version.rollback',
    action: 'BUSINESS.VERSION.ROLLBACK',
    targetType: 'APPLICATION_VERSION',
    targetId: 'ver-9720-110',
    versionNumber: '1.1.0',
    result: 'SUCCESS',
    details: 'Simulation de rollback vers la version stable précédente v1.1.0',
    traceId: 'tr_9720rol08',
    createdAt: '2024-05-23T14:10:00.000Z',
    before: { publishedVersion: '1.2.0-beta' },
    after: { publishedVersion: '1.1.0', status: 'ACTIVE' },
    metadata: {
      tenantId: 'tenant-techzone-01',
      reason: 'Restauration de secours',
    },
  },
];

export const CREATION_TEMPLATES = [
  {
    key: 'ecommerce',
    title: 'Boutique E-commerce',
    code: 'boutique-ecommerce',
    icon: 'ShoppingBag',
    color: '#3B82F6',
    category: 'Commerce',
    type: 'Standard',
    desc: 'Catalogue produits, panier, passage de commande, paiements et gestion des clients.',
    entitiesCount: 4,
    featuresCount: 7,
  },
  {
    key: 'restaurant',
    title: 'Restaurant & Carte',
    code: 'restaurant-carte',
    icon: 'UtensilsCrossed',
    color: '#F97316',
    category: 'Restauration',
    type: 'Standard',
    desc: 'Plats du jour, gestion des tables, réservations de salle et commandes cuisine.',
    entitiesCount: 3,
    featuresCount: 5,
  },
  {
    key: 'garage',
    title: 'Garage Automobile',
    code: 'garage-automobile',
    icon: 'Wrench',
    color: '#8B5CF6',
    category: 'Automobile',
    type: 'Standard',
    desc: 'Véhicules, ordres de réparation, diagnostics et stocks de pièces détachées.',
    entitiesCount: 3,
    featuresCount: 6,
  },
  {
    key: 'ecole',
    title: 'École & Inscriptions',
    code: 'ecole-inscriptions',
    icon: 'GraduationCap',
    color: '#06B6D4',
    category: 'Éducation',
    type: 'Standard',
    desc: 'Suivi des élèves, classes, plannings de cours, examens et enseignants.',
    entitiesCount: 4,
    featuresCount: 6,
  },
  {
    key: 'pharmacie',
    title: 'Pharmacie & Santé',
    code: 'pharmacie-sante',
    icon: 'Pill',
    color: '#10B981',
    category: 'Santé',
    type: 'Standard',
    desc: 'Gestion des ordonnances, stocks médicaments, fournisseurs et délivrances.',
    entitiesCount: 3,
    featuresCount: 5,
  },
  {
    key: 'hotel',
    title: 'Hôtel & Réservations',
    code: 'hotel-reservations',
    icon: 'Hotel',
    color: '#EC4899',
    category: 'Hôtellerie',
    type: 'Standard',
    desc: 'Chambres, réservations, check-in / check-out et facturation de séjour.',
    entitiesCount: 3,
    featuresCount: 5,
  },
];

// BM-CDC-03 Data Model Entities, Fields & Relations Seed
export const INITIAL_DATA_MODELS = [
  {
    id: 'ent_prod_01',
    applicationId: 'app-9720-prem',
    code: 'product',
    name: 'Produit',
    plural: 'Produits',
    tableName: 'bm_products',
    description: 'Article commercialisable avec gestion de stock, prix, TVA et déclinaisons.',
    category: 'Catalogue',
    isSystem: false,
    primaryKey: 'id',
    fields: [
      { id: 'f_p1', name: 'id', technicalName: 'id', type: 'UUID', required: true, isPrimary: true, isUnique: true, description: 'Identifiant universel unique' },
      { id: 'f_p2', name: 'code', technicalName: 'code', type: 'TEXT', required: true, isPrimary: false, isUnique: true, description: 'Code référence SKU produit (ex: PROD-998)' },
      { id: 'f_p3', name: 'name', technicalName: 'name', type: 'TEXT', required: true, isPrimary: false, isUnique: false, description: 'Désignation commerciale du produit' },
      { id: 'f_p4', name: 'price', technicalName: 'price_ht', type: 'CURRENCY', required: true, isPrimary: false, isUnique: false, defaultValue: '0.00', description: 'Prix unitaire Hors Taxes' },
      { id: 'f_p5', name: 'vat_rate', technicalName: 'vat_rate', type: 'DECIMAL', required: true, isPrimary: false, isUnique: false, defaultValue: '20.0', description: 'Taux de TVA en pourcentage' },
      { id: 'f_p6', name: 'stock', technicalName: 'stock_qty', type: 'INTEGER', required: true, isPrimary: false, isUnique: false, defaultValue: '0', description: 'Quantité physique en stock' },
      { id: 'f_p7', name: 'is_active', technicalName: 'is_active', type: 'BOOLEAN', required: true, isPrimary: false, isUnique: false, defaultValue: 'true', description: 'Visibilité dans le catalogue' },
      { id: 'f_p8', name: 'category_id', technicalName: 'category_id', type: 'RELATION', required: false, isPrimary: false, isUnique: false, targetEntity: 'category', relationType: 'MANY_TO_ONE', description: 'Catégorie principale de rattachement' },
    ],
    relations: [
      { id: 'rel_p_c', name: 'ProductCategory', targetEntityId: 'ent_cat_01', targetCode: 'category', type: 'MANY_TO_ONE', sourceField: 'category_id', targetField: 'id', onDelete: 'SET_NULL' },
      { id: 'rel_p_oi', name: 'ProductOrderItems', targetEntityId: 'ent_oi_01', targetCode: 'order_item', type: 'ONE_TO_MANY', sourceField: 'id', targetField: 'product_id', onDelete: 'RESTRICT' },
    ],
  },
  {
    id: 'ent_ord_01',
    applicationId: 'app-9720-prem',
    code: 'order',
    name: 'Commande',
    plural: 'Commandes',
    tableName: 'bm_orders',
    description: 'Transaction client enregistrant les articles achetés, le montant et le statut de livraison.',
    category: 'Ventes',
    isSystem: false,
    primaryKey: 'id',
    fields: [
      { id: 'f_o1', name: 'id', technicalName: 'id', type: 'UUID', required: true, isPrimary: true, isUnique: true, description: 'Identifiant commande' },
      { id: 'f_o2', name: 'order_number', technicalName: 'order_number', type: 'TEXT', required: true, isPrimary: false, isUnique: true, description: 'Numéro de facture / commande séquentiel' },
      { id: 'f_o3', name: 'customer_id', technicalName: 'customer_id', type: 'RELATION', required: true, isPrimary: false, isUnique: false, targetEntity: 'customer', relationType: 'MANY_TO_ONE', description: 'Client ayant passé la commande' },
      { id: 'f_o4', name: 'total_amount', technicalName: 'total_ttc', type: 'CURRENCY', required: true, isPrimary: false, isUnique: false, defaultValue: '0.00', description: 'Total TTC de la commande' },
      { id: 'f_o5', name: 'status', technicalName: 'status', type: 'ENUM', required: true, isPrimary: false, isUnique: false, enumValues: ['DRAFT', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED'], defaultValue: 'DRAFT', description: 'État du cycle de vie commande' },
      { id: 'f_o6', name: 'payment_method', technicalName: 'payment_method', type: 'TEXT', required: true, isPrimary: false, isUnique: false, defaultValue: 'STRIPE', description: 'Méthode de paiement retenue' },
      { id: 'f_o7', name: 'created_at', technicalName: 'created_at', type: 'DATETIME', required: true, isPrimary: false, isUnique: false, defaultValue: 'NOW()', description: 'Date de validation du panier' },
    ],
    relations: [
      { id: 'rel_o_c', name: 'OrderCustomer', targetEntityId: 'ent_cust_01', targetCode: 'customer', type: 'MANY_TO_ONE', sourceField: 'customer_id', targetField: 'id', onDelete: 'RESTRICT' },
      { id: 'rel_o_items', name: 'OrderItems', targetEntityId: 'ent_oi_01', targetCode: 'order_item', type: 'ONE_TO_MANY', sourceField: 'id', targetField: 'order_id', onDelete: 'CASCADE' },
    ],
  },
  {
    id: 'ent_cust_01',
    applicationId: 'app-9720-prem',
    code: 'customer',
    name: 'Client',
    plural: 'Clients',
    tableName: 'bm_customers',
    description: 'Profil client, coordonnées, adresse de facturation et historique de fidélité.',
    category: 'CRM',
    isSystem: false,
    primaryKey: 'id',
    fields: [
      { id: 'f_c1', name: 'id', technicalName: 'id', type: 'UUID', required: true, isPrimary: true, isUnique: true, description: 'Identifiant unique client' },
      { id: 'f_c2', name: 'full_name', technicalName: 'full_name', type: 'TEXT', required: true, isPrimary: false, isUnique: false, description: 'Nom complet ou raison sociale' },
      { id: 'f_c3', name: 'email', technicalName: 'email', type: 'TEXT', required: true, isPrimary: false, isUnique: true, description: 'Adresse email professionnelle' },
      { id: 'f_c4', name: 'phone', technicalName: 'phone', type: 'TEXT', required: false, isPrimary: false, isUnique: false, description: 'Numéro de téléphone direct' },
      { id: 'f_c5', name: 'tier', technicalName: 'loyalty_tier', type: 'ENUM', required: true, isPrimary: false, isUnique: false, enumValues: ['STANDARD', 'SILVER', 'GOLD', 'VIP'], defaultValue: 'STANDARD', description: 'Niveau du programme fidélité' },
      { id: 'f_c6', name: 'loyalty_points', technicalName: 'loyalty_points', type: 'INTEGER', required: true, isPrimary: false, isUnique: false, defaultValue: '0', description: 'Solde de points fidélité' },
    ],
    relations: [
      { id: 'rel_c_o', name: 'CustomerOrders', targetEntityId: 'ent_ord_01', targetCode: 'order', type: 'ONE_TO_MANY', sourceField: 'id', targetField: 'customer_id', onDelete: 'RESTRICT' },
    ],
  },
  {
    id: 'ent_cat_01',
    applicationId: 'app-9720-prem',
    code: 'category',
    name: 'Catégorie',
    plural: 'Catégories',
    tableName: 'bm_categories',
    description: 'Arborescence hiérarchique de classification des articles.',
    category: 'Catalogue',
    isSystem: false,
    primaryKey: 'id',
    fields: [
      { id: 'f_cat1', name: 'id', technicalName: 'id', type: 'UUID', required: true, isPrimary: true, isUnique: true, description: 'ID catégorie' },
      { id: 'f_cat2', name: 'title', technicalName: 'title', type: 'TEXT', required: true, isPrimary: false, isUnique: false, description: 'Titre affiché en boutique' },
      { id: 'f_cat3', name: 'slug', technicalName: 'slug', type: 'TEXT', required: true, isPrimary: false, isUnique: true, description: 'Identifiant URL unique' },
      { id: 'f_cat4', name: 'parent_id', technicalName: 'parent_id', type: 'RELATION', required: false, isPrimary: false, isUnique: false, targetEntity: 'category', relationType: 'MANY_TO_ONE', description: 'Catégorie parente (arborescence)' },
    ],
    relations: [
      { id: 'rel_cat_p', name: 'CategoryProducts', targetEntityId: 'ent_prod_01', targetCode: 'product', type: 'ONE_TO_MANY', sourceField: 'id', targetField: 'category_id', onDelete: 'SET_NULL' },
    ],
  },
  {
    id: 'ent_oi_01',
    applicationId: 'app-9720-prem',
    code: 'order_item',
    name: 'Ligne de Commande',
    plural: 'Lignes de Commande',
    tableName: 'bm_order_items',
    description: 'Détail d un produit et quantité commandée dans un panier.',
    category: 'Ventes',
    isSystem: false,
    primaryKey: 'id',
    fields: [
      { id: 'f_oi1', name: 'id', technicalName: 'id', type: 'UUID', required: true, isPrimary: true, isUnique: true, description: 'ID de ligne' },
      { id: 'f_oi2', name: 'order_id', technicalName: 'order_id', type: 'RELATION', required: true, isPrimary: false, isUnique: false, targetEntity: 'order', relationType: 'MANY_TO_ONE', description: 'Commande parente' },
      { id: 'f_oi3', name: 'product_id', technicalName: 'product_id', type: 'RELATION', required: true, isPrimary: false, isUnique: false, targetEntity: 'product', relationType: 'MANY_TO_ONE', description: 'Produit commandé' },
      { id: 'f_oi4', name: 'quantity', technicalName: 'quantity', type: 'INTEGER', required: true, isPrimary: false, isUnique: false, defaultValue: '1', description: 'Quantité unitaire achetée' },
      { id: 'f_oi5', name: 'unit_price', technicalName: 'unit_price', type: 'CURRENCY', required: true, isPrimary: false, isUnique: false, description: 'Prix figé au moment de l achat' },
    ],
    relations: [
      { id: 'rel_oi_o', name: 'OrderItemOrder', targetEntityId: 'ent_ord_01', targetCode: 'order', type: 'MANY_TO_ONE', sourceField: 'order_id', targetField: 'id', onDelete: 'CASCADE' },
      { id: 'rel_oi_p', name: 'OrderItemProduct', targetEntityId: 'ent_prod_01', targetCode: 'product', type: 'MANY_TO_ONE', sourceField: 'product_id', targetField: 'id', onDelete: 'RESTRICT' },
    ],
  },
];

// BM-CDC-04 Feature & Capability Seed
export const INITIAL_FEATURES = [
  {
    id: 'feat_catalog',
    code: 'catalog.management',
    name: 'Gestion de Catalogue Produits',
    domain: 'Commerce',
    description: 'Exploration, création, mise à jour des fiches articles et déclinaisons.',
    status: 'ACTIVE',
    source: 'SYSTEM',
    icon: 'Boxes',
    capabilities: [
      { id: 'cap_cat_read', code: 'catalog.product.read', name: 'Consulter les produits', type: 'READ', risk: 'LOW', required: true },
      { id: 'cap_cat_create', code: 'catalog.product.create', name: 'Créer un produit', type: 'CREATE', risk: 'MEDIUM', required: true },
      { id: 'cap_cat_update', code: 'catalog.product.update', name: 'Modifier un produit', type: 'UPDATE', risk: 'MEDIUM', required: true },
      { id: 'cap_cat_delete', code: 'catalog.product.delete', name: 'Supprimer un produit', type: 'DELETE', risk: 'HIGH', required: false },
    ],
    requiredEntities: ['product', 'category'],
    dependencies: [],
  },
  {
    id: 'feat_checkout',
    code: 'sales.checkout',
    name: 'Tunnel de Commande & Panier',
    domain: 'Ventes',
    description: 'Gestion du panier d achat, validation des stocks et finalisation de commande.',
    status: 'ACTIVE',
    source: 'SYSTEM',
    icon: 'ShoppingCart',
    capabilities: [
      { id: 'cap_chk_cart', code: 'sales.cart.manage', name: 'Gérer le panier', type: 'UPDATE', risk: 'LOW', required: true },
      { id: 'cap_chk_process', code: 'sales.order.checkout', name: 'Valider la commande', type: 'ACTION', risk: 'HIGH', required: true },
      { id: 'cap_chk_cancel', code: 'sales.order.cancel', name: 'Annuler une commande', type: 'ACTION', risk: 'HIGH', required: false },
    ],
    requiredEntities: ['order', 'order_item', 'customer'],
    dependencies: [
      { targetCode: 'catalog.management', type: 'REQUIRES' },
    ],
  },
  {
    id: 'feat_stripe',
    code: 'payment.stripe',
    name: 'Passerelle Paiement Stripe',
    domain: 'Finance',
    description: 'Traitement sécurisé des cartes bancaires, 3D Secure et remboursements.',
    status: 'ACTIVE',
    source: 'PACK',
    icon: 'CreditCard',
    capabilities: [
      { id: 'cap_pay_charge', code: 'payment.stripe.charge', name: 'Débiter le paiement', type: 'ACTION', risk: 'CRITICAL', required: true },
      { id: 'cap_pay_refund', code: 'payment.stripe.refund', name: 'Effectuer un remboursement', type: 'ACTION', risk: 'CRITICAL', required: false },
    ],
    requiredEntities: ['order'],
    dependencies: [
      { targetCode: 'sales.checkout', type: 'REQUIRES' },
    ],
  },
  {
    id: 'feat_loyalty',
    code: 'crm.loyalty',
    name: 'Programme de Fidélité',
    domain: 'Marketing',
    description: 'Attribution de points, paliers de fidélité et bons de réduction.',
    status: 'ACTIVE',
    source: 'PACK',
    icon: 'Gift',
    capabilities: [
      { id: 'cap_loy_accrue', code: 'loyalty.points.accrue', name: 'Cumuler des points', type: 'ACTION', risk: 'LOW', required: true },
      { id: 'cap_loy_redeem', code: 'loyalty.points.redeem', name: 'Consommer des points', type: 'ACTION', risk: 'MEDIUM', required: true },
    ],
    requiredEntities: ['customer'],
    dependencies: [
      { targetCode: 'sales.checkout', type: 'IMPLIES' },
    ],
  },
  {
    id: 'feat_ai_recom',
    code: 'ai.recommendations',
    name: 'Recommandations Produits IA',
    domain: 'Intelligence',
    description: 'Algorithme prédictif de suggestions d articles complémentaires.',
    status: 'DRAFT',
    source: 'CUSTOM',
    icon: 'Sparkles',
    capabilities: [
      { id: 'cap_ai_suggest', code: 'ai.catalog.suggest', name: 'Générer des suggestions', type: 'ACTION', risk: 'LOW', required: true },
    ],
    requiredEntities: ['product', 'order'],
    dependencies: [
      { targetCode: 'catalog.management', type: 'REQUIRES' },
    ],
  },
];

// BM-CDC-05 Menu Engine Navigation Seed
export const INITIAL_MENUS = [
  {
    id: 'menu_sidebar_main',
    location: 'SIDEBAR',
    name: 'Navigation Principale',
    description: 'Menu latéral pour les utilisateurs de l application métier.',
    items: [
      {
        id: 'nav_dash',
        label: 'Tableau de bord',
        icon: 'LayoutDashboard',
        targetType: 'ROUTE',
        route: '/dashboard',
        openMode: 'SAME_VIEW',
        badge: null,
        requiredFeatures: [],
        requiredCapabilities: [],
        matchMode: 'ALL',
        order: 1,
        children: [],
      },
      {
        id: 'nav_cat',
        label: 'Catalogue',
        icon: 'Boxes',
        targetType: 'NONE',
        route: null,
        openMode: 'SAME_VIEW',
        badge: '156',
        requiredFeatures: ['catalog.management'],
        requiredCapabilities: ['catalog.product.read'],
        matchMode: 'ALL',
        order: 2,
        children: [
          {
            id: 'nav_cat_products',
            label: 'Tous les produits',
            icon: 'ShoppingBag',
            targetType: 'ROUTE',
            route: '/products',
            openMode: 'SAME_VIEW',
            badge: null,
            requiredFeatures: ['catalog.management'],
            requiredCapabilities: ['catalog.product.read'],
            matchMode: 'ALL',
            order: 1,
          },
          {
            id: 'nav_cat_cats',
            label: 'Catégories',
            icon: 'Layers',
            targetType: 'ROUTE',
            route: '/categories',
            openMode: 'SAME_VIEW',
            badge: null,
            requiredFeatures: ['catalog.management'],
            requiredCapabilities: ['catalog.product.read'],
            matchMode: 'ALL',
            order: 2,
          },
        ],
      },
      {
        id: 'nav_sales',
        label: 'Ventes & Commandes',
        icon: 'ShoppingCart',
        targetType: 'NONE',
        route: null,
        openMode: 'SAME_VIEW',
        badge: 'Nouveau',
        requiredFeatures: ['sales.checkout'],
        requiredCapabilities: [],
        matchMode: 'ALL',
        order: 3,
        children: [
          {
            id: 'nav_sales_orders',
            label: 'Commandes',
            icon: 'FileText',
            targetType: 'ROUTE',
            route: '/orders',
            openMode: 'SAME_VIEW',
            badge: '12 en attente',
            requiredFeatures: ['sales.checkout'],
            requiredCapabilities: [],
            matchMode: 'ALL',
            order: 1,
          },
          {
            id: 'nav_sales_cust',
            label: 'Clients',
            icon: 'Users',
            targetType: 'ROUTE',
            route: '/customers',
            openMode: 'SAME_VIEW',
            badge: null,
            requiredFeatures: [],
            requiredCapabilities: [],
            matchMode: 'ALL',
            order: 2,
          },
        ],
      },
      {
        id: 'nav_loyalty',
        label: 'Programme Fidélité',
        icon: 'Gift',
        targetType: 'ROUTE',
        route: '/loyalty',
        openMode: 'SAME_VIEW',
        badge: 'VIP',
        requiredFeatures: ['crm.loyalty'],
        requiredCapabilities: ['loyalty.points.accrue'],
        matchMode: 'ALL',
        order: 4,
        children: [],
      },
      {
        id: 'nav_settings',
        label: 'Configuration',
        icon: 'Settings',
        targetType: 'ROUTE',
        route: '/settings',
        openMode: 'SAME_VIEW',
        badge: null,
        requiredFeatures: [],
        requiredCapabilities: [],
        matchMode: 'ALL',
        order: 5,
        children: [],
      },
    ],
  },
  {
    id: 'menu_bottom_nav',
    location: 'BOTTOM_NAV',
    name: 'Navigation Mobile',
    description: 'Barre de navigation tactile adaptée aux smartphones.',
    items: [
      { id: 'mb_1', label: 'Accueil', icon: 'LayoutDashboard', route: '/dashboard', order: 1 },
      { id: 'mb_2', label: 'Articles', icon: 'ShoppingBag', route: '/products', order: 2 },
      { id: 'mb_3', label: 'Panier', icon: 'ShoppingCart', route: '/cart', order: 3 },
      { id: 'mb_4', label: 'Profil', icon: 'Users', route: '/profile', order: 4 },
    ],
  },
];

// BM-CDC-06 Configuration & Metadata Seed
export const INITIAL_CONFIG_DEFINITIONS = [
  {
    code: 'ecommerce.checkout.currency',
    label: 'Devise principale',
    section: 'Ventes & Monnaie',
    dataType: 'ENUM',
    enumValues: ['EUR', 'USD', 'GBP', 'CAD', 'CHF'],
    defaultValue: 'EUR',
    scope: 'APPLICATION',
    isSecret: false,
    runtimeExposed: true,
    description: 'Devise utilisée pour le calcul des prix et des transactions Stripe.',
    storedValue: 'EUR',
    effectiveValue: 'EUR',
    inheritance: 'TENANT',
  },
  {
    code: 'ecommerce.checkout.default_vat',
    label: 'Taux TVA par défaut (%)',
    section: 'Ventes & Monnaie',
    dataType: 'NUMBER',
    defaultValue: 20.0,
    scope: 'APPLICATION_VERSION',
    isSecret: false,
    runtimeExposed: true,
    description: 'Taux de taxe sur la valeur ajoutée applicable automatiquement aux nouveaux articles.',
    storedValue: 20.0,
    effectiveValue: 20.0,
    inheritance: 'OVERRIDE',
  },
  {
    code: 'security.stripe.publishable_key',
    label: 'Clé Publique Stripe (PK)',
    section: 'Passerelle de Paiement',
    dataType: 'STRING',
    defaultValue: 'pk_test_sample51Nxxxxxxx',
    scope: 'ENVIRONMENT',
    isSecret: false,
    runtimeExposed: true,
    description: 'Identifiant public pour initialiser Stripe Elements côté client.',
    storedValue: 'pk_live_51N89720TechzonePrem001',
    effectiveValue: 'pk_live_51N89720TechzonePrem001',
    inheritance: 'OVERRIDE',
  },
  {
    code: 'security.stripe.secret_key',
    label: 'Clé Secrète Stripe (SK)',
    section: 'Passerelle de Paiement',
    dataType: 'SECRET',
    defaultValue: 'sk_test_••••••••••••',
    scope: 'ENVIRONMENT',
    isSecret: true,
    runtimeExposed: false,
    description: 'Clé d API serveur strictement confidentielle pour valider les débits.',
    storedValue: 'sk_live_998877665544332211aabbcc',
    effectiveValue: '••••••••••••••••••••••••••••••••',
    inheritance: 'OVERRIDE',
  },
  {
    code: 'crm.loyalty.points_multiplier',
    label: 'Facteur de conversion points (€ -> pts)',
    section: 'Programme Fidélité',
    dataType: 'NUMBER',
    defaultValue: 10,
    scope: 'APPLICATION',
    isSecret: false,
    runtimeExposed: true,
    description: 'Nombre de points accordés pour chaque euro dépensé en boutique.',
    storedValue: 10,
    effectiveValue: 10,
    inheritance: 'TENANT',
  },
];

// BM-CDC-07 Integrations & Runtime Contracts Seed
export const INITIAL_INTEGRATIONS = [
  {
    id: 'int_erp_odoo',
    code: 'erp.odoo.adapter',
    name: 'Connecteur ERP Odoo / SAP',
    category: 'ERP & Comptabilité',
    provider: 'Techzone Cloud Runtime',
    status: 'CONNECTED',
    protocol: 'REST_JSON',
    endpoint: 'https://erp.techzone.io/api/v2/sync',
    latencyMs: 38,
    lastSync: 'Il y a 4 min',
    health: 'HEALTHY',
    boundEntities: ['product', 'order', 'customer'],
  },
  {
    id: 'int_stripe',
    code: 'payment.stripe.gateway',
    name: 'Stripe Payments v2024',
    category: 'Paiement',
    provider: 'Stripe Inc.',
    status: 'CONNECTED',
    protocol: 'WEBHOOK_HMAC',
    endpoint: 'https://api.stripe.com/v1',
    latencyMs: 64,
    lastSync: 'Il y a 12 sec',
    health: 'HEALTHY',
    boundEntities: ['order'],
  },
  {
    id: 'int_msg_sendgrid',
    code: 'messaging.email.sendgrid',
    name: 'SendGrid Transactional Mails',
    category: 'Messagerie',
    provider: 'Twilio SendGrid',
    status: 'CONNECTED',
    protocol: 'SMTP_REST',
    endpoint: 'https://api.sendgrid.com/v3/mail/send',
    latencyMs: 110,
    lastSync: 'Il y a 1 heure',
    health: 'HEALTHY',
    boundEntities: ['customer', 'order'],
  },
  {
    id: 'int_storage_s3',
    code: 'storage.assets.s3',
    name: 'AWS S3 Asset Bucket (Paris)',
    category: 'Stockage & Médias',
    provider: 'Amazon Web Services',
    status: 'CONFIGURED',
    protocol: 'S3_V4',
    endpoint: 'https://s3.eu-west-3.amazonaws.com/techzone-assets',
    latencyMs: 22,
    lastSync: 'Il y a 30 min',
    health: 'HEALTHY',
    boundEntities: ['product'],
  },
];

// BM-CDC-08 Quality & Testing Campaigns Seed
export const INITIAL_QUALITY_RULES = [
  {
    code: 'Q_RULE_APP_IDENTITY',
    cdc: 'BM-CDC-01',
    name: 'Identité et unicité de l application',
    severity: 'BLOCKING',
    category: 'APPLICATION',
    description: 'L application doit posséder un code kebab-case unique et un nom non vide.',
  },
  {
    code: 'Q_RULE_SEMVER_COMPLIANCE',
    cdc: 'BM-CDC-02',
    name: 'Conformité sémantique SemVer',
    severity: 'BLOCKING',
    category: 'VERSION',
    description: 'Les numéros de versions doivent respecter STRICTEMENT la spécification SemVer X.Y.Z.',
  },
  {
    code: 'Q_RULE_SCHEMA_PRIMARY_KEYS',
    cdc: 'BM-CDC-03',
    name: 'Clés primaires du modèle de données',
    severity: 'BLOCKING',
    category: 'DATA_MODEL',
    description: 'Chaque entité active doit déclarer au moins une clé primaire unique.',
  },
  {
    code: 'Q_RULE_FEATURE_DEP_CYCLES',
    cdc: 'BM-CDC-04',
    name: 'Absence de cycles dans les dépendances de fonctionnalités',
    severity: 'BLOCKING',
    category: 'FEATURE',
    description: 'Le graphe orienté des dépendances de fonctionnalités doit être un DAG acyclique.',
  },
  {
    code: 'Q_RULE_NAVIGATION_ORPHANS',
    cdc: 'BM-CDC-05',
    name: 'Résolution des éléments de navigation',
    severity: 'WARNING',
    category: 'NAVIGATION',
    description: 'Tout élément de menu doit pointer vers une route valide ou masquer ses enfants vides.',
  },
  {
    code: 'Q_RULE_SECRET_STORAGE',
    cdc: 'BM-CDC-06',
    name: 'Chiffrement et masquage des secrets',
    severity: 'BLOCKING',
    category: 'CONFIGURATION',
    description: 'Les clés privées et secrets ne doivent jamais être exposés au runtime client.',
  },
  {
    code: 'Q_RULE_RUNTIME_MANIFEST',
    cdc: 'BM-CDC-07',
    name: 'Signature et intégrité du manifeste runtime',
    severity: 'BLOCKING',
    category: 'INTEGRATION',
    description: 'Le hash de snapshot calculé doit correspondre au payload déterministe généré.',
  },
];

