// mockPackData.js — Pack Manager Seed & Mock Data (PM-CDC-00, PM-CDC-01, PM-CDC-02, PM-CDC-03..07)
import {
  PACK_STATUS,
  PACK_VERSION_STATUS,
  PACK_VALIDATION_STATUS,
  PACK_MANIFEST_STATUS,
  PACK_SOURCE_TYPE,
  MODULE_TYPE,
  FEATURE_TYPE,
  CAPABILITY_TYPE,
  CAPABILITY_RELATION_TYPE,
  DEPENDENCY_TYPE,
  DEPENDENCY_RESOLUTION_STATUS,
  RULE_TYPE,
  RULE_EFFECT,
} from '../types/domain';

export const INITIAL_PACKS = [
  {
    id: 'pack-stock',
    tenantId: 'tenant-techzone-01',
    code: 'stock',
    name: 'Gestion de Stock & Inventaires',
    shortName: 'Stock',
    description: 'Pack modulaire complet de gestion des articles, dépôts multiples, inventaires tournants et mouvements de stock.',
    categoryId: 'cat_commerce',
    category: 'Commerce & Stock',
    iconKey: 'Boxes',
    logoRef: null,
    status: PACK_STATUS.ACTIVE,
    sourceType: PACK_SOURCE_TYPE.CUSTOM,
    color: '#3B82F6',
    metadata: {
      tags: ['stock', 'inventaire', 'entrepôt', 'logistique'],
      targetAudience: 'Commerçants, Grossistes, Gestionnaires de dépôts',
    },
    currentVersionId: 'pver-stock-120',
    publishedVersionId: 'pver-stock-120',
    publishedVersionNumber: '1.2.0',
    currentVersionNumber: '1.2.0',
    versionsCount: 3,
    modulesCount: 4,
    featuresCount: 12,
    capabilitiesCount: 8,
    dependenciesCount: 3,
    rulesCount: 4,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    createdAt: '2024-05-10T08:00:00.000Z',
    createdBy: 'Administrateur Pack',
    updatedAt: '2024-05-28T14:20:00.000Z',
    updatedBy: 'Administrateur Pack',
    archivedAt: null,
    version: 5,
  },
  {
    id: 'pack-sales',
    tenantId: 'tenant-techzone-01',
    code: 'sales',
    name: 'Ventes, Facturation & Encaissement',
    shortName: 'Ventes',
    description: 'Gestion des devis, commandes clients, factures d’acompte, avoirs et encaissements multi-devises.',
    categoryId: 'cat_commerce',
    category: 'Commerce & Stock',
    iconKey: 'Receipt',
    logoRef: null,
    status: PACK_STATUS.ACTIVE,
    sourceType: PACK_SOURCE_TYPE.CUSTOM,
    color: '#10B981',
    metadata: {
      tags: ['ventes', 'facturation', 'devis', 'caisse', 'client'],
      targetAudience: 'Commerciaux, Caissiers, Responsables comptables',
    },
    currentVersionId: 'pver-sales-140',
    publishedVersionId: 'pver-sales-130',
    publishedVersionNumber: '1.3.0',
    currentVersionNumber: '1.4.0-draft',
    versionsCount: 4,
    modulesCount: 5,
    featuresCount: 18,
    capabilitiesCount: 11,
    dependenciesCount: 4,
    rulesCount: 6,
    validationStatus: PACK_VALIDATION_STATUS.OUTDATED,
    manifestStatus: PACK_MANIFEST_STATUS.OUTDATED,
    createdAt: '2024-04-15T09:30:00.000Z',
    createdBy: 'Administrateur Pack',
    updatedAt: '2024-05-27T16:45:00.000Z',
    updatedBy: 'Architecte Produit',
    archivedAt: null,
    version: 8,
  },
  {
    id: 'pack-restaurant',
    tenantId: 'tenant-techzone-01',
    code: 'restaurant',
    name: 'Restauration, Tables & Cuisine',
    shortName: 'Restauration',
    description: 'Plan de salle interactif, prise de commande sur tablette, écran d’affichage cuisine (KDS) et partages de notes.',
    categoryId: 'cat_service',
    category: 'Services & CHR',
    iconKey: 'Utensils',
    logoRef: null,
    status: PACK_STATUS.ACTIVE,
    sourceType: PACK_SOURCE_TYPE.TEMPLATE,
    color: '#F59E0B',
    metadata: {
      tags: ['restaurant', 'tables', 'cuisine', 'kds', 'bar'],
      targetAudience: 'Restaurateurs, Serveurs, Chefs de cuisine',
    },
    currentVersionId: 'pver-resto-120',
    publishedVersionId: 'pver-resto-110',
    publishedVersionNumber: '1.1.0',
    currentVersionNumber: '1.2.0-rc',
    versionsCount: 2,
    modulesCount: 3,
    featuresCount: 9,
    capabilitiesCount: 6,
    dependenciesCount: 2,
    rulesCount: 3,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    createdAt: '2024-05-01T11:00:00.000Z',
    createdBy: 'Administrateur Pack',
    updatedAt: '2024-05-26T10:15:00.000Z',
    updatedBy: 'Lead Developer',
    archivedAt: null,
    version: 4,
  },
  {
    id: 'pack-garage',
    tenantId: 'tenant-techzone-01',
    code: 'garage',
    name: 'Garage & Atelier Mécanique',
    shortName: 'Garage',
    description: 'Ordres de réparation (OR), devis carrosserie, pièces détachées et planning des ponts de levage.',
    categoryId: 'cat_auto',
    category: 'Automobile',
    iconKey: 'Wrench',
    logoRef: null,
    status: PACK_STATUS.ACTIVE,
    sourceType: PACK_SOURCE_TYPE.CUSTOM,
    color: '#8B5CF6',
    metadata: {
      tags: ['garage', 'automobile', 'réparation', 'véhicule', 'atelier'],
      targetAudience: 'Garagistes, Mécaniciens, Gestionnaires de flotte',
    },
    currentVersionId: 'pver-gar-100',
    publishedVersionId: null,
    publishedVersionNumber: null,
    currentVersionNumber: '1.0.0-ready',
    versionsCount: 1,
    modulesCount: 4,
    featuresCount: 14,
    capabilitiesCount: 7,
    dependenciesCount: 2,
    rulesCount: 2,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    createdAt: '2024-05-18T14:00:00.000Z',
    createdBy: 'Administrateur Pack',
    updatedAt: '2024-05-28T09:10:00.000Z',
    updatedBy: 'Administrateur Pack',
    archivedAt: null,
    version: 3,
  },
  {
    id: 'pack-catalog',
    tenantId: 'tenant-techzone-01',
    code: 'catalog',
    name: 'Catalogue Centralisé des Produits & Tarifs',
    shortName: 'Catalogue',
    description: 'Gestion des fiches articles, grilles tarifaires par segment, déclinaisons, codes-barres et catégories.',
    categoryId: 'cat_commerce',
    category: 'Commerce & Stock',
    iconKey: 'Layers',
    logoRef: null,
    status: PACK_STATUS.ACTIVE,
    sourceType: PACK_SOURCE_TYPE.SYSTEM,
    color: '#06B6D4',
    metadata: {
      tags: ['catalogue', 'produits', 'tarifs', 'articles', 'ean'],
      targetAudience: 'Gestionnaires de catalogue, Responsables pricing',
    },
    currentVersionId: 'pver-cat-200',
    publishedVersionId: 'pver-cat-200',
    publishedVersionNumber: '2.0.0',
    currentVersionNumber: '2.0.0',
    versionsCount: 3,
    modulesCount: 3,
    featuresCount: 10,
    capabilitiesCount: 9,
    dependenciesCount: 1,
    rulesCount: 2,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    createdAt: '2024-03-01T10:00:00.000Z',
    createdBy: 'System Engine',
    updatedAt: '2024-05-20T12:00:00.000Z',
    updatedBy: 'System Engine',
    archivedAt: null,
    version: 6,
  },
  {
    id: 'pack-analytics',
    tenantId: 'tenant-techzone-01',
    code: 'analytics',
    name: 'Analytics, KPI & Tableaux de Bord',
    shortName: 'Analytics',
    description: 'Moteur de métriques décisionnelles, exports automatisés, calcul de rentabilité et rapports périodiques.',
    categoryId: 'cat_reporting',
    category: 'Reporting & Décisionnel',
    iconKey: 'TrendingUp',
    logoRef: null,
    status: PACK_STATUS.ACTIVE,
    sourceType: PACK_SOURCE_TYPE.CUSTOM,
    color: '#EC4899',
    metadata: {
      tags: ['analytics', 'reporting', 'kpi', 'export', 'décisionnel'],
      targetAudience: 'Directeurs généraux, Analystes, Responsables de pôle',
    },
    currentVersionId: 'pver-ana-110',
    publishedVersionId: 'pver-ana-100',
    publishedVersionNumber: '1.0.0',
    currentVersionNumber: '1.1.0-draft',
    versionsCount: 2,
    modulesCount: 2,
    featuresCount: 6,
    capabilitiesCount: 4,
    dependenciesCount: 3,
    rulesCount: 3,
    validationStatus: PACK_VALIDATION_STATUS.INVALID,
    manifestStatus: PACK_MANIFEST_STATUS.INVALID,
    createdAt: '2024-05-12T15:30:00.000Z',
    createdBy: 'Administrateur Pack',
    updatedAt: '2024-05-28T11:00:00.000Z',
    updatedBy: 'Architecte Produit',
    archivedAt: null,
    version: 4,
  },
  {
    id: 'pack-legacy-pos',
    tenantId: 'tenant-techzone-01',
    code: 'legacy-pos',
    name: 'Ancien Module Caisse (Déprécié)',
    shortName: 'Legacy POS',
    description: 'Ancienne version de caisse enregistreuse monolithique, remplacée par le pack Sales v1.3+.',
    categoryId: 'cat_commerce',
    category: 'Commerce & Stock',
    iconKey: 'Archive',
    logoRef: null,
    status: PACK_STATUS.DEPRECATED,
    sourceType: PACK_SOURCE_TYPE.CUSTOM,
    color: '#64748B',
    metadata: {
      tags: ['legacy', 'caisse', 'obsolète'],
    },
    currentVersionId: 'pver-leg-090',
    publishedVersionId: 'pver-leg-090',
    publishedVersionNumber: '0.9.0',
    currentVersionNumber: '0.9.0',
    versionsCount: 1,
    modulesCount: 2,
    featuresCount: 4,
    capabilitiesCount: 2,
    dependenciesCount: 1,
    rulesCount: 1,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    createdAt: '2023-11-10T10:00:00.000Z',
    createdBy: 'System Engine',
    updatedAt: '2024-01-15T09:00:00.000Z',
    updatedBy: 'Administrateur Pack',
    archivedAt: null,
    version: 2,
  },
];

export const INITIAL_PACK_VERSIONS = [
  {
    id: 'pver-stock-120',
    packId: 'pack-stock',
    versionNumber: '1.2.0',
    label: 'Version 1.2.0 (Stable Multi-entrepôts)',
    description: 'Support complet du multi-dépôts avec traçabilité par numéro de lot et inventaires consolidés.',
    status: PACK_VERSION_STATUS.PUBLISHED,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    sourceVersionId: 'pver-stock-110',
    snapshotHash: 'sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    manifestHash: 'sha256:9a4b82c1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126a1b2',
    contractVersion: '1.0',
    publishedAt: '2024-05-25T10:00:00.000Z',
    publishedBy: 'Administrateur Pack',
    createdAt: '2024-05-15T08:00:00.000Z',
    updatedAt: '2024-05-25T10:00:00.000Z',
    version: 4,
    modulesCount: 4,
    featuresCount: 12,
    dependenciesCount: 3,
    rulesCount: 4,
  },
  {
    id: 'pver-sales-130',
    packId: 'pack-sales',
    versionNumber: '1.3.0',
    label: 'Version 1.3.0 (Production Stable)',
    description: 'Facturation conforme, TVA multi-taux et export comptable FEC.',
    status: PACK_VERSION_STATUS.PUBLISHED,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    sourceVersionId: null,
    snapshotHash: 'sha256:4a3b82c1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d44a',
    manifestHash: 'sha256:1e2f3a4b82c1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126',
    contractVersion: '1.0',
    publishedAt: '2024-05-20T14:30:00.000Z',
    publishedBy: 'Administrateur Pack',
    createdAt: '2024-05-01T09:00:00.000Z',
    updatedAt: '2024-05-20T14:30:00.000Z',
    version: 6,
    modulesCount: 5,
    featuresCount: 18,
    dependenciesCount: 4,
    rulesCount: 6,
  },
  {
    id: 'pver-sales-140',
    packId: 'pack-sales',
    versionNumber: '1.4.0-draft',
    label: 'Version 1.4.0 (Draft — Paiement fractionné)',
    description: 'Intégration du paiement en 3x/4x et réconciliation bancaire instantanée.',
    status: PACK_VERSION_STATUS.CONFIGURING,
    validationStatus: PACK_VALIDATION_STATUS.OUTDATED,
    manifestStatus: PACK_MANIFEST_STATUS.OUTDATED,
    sourceVersionId: 'pver-sales-130',
    snapshotHash: null,
    manifestHash: null,
    contractVersion: '1.0',
    publishedAt: null,
    createdAt: '2024-05-26T10:00:00.000Z',
    updatedAt: '2024-05-27T16:45:00.000Z',
    version: 2,
    modulesCount: 5,
    featuresCount: 20,
    dependenciesCount: 5,
    rulesCount: 7,
  },
  {
    id: 'pver-gar-100',
    packId: 'pack-garage',
    versionNumber: '1.0.0',
    label: 'Version 1.0.0 (Prête pour publication)',
    description: 'Première version officielle de gestion d atelier automobile.',
    status: PACK_VERSION_STATUS.READY,
    validationStatus: PACK_VALIDATION_STATUS.VALID,
    manifestStatus: PACK_MANIFEST_STATUS.VALID,
    sourceVersionId: null,
    snapshotHash: 'sha256:6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f',
    manifestHash: 'sha256:5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f6e7f8a9b0c1d2e3f4a',
    contractVersion: '1.0',
    publishedAt: null,
    createdAt: '2024-05-18T14:00:00.000Z',
    updatedAt: '2024-05-28T09:10:00.000Z',
    version: 3,
    modulesCount: 4,
    featuresCount: 14,
    dependenciesCount: 2,
    rulesCount: 2,
  },
  {
    id: 'pver-ana-110',
    packId: 'pack-analytics',
    versionNumber: '1.1.0-draft',
    label: 'Version 1.1.0 (En validation — Bloquée)',
    description: 'Nouveaux tableaux de bord temps réel avec prévisions par IA.',
    status: PACK_VERSION_STATUS.VALIDATING,
    validationStatus: PACK_VALIDATION_STATUS.INVALID,
    manifestStatus: PACK_MANIFEST_STATUS.INVALID,
    sourceVersionId: 'pver-ana-100',
    snapshotHash: null,
    manifestHash: null,
    contractVersion: '1.0',
    publishedAt: null,
    createdAt: '2024-05-22T09:00:00.000Z',
    updatedAt: '2024-05-28T11:00:00.000Z',
    version: 2,
    modulesCount: 2,
    featuresCount: 6,
    dependenciesCount: 3,
    rulesCount: 3,
  },
];

export const INITIAL_PACK_CATEGORIES = [
  { id: 'cat_all', name: 'Toutes les catégories', count: 7 },
  { id: 'cat_commerce', name: 'Commerce & Stock', count: 4 },
  { id: 'cat_service', name: 'Services & CHR', count: 1 },
  { id: 'cat_auto', name: 'Automobile', count: 1 },
  { id: 'cat_reporting', name: 'Reporting & Décisionnel', count: 1 },
];

export const INITIAL_PACK_ATTENTION_ITEMS = [
  {
    id: 'att-01',
    severity: 'CRITICAL',
    packId: 'pack-analytics',
    packCode: 'analytics',
    packName: 'Analytics & Reporting',
    versionNumber: '1.1.0-draft',
    versionId: 'pver-ana-110',
    title: 'Dépendance obligatoire non résolue',
    description: 'La dépendance requise vers "catalog >= 2.0.0" est introuvable ou incompatible.',
    target: 'Dependency: catalog >= 2.0.0',
    source: 'PM-CDC-06 Dependency Resolver',
    actionLabel: 'Résoudre dépendances',
    actionRoute: 'pack-dependencies',
    createdAt: '2024-05-28T11:00:00.000Z',
  },
  {
    id: 'att-02',
    severity: 'ERROR',
    packId: 'pack-analytics',
    packCode: 'analytics',
    packName: 'Analytics & Reporting',
    versionNumber: '1.1.0-draft',
    versionId: 'pver-ana-110',
    title: 'Génération Pack Manifest échouée',
    description: 'Le contrat du Pack Manifest ne peut être assemblé en raison de règles de composition en conflit.',
    target: 'Rule: analytics.forecast.beta',
    source: 'PM-CDC-00 Manifest Builder',
    actionLabel: 'Vérifier les règles',
    actionRoute: 'pack-rules',
    createdAt: '2024-05-28T11:02:00.000Z',
  },
  {
    id: 'att-03',
    severity: 'WARNING',
    packId: 'pack-sales',
    packCode: 'sales',
    packName: 'Ventes & Facturation',
    versionNumber: '1.4.0-draft',
    versionId: 'pver-sales-140',
    title: 'Validation de version obsolète (OUTDATED)',
    description: 'Des modifications ont été apportées aux modules depuis la dernière validation réussie.',
    target: 'Module: sales.payment_split',
    source: 'PM-CDC-03 Version Validator',
    actionLabel: 'Re-valider la version',
    actionRoute: 'pack-versions',
    createdAt: '2024-05-27T16:45:00.000Z',
  },
  {
    id: 'att-04',
    severity: 'INFO',
    packId: 'pack-garage',
    packCode: 'garage',
    packName: 'Garage Automobile',
    versionNumber: '1.0.0',
    versionId: 'pver-gar-100',
    title: 'Version validée prête à la publication',
    description: 'Tous les modules, features, capabilities et dépendances sont valides. Le Pack Manifest est scellé.',
    target: 'PackVersion: v1.0.0',
    source: 'PM-CDC-03 Release Pipeline',
    actionLabel: 'Publier la version',
    actionRoute: 'pack-versions',
    createdAt: '2024-05-28T09:10:00.000Z',
  },
];

export const INITIAL_PACK_ACTIVITIES = [
  {
    id: 'pact-01',
    traceId: 'trc_pm_098271',
    actor: 'Administrateur Pack',
    role: 'ADMIN',
    action: 'pack.version.ready',
    packCode: 'garage',
    packName: 'Garage Automobile',
    versionNumber: '1.0.0',
    details: 'Validation réussie : transition vers READY pour publication.',
    status: 'SUCCESS',
    timestamp: '2024-05-28T09:10:00.000Z',
  },
  {
    id: 'pact-02',
    traceId: 'trc_pm_098264',
    actor: 'Architecte Produit',
    role: 'BUILDER',
    action: 'pack.module.updated',
    packCode: 'sales',
    packName: 'Ventes & Facturation',
    versionNumber: '1.4.0-draft',
    details: 'Ajout du module Paiement fractionné (sales.payment_split). Validation marquée OUTDATED.',
    status: 'SUCCESS',
    timestamp: '2024-05-27T16:45:00.000Z',
  },
  {
    id: 'pact-03',
    traceId: 'trc_pm_098251',
    actor: 'Administrateur Pack',
    role: 'ADMIN',
    action: 'pack.version.published',
    packCode: 'stock',
    packName: 'Gestion de Stock',
    versionNumber: '1.2.0',
    details: 'Publication de la version 1.2.0. Snapshot scellé et Pack Manifest publié au Pack Runtime.',
    status: 'SUCCESS',
    timestamp: '2024-05-25T10:00:00.000Z',
  },
  {
    id: 'pact-04',
    traceId: 'trc_pm_098240',
    actor: 'Architecte Produit',
    role: 'BUILDER',
    action: 'pack.dependency.conflict_detected',
    packCode: 'analytics',
    packName: 'Analytics & Reporting',
    versionNumber: '1.1.0-draft',
    details: 'Conflit détecté entre la dépendance catalog >= 2.0.0 et la version active 1.2.0.',
    status: 'BLOCKED',
    timestamp: '2024-05-28T11:00:00.000Z',
  },
];

// PM-CDC-04 Modules Seed
export const INITIAL_PACK_MODULES = [
  // Stock Pack Modules (for pver-stock-120)
  {
    id: 'mod-stock-items',
    packVersionId: 'pver-stock-120',
    packId: 'pack-stock',
    code: 'stock.items',
    name: 'Référentiel Articles & Nomenclatures',
    shortName: 'Articles',
    description: 'Gestion des fiches produits, références UVC, code-barres EAN13/UPC et conditionnements.',
    moduleType: 'CORE',
    isRequired: true,
    isDefaultEnabled: true,
    sortOrder: 1,
    iconKey: 'Package',
    status: 'ACTIVE',
    featuresCount: 4,
    capabilitiesCount: 2,
    createdAt: '2024-05-15T08:00:00.000Z',
  },
  {
    id: 'mod-stock-warehouses',
    packVersionId: 'pver-stock-120',
    packId: 'pack-stock',
    code: 'stock.warehouses',
    name: 'Multi-Entrepôts & Emplacements',
    shortName: 'Entrepôts',
    description: 'Topologie de dépôts multiples, zones de picking, allées, travées et niveaux.',
    moduleType: 'STANDARD',
    isRequired: false,
    isDefaultEnabled: true,
    sortOrder: 2,
    iconKey: 'Boxes',
    status: 'ACTIVE',
    featuresCount: 3,
    capabilitiesCount: 2,
    createdAt: '2024-05-15T08:00:00.000Z',
  },
  {
    id: 'mod-stock-movements',
    packVersionId: 'pver-stock-120',
    packId: 'pack-stock',
    code: 'stock.movements',
    name: 'Mouvements & Traçabilité Lots',
    shortName: 'Mouvements',
    description: 'Entrées en stock, sorties de consommation, transferts inter-dépôts et numéros de série/lots.',
    moduleType: 'STANDARD',
    isRequired: false,
    isDefaultEnabled: true,
    sortOrder: 3,
    iconKey: 'Truck',
    status: 'ACTIVE',
    featuresCount: 3,
    capabilitiesCount: 2,
    createdAt: '2024-05-15T08:00:00.000Z',
  },
  {
    id: 'mod-stock-inventory',
    packVersionId: 'pver-stock-120',
    packId: 'pack-stock',
    code: 'stock.inventory',
    name: 'Inventaires Tournants & Régularisations',
    shortName: 'Inventaires',
    description: 'Campagnes d’inventaire physique avec écarts valorisés et ajustements automatiques.',
    moduleType: 'EXTENSION',
    isRequired: false,
    isDefaultEnabled: false,
    sortOrder: 4,
    iconKey: 'FileCheck',
    status: 'ACTIVE',
    featuresCount: 2,
    capabilitiesCount: 2,
    createdAt: '2024-05-15T08:00:00.000Z',
  },

  // Sales Pack Modules (for pver-sales-130 & pver-sales-140)
  {
    id: 'mod-sales-quotes',
    packVersionId: 'pver-sales-130',
    packId: 'pack-sales',
    code: 'sales.quotes',
    name: 'Devis & Propositions Commerciales',
    shortName: 'Devis',
    description: 'Génération de devis chiffrés avec signature électronique et validation client.',
    moduleType: 'STANDARD',
    isRequired: false,
    isDefaultEnabled: true,
    sortOrder: 1,
    iconKey: 'FileText',
    status: 'ACTIVE',
    featuresCount: 4,
    capabilitiesCount: 2,
    createdAt: '2024-05-01T09:00:00.000Z',
  },
  {
    id: 'mod-sales-invoicing',
    packVersionId: 'pver-sales-130',
    packId: 'pack-sales',
    code: 'sales.invoicing',
    name: 'Facturation & Avoirs Légaux',
    shortName: 'Facturation',
    description: 'Factures proforma, acomptes, factures définitives et avoirs numérotés séquentiellement.',
    moduleType: 'CORE',
    isRequired: true,
    isDefaultEnabled: true,
    sortOrder: 2,
    iconKey: 'Receipt',
    status: 'ACTIVE',
    featuresCount: 5,
    capabilitiesCount: 3,
    createdAt: '2024-05-01T09:00:00.000Z',
  },
  {
    id: 'mod-sales-payments',
    packVersionId: 'pver-sales-130',
    packId: 'pack-sales',
    code: 'sales.payments',
    name: 'Encaissement & Moyens de Paiement',
    shortName: 'Encaissement',
    description: 'Règlements multi-moyens (CB, Espèces, Chèques, Virements) et journal de caisse.',
    moduleType: 'STANDARD',
    isRequired: false,
    isDefaultEnabled: true,
    sortOrder: 3,
    iconKey: 'CreditCard',
    status: 'ACTIVE',
    featuresCount: 4,
    capabilitiesCount: 2,
    createdAt: '2024-05-01T09:00:00.000Z',
  },
  {
    id: 'mod-sales-payment-split',
    packVersionId: 'pver-sales-140',
    packId: 'pack-sales',
    code: 'sales.payment_split',
    name: 'Paiement Fractionné (3x/4x)',
    shortName: 'Fractionné',
    description: 'Échéanciers de paiement automatique et recouvrement échelonné.',
    moduleType: 'EXTENSION',
    isRequired: false,
    isDefaultEnabled: false,
    sortOrder: 4,
    iconKey: 'Layers',
    status: 'ACTIVE',
    featuresCount: 3,
    capabilitiesCount: 2,
    createdAt: '2024-05-26T10:00:00.000Z',
  },

  // Garage Modules
  {
    id: 'mod-gar-or',
    packVersionId: 'pver-gar-100',
    packId: 'pack-garage',
    code: 'garage.repair_orders',
    name: 'Ordres de Réparation (OR) & Diagnostic',
    shortName: 'OR & Diagnostic',
    description: 'Prise en charge du véhicule, check-in photo, devis pièces/main d’œuvre.',
    moduleType: 'CORE',
    isRequired: true,
    isDefaultEnabled: true,
    sortOrder: 1,
    iconKey: 'Wrench',
    status: 'ACTIVE',
    featuresCount: 5,
    capabilitiesCount: 3,
    createdAt: '2024-05-18T14:00:00.000Z',
  },
  {
    id: 'mod-gar-planning',
    packVersionId: 'pver-gar-100',
    packId: 'pack-garage',
    code: 'garage.bay_planning',
    name: 'Planning des Ponts & Mécaniciens',
    shortName: 'Planning Atelier',
    description: 'Affectation des ponts de levage, gestion des temps barémés constructeur.',
    moduleType: 'STANDARD',
    isRequired: false,
    isDefaultEnabled: true,
    sortOrder: 2,
    iconKey: 'Calendar',
    status: 'ACTIVE',
    featuresCount: 4,
    capabilitiesCount: 2,
    createdAt: '2024-05-18T14:00:00.000Z',
  },
];

// PM-CDC-04 Features Seed
export const INITIAL_PACK_FEATURES = [
  // Stock Items Features
  {
    id: 'feat-stock-ean',
    moduleId: 'mod-stock-items',
    packVersionId: 'pver-stock-120',
    code: 'stock.items.barcode_scanning',
    name: 'Scan Code-Barres & Douchette',
    featureType: 'TOGGLE',
    isRequired: false,
    isDefaultEnabled: true,
    enabled: true,
    description: 'Support des scanners laser USB et caméras embarquées pour la recherche rapide.',
  },
  {
    id: 'feat-stock-variants',
    moduleId: 'mod-stock-items',
    packVersionId: 'pver-stock-120',
    code: 'stock.items.variants_matrix',
    name: 'Matrice Variantes (Taille / Couleur)',
    featureType: 'CONFIGURABLE',
    isRequired: false,
    isDefaultEnabled: true,
    enabled: true,
    description: 'Gestion des grilles bi-dimensionnelles d’articles combinés.',
  },
  {
    id: 'feat-stock-serial',
    moduleId: 'mod-stock-movements',
    packVersionId: 'pver-stock-120',
    code: 'stock.movements.serial_tracking',
    name: 'Traçabilité Unitaire par N° de Série',
    featureType: 'TOGGLE',
    isRequired: false,
    isDefaultEnabled: false,
    enabled: false,
    description: 'Impose la saisie du numéro de série lors de chaque transfert et vente.',
  },
  {
    id: 'feat-stock-lots',
    moduleId: 'mod-stock-movements',
    packVersionId: 'pver-stock-120',
    code: 'stock.movements.batch_expiry',
    name: 'Gestion des Lots & Dates de Péremption (DLC/DLUO)',
    featureType: 'TOGGLE',
    isRequired: false,
    isDefaultEnabled: true,
    enabled: true,
    description: 'Gestion FIFO/FEFO selon la date limite de consommation.',
  },

  // Sales Features
  {
    id: 'feat-sales-einvoicing',
    moduleId: 'mod-sales-invoicing',
    packVersionId: 'pver-sales-130',
    code: 'sales.invoicing.facturx',
    name: 'Export Factur-X & Facturation Électronique',
    featureType: 'TOGGLE',
    isRequired: true,
    isDefaultEnabled: true,
    enabled: true,
    description: 'Génération automatique du PDF/A-3 avec XML chorus Pro embarqué.',
  },
  {
    id: 'feat-sales-pos-caisse',
    moduleId: 'mod-sales-payments',
    packVersionId: 'pver-sales-130',
    code: 'sales.payments.cash_drawer',
    name: 'Gestion Tiroir-Caisse & X/Z de Caisse',
    featureType: 'TOGGLE',
    isRequired: false,
    isDefaultEnabled: true,
    enabled: true,
    description: 'Clôture journalière conforme NF525 avec scellement cryptographique.',
  },
  {
    id: 'feat-sales-split-3x',
    moduleId: 'mod-sales-payment-split',
    packVersionId: 'pver-sales-140',
    code: 'sales.payments.split_schedules',
    name: 'Échéancier de Prélèvement Automatique',
    featureType: 'CONFIGURABLE',
    isRequired: false,
    isDefaultEnabled: true,
    enabled: true,
    description: 'Génération de mandats SEPA et échéanciers 3x sans frais.',
  },
];

// PM-CDC-05 Capabilities Seed (PROVIDES, REQUIRES, USES)
export const INITIAL_PACK_CAPABILITIES = [
  {
    id: 'cap-01',
    packVersionId: 'pver-stock-120',
    packCode: 'stock',
    capabilityCode: 'stock.valuation.fifo',
    relationType: 'PROVIDES',
    name: 'Valorisation FIFO & PMP',
    category: 'INVENTORY',
    description: 'Fournit le calcul du prix moyen pondéré et valorisation en temps réel.',
    stability: 'STABLE',
  },
  {
    id: 'cap-02',
    packVersionId: 'pver-stock-120',
    packCode: 'stock',
    capabilityCode: 'catalog.articles.read',
    relationType: 'REQUIRES',
    name: 'Lecture Catalogue Articles',
    category: 'CATALOG',
    description: 'Nécessite l’accès au référentiel d’articles pour les mouvements de stock.',
    stability: 'STABLE',
  },
  {
    id: 'cap-03',
    packVersionId: 'pver-sales-130',
    packCode: 'sales',
    capabilityCode: 'billing.invoice.create',
    relationType: 'PROVIDES',
    name: 'Création Factures & Avoirs',
    category: 'BILLING',
    description: 'Fournit la génération légale des factures clients.',
    stability: 'STABLE',
  },
  {
    id: 'cap-04',
    packVersionId: 'pver-sales-130',
    packCode: 'sales',
    capabilityCode: 'stock.decrement.on_sale',
    relationType: 'USES',
    name: 'Décrémentation de Stock Vente',
    category: 'INVENTORY',
    description: 'Utilise le module de stock pour décompter les pièces lors de la facturation.',
    stability: 'STABLE',
  },
  {
    id: 'cap-05',
    packVersionId: 'pver-gar-100',
    packCode: 'garage',
    capabilityCode: 'garage.or.create',
    relationType: 'PROVIDES',
    name: 'Création Ordres de Réparation',
    category: 'AUTOMOTIVE',
    description: 'Génère et suit les dossiers d’atelier mécanique.',
    stability: 'STABLE',
  },
  {
    id: 'cap-06',
    packVersionId: 'pver-gar-100',
    packCode: 'garage',
    capabilityCode: 'billing.invoice.create',
    relationType: 'REQUIRES',
    name: 'Facturation Atelier Recommandée',
    category: 'BILLING',
    description: 'Nécessite un moteur de facturation pour clore les OR.',
    stability: 'STABLE',
  },
];

// PM-CDC-06 Dependencies Seed
export const INITIAL_PACK_DEPENDENCIES = [
  {
    id: 'dep-01',
    sourcePackVersionId: 'pver-stock-120',
    sourcePackCode: 'stock',
    targetPackCode: 'catalog',
    versionRange: '^2.0.0',
    dependencyType: 'REQUIRED',
    resolutionStatus: 'RESOLVED',
    resolvedVersion: '2.0.0',
    description: 'Le pack Stock requiert le catalogue d’articles centralisé.',
  },
  {
    id: 'dep-02',
    sourcePackVersionId: 'pver-sales-130',
    sourcePackCode: 'sales',
    targetPackCode: 'catalog',
    versionRange: '>=2.0.0',
    dependencyType: 'REQUIRED',
    resolutionStatus: 'RESOLVED',
    resolvedVersion: '2.0.0',
    description: 'Le pack Sales requiert les tarifs articles du catalogue.',
  },
  {
    id: 'dep-03',
    sourcePackVersionId: 'pver-sales-130',
    sourcePackCode: 'sales',
    targetPackCode: 'stock',
    versionRange: '^1.2.0',
    dependencyType: 'OPTIONAL',
    resolutionStatus: 'RESOLVED',
    resolvedVersion: '1.2.0',
    description: 'Synchronisation optionnelle avec le stock pour la réservation d’articles.',
  },
  {
    id: 'dep-04',
    sourcePackVersionId: 'pver-gar-100',
    sourcePackCode: 'garage',
    targetPackCode: 'sales',
    versionRange: '^1.3.0',
    dependencyType: 'REQUIRED',
    resolutionStatus: 'RESOLVED',
    resolvedVersion: '1.3.0',
    description: 'Facturation des interventions d’atelier mécanique.',
  },
  {
    id: 'dep-05',
    sourcePackVersionId: 'pver-gar-100',
    sourcePackCode: 'garage',
    targetPackCode: 'stock',
    versionRange: '^1.2.0',
    dependencyType: 'REQUIRED',
    resolutionStatus: 'RESOLVED',
    resolvedVersion: '1.2.0',
    description: 'Gestion du stock de pièces détachées et consommables atelier.',
  },
  {
    id: 'dep-06',
    sourcePackVersionId: 'pver-ana-110',
    sourcePackCode: 'analytics',
    targetPackCode: 'catalog',
    versionRange: '>=2.0.0',
    dependencyType: 'REQUIRED',
    resolutionStatus: 'UNRESOLVED',
    resolvedVersion: null,
    conflictReason: 'Version requise non satisfaite ou connecteur non instancié',
    description: 'Reporting de rentabilité par article du catalogue.',
  },
];

// PM-CDC-07 Composition Rules Seed
export const INITIAL_PACK_RULES = [
  {
    id: 'rule-01',
    packVersionId: 'pver-stock-120',
    packCode: 'stock',
    code: 'rule.stock.serial_requires_movements',
    name: 'N° de Série impose Module Mouvements',
    ruleType: 'COMPOSITION',
    trigger: 'ON_FEATURE_CHANGE',
    priority: 10,
    isActive: true,
    description: 'L’activation de la traçabilité par n° de série requiert impérativement le module stock.movements.',
    condition: {
      combinator: 'AND',
      predicates: [
        { field: 'features.stock.movements.serial_tracking', operator: 'EQUALS', value: true },
      ],
    },
    effect: {
      type: 'REQUIRE_MODULE',
      target: 'stock.movements',
      message: 'Le module de mouvements est requis pour tracer les numéros de série.',
    },
  },
  {
    id: 'rule-02',
    packVersionId: 'pver-sales-140',
    packCode: 'sales',
    code: 'rule.sales.split_requires_invoicing',
    name: 'Paiement fractionné requiert Facturation légale',
    ruleType: 'COMPOSITION',
    trigger: 'ON_MODULE_ENABLE',
    priority: 20,
    isActive: true,
    description: 'L’échéancier fractionné 3x ne peut être actif sans le module de facturation légale.',
    condition: {
      combinator: 'AND',
      predicates: [
        { field: 'modules.sales.payment_split', operator: 'EQUALS', value: true },
      ],
    },
    effect: {
      type: 'REQUIRE_MODULE',
      target: 'sales.invoicing',
      message: 'La facturation légale est indispensable pour émettre des échéances fractionnées.',
    },
  },
  {
    id: 'rule-03',
    packVersionId: 'pver-sales-130',
    packCode: 'sales',
    code: 'rule.sales.facturx_mandatory_in_b2b',
    name: 'Factur-X obligatoire en B2B',
    ruleType: 'VALIDATION',
    trigger: 'GLOBAL_EVAL',
    priority: 30,
    isActive: true,
    description: 'Si le client est une entreprise (B2B), le format Factur-X doit être forcé.',
    condition: {
      combinator: 'AND',
      predicates: [
        { field: 'context.customer_type', operator: 'EQUALS', value: 'B2B' },
      ],
    },
    effect: {
      type: 'ENABLE_FEATURE',
      target: 'sales.invoicing.facturx',
      message: 'Format Factur-X activé automatiquement pour les flux B2B.',
    },
  },
  {
    id: 'rule-04',
    packVersionId: 'pver-gar-100',
    packCode: 'garage',
    code: 'rule.garage.requires_sales_or_stock',
    name: 'OR Garage requiert Sales ou Pièces de Stock',
    ruleType: 'INTEGRITY',
    trigger: 'GLOBAL_EVAL',
    priority: 15,
    isActive: true,
    description: 'Un atelier doit avoir accès soit à la facturation, soit au stock de pièces.',
    condition: {
      combinator: 'OR',
      predicates: [
        { field: 'dependencies.sales.resolved', operator: 'EQUALS', value: true },
        { field: 'dependencies.stock.resolved', operator: 'EQUALS', value: true },
      ],
    },
    effect: {
      type: 'VALIDATION_PASS',
      target: 'garage.repair_orders',
      message: 'Intégrité d’atelier vérifiée.',
    },
  },
];
